load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "seq",
    srcs = ["seq.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/lib/seq",
    visibility = ["//visibility:public"],
)

