load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//enterprise:__subpackages__"])

go_library(
    name = "pebble",
    srcs = ["pebble.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/util/pebble",
    visibility = ["//visibility:public"],
    deps = [
        "//server/metrics",
        "//server/util/alert",
        "//server/util/log",
        "//server/util/proto",
        "//server/util/status",
        "@com_github_cockroachdb_pebble//:pebble",
        "@com_github_cockroachdb_pebble//bloom",
        "@com_github_cockroachdb_pebble//vfs",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)

