// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/stat_filter.proto

package stat_filter

import (
	invocation_status "github.com/buildbuddy-io/buildbuddy/proto/invocation_status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvocationMetricType int32

const (
	InvocationMetricType_UNKNOWN_INVOCATION_METRIC                  InvocationMetricType = 0
	InvocationMetricType_DURATION_USEC_INVOCATION_METRIC            InvocationMetricType = 1
	InvocationMetricType_CAS_CACHE_MISSES_INVOCATION_METRIC         InvocationMetricType = 2
	InvocationMetricType_UPDATED_AT_USEC_INVOCATION_METRIC          InvocationMetricType = 3
	InvocationMetricType_CAS_CACHE_DOWNLOAD_SIZE_INVOCATION_METRIC  InvocationMetricType = 4
	InvocationMetricType_CAS_CACHE_DOWNLOAD_SPEED_INVOCATION_METRIC InvocationMetricType = 5
	InvocationMetricType_CAS_CACHE_UPLOAD_SIZE_INVOCATION_METRIC    InvocationMetricType = 6
	InvocationMetricType_CAS_CACHE_UPLOAD_SPEED_INVOCATION_METRIC   InvocationMetricType = 7
	InvocationMetricType_ACTION_CACHE_MISSES_INVOCATION_METRIC      InvocationMetricType = 8
	InvocationMetricType_TIME_SAVED_USEC_INVOCATION_METRIC          InvocationMetricType = 9
)

// Enum value maps for InvocationMetricType.
var (
	InvocationMetricType_name = map[int32]string{
		0: "UNKNOWN_INVOCATION_METRIC",
		1: "DURATION_USEC_INVOCATION_METRIC",
		2: "CAS_CACHE_MISSES_INVOCATION_METRIC",
		3: "UPDATED_AT_USEC_INVOCATION_METRIC",
		4: "CAS_CACHE_DOWNLOAD_SIZE_INVOCATION_METRIC",
		5: "CAS_CACHE_DOWNLOAD_SPEED_INVOCATION_METRIC",
		6: "CAS_CACHE_UPLOAD_SIZE_INVOCATION_METRIC",
		7: "CAS_CACHE_UPLOAD_SPEED_INVOCATION_METRIC",
		8: "ACTION_CACHE_MISSES_INVOCATION_METRIC",
		9: "TIME_SAVED_USEC_INVOCATION_METRIC",
	}
	InvocationMetricType_value = map[string]int32{
		"UNKNOWN_INVOCATION_METRIC":                  0,
		"DURATION_USEC_INVOCATION_METRIC":            1,
		"CAS_CACHE_MISSES_INVOCATION_METRIC":         2,
		"UPDATED_AT_USEC_INVOCATION_METRIC":          3,
		"CAS_CACHE_DOWNLOAD_SIZE_INVOCATION_METRIC":  4,
		"CAS_CACHE_DOWNLOAD_SPEED_INVOCATION_METRIC": 5,
		"CAS_CACHE_UPLOAD_SIZE_INVOCATION_METRIC":    6,
		"CAS_CACHE_UPLOAD_SPEED_INVOCATION_METRIC":   7,
		"ACTION_CACHE_MISSES_INVOCATION_METRIC":      8,
		"TIME_SAVED_USEC_INVOCATION_METRIC":          9,
	}
)

func (x InvocationMetricType) Enum() *InvocationMetricType {
	p := new(InvocationMetricType)
	*p = x
	return p
}

func (x InvocationMetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationMetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[0].Descriptor()
}

func (InvocationMetricType) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[0]
}

func (x InvocationMetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationMetricType.Descriptor instead.
func (InvocationMetricType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{0}
}

type ExecutionMetricType int32

const (
	ExecutionMetricType_UNKNOWN_EXECUTION_METRIC                      ExecutionMetricType = 0
	ExecutionMetricType_QUEUE_TIME_USEC_EXECUTION_METRIC              ExecutionMetricType = 1
	ExecutionMetricType_UPDATED_AT_USEC_EXECUTION_METRIC              ExecutionMetricType = 2
	ExecutionMetricType_INPUT_DOWNLOAD_TIME_EXECUTION_METRIC          ExecutionMetricType = 3
	ExecutionMetricType_REAL_EXECUTION_TIME_EXECUTION_METRIC          ExecutionMetricType = 4
	ExecutionMetricType_OUTPUT_UPLOAD_TIME_EXECUTION_METRIC           ExecutionMetricType = 5
	ExecutionMetricType_PEAK_MEMORY_EXECUTION_METRIC                  ExecutionMetricType = 6
	ExecutionMetricType_INPUT_DOWNLOAD_SIZE_EXECUTION_METRIC          ExecutionMetricType = 7
	ExecutionMetricType_OUTPUT_UPLOAD_SIZE_EXECUTION_METRIC           ExecutionMetricType = 8
	ExecutionMetricType_EXECUTION_WALL_TIME_EXECUTION_METRIC          ExecutionMetricType = 9
	ExecutionMetricType_EXECUTION_CPU_NANOS_EXECUTION_METRIC          ExecutionMetricType = 10
	ExecutionMetricType_EXECUTION_AVERAGE_MILLICORES_EXECUTION_METRIC ExecutionMetricType = 11
)

// Enum value maps for ExecutionMetricType.
var (
	ExecutionMetricType_name = map[int32]string{
		0:  "UNKNOWN_EXECUTION_METRIC",
		1:  "QUEUE_TIME_USEC_EXECUTION_METRIC",
		2:  "UPDATED_AT_USEC_EXECUTION_METRIC",
		3:  "INPUT_DOWNLOAD_TIME_EXECUTION_METRIC",
		4:  "REAL_EXECUTION_TIME_EXECUTION_METRIC",
		5:  "OUTPUT_UPLOAD_TIME_EXECUTION_METRIC",
		6:  "PEAK_MEMORY_EXECUTION_METRIC",
		7:  "INPUT_DOWNLOAD_SIZE_EXECUTION_METRIC",
		8:  "OUTPUT_UPLOAD_SIZE_EXECUTION_METRIC",
		9:  "EXECUTION_WALL_TIME_EXECUTION_METRIC",
		10: "EXECUTION_CPU_NANOS_EXECUTION_METRIC",
		11: "EXECUTION_AVERAGE_MILLICORES_EXECUTION_METRIC",
	}
	ExecutionMetricType_value = map[string]int32{
		"UNKNOWN_EXECUTION_METRIC":                      0,
		"QUEUE_TIME_USEC_EXECUTION_METRIC":              1,
		"UPDATED_AT_USEC_EXECUTION_METRIC":              2,
		"INPUT_DOWNLOAD_TIME_EXECUTION_METRIC":          3,
		"REAL_EXECUTION_TIME_EXECUTION_METRIC":          4,
		"OUTPUT_UPLOAD_TIME_EXECUTION_METRIC":           5,
		"PEAK_MEMORY_EXECUTION_METRIC":                  6,
		"INPUT_DOWNLOAD_SIZE_EXECUTION_METRIC":          7,
		"OUTPUT_UPLOAD_SIZE_EXECUTION_METRIC":           8,
		"EXECUTION_WALL_TIME_EXECUTION_METRIC":          9,
		"EXECUTION_CPU_NANOS_EXECUTION_METRIC":          10,
		"EXECUTION_AVERAGE_MILLICORES_EXECUTION_METRIC": 11,
	}
)

func (x ExecutionMetricType) Enum() *ExecutionMetricType {
	p := new(ExecutionMetricType)
	*p = x
	return p
}

func (x ExecutionMetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[1].Descriptor()
}

func (ExecutionMetricType) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[1]
}

func (x ExecutionMetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMetricType.Descriptor instead.
func (ExecutionMetricType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{1}
}

type InvocationDimensionType int32

const (
	InvocationDimensionType_UNKNOWN_INVOCATION_DIMENSION InvocationDimensionType = 0
	InvocationDimensionType_BRANCH_INVOCATION_DIMENSION  InvocationDimensionType = 1
)

// Enum value maps for InvocationDimensionType.
var (
	InvocationDimensionType_name = map[int32]string{
		0: "UNKNOWN_INVOCATION_DIMENSION",
		1: "BRANCH_INVOCATION_DIMENSION",
	}
	InvocationDimensionType_value = map[string]int32{
		"UNKNOWN_INVOCATION_DIMENSION": 0,
		"BRANCH_INVOCATION_DIMENSION":  1,
	}
)

func (x InvocationDimensionType) Enum() *InvocationDimensionType {
	p := new(InvocationDimensionType)
	*p = x
	return p
}

func (x InvocationDimensionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationDimensionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[2].Descriptor()
}

func (InvocationDimensionType) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[2]
}

func (x InvocationDimensionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationDimensionType.Descriptor instead.
func (InvocationDimensionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{2}
}

type ExecutionDimensionType int32

const (
	ExecutionDimensionType_UNKNOWN_EXECUTION_DIMENSION         ExecutionDimensionType = 0
	ExecutionDimensionType_WORKER_EXECUTION_DIMENSION          ExecutionDimensionType = 1
	ExecutionDimensionType_TARGET_LABEL_EXECUTION_DIMENSION    ExecutionDimensionType = 2
	ExecutionDimensionType_ACTION_MNEMONIC_EXECUTION_DIMENSION ExecutionDimensionType = 3
	ExecutionDimensionType_EFFECTIVE_POOL_EXECUTION_DIMENSION  ExecutionDimensionType = 4
	ExecutionDimensionType_EXIT_CODE_EXECUTION_DIMENSION       ExecutionDimensionType = 5
)

// Enum value maps for ExecutionDimensionType.
var (
	ExecutionDimensionType_name = map[int32]string{
		0: "UNKNOWN_EXECUTION_DIMENSION",
		1: "WORKER_EXECUTION_DIMENSION",
		2: "TARGET_LABEL_EXECUTION_DIMENSION",
		3: "ACTION_MNEMONIC_EXECUTION_DIMENSION",
		4: "EFFECTIVE_POOL_EXECUTION_DIMENSION",
		5: "EXIT_CODE_EXECUTION_DIMENSION",
	}
	ExecutionDimensionType_value = map[string]int32{
		"UNKNOWN_EXECUTION_DIMENSION":         0,
		"WORKER_EXECUTION_DIMENSION":          1,
		"TARGET_LABEL_EXECUTION_DIMENSION":    2,
		"ACTION_MNEMONIC_EXECUTION_DIMENSION": 3,
		"EFFECTIVE_POOL_EXECUTION_DIMENSION":  4,
		"EXIT_CODE_EXECUTION_DIMENSION":       5,
	}
)

func (x ExecutionDimensionType) Enum() *ExecutionDimensionType {
	p := new(ExecutionDimensionType)
	*p = x
	return p
}

func (x ExecutionDimensionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionDimensionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[3].Descriptor()
}

func (ExecutionDimensionType) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[3]
}

func (x ExecutionDimensionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionDimensionType.Descriptor instead.
func (ExecutionDimensionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{3}
}

type FilterCategory int32

const (
	FilterCategory_UNKNOWN_FILTER_CATEGORY      FilterCategory = 0
	FilterCategory_STRING_FILTER_CATEGORY       FilterCategory = 1
	FilterCategory_INT_FILTER_CATEGORY          FilterCategory = 2
	FilterCategory_STATUS_FILTER_CATEGORY       FilterCategory = 3
	FilterCategory_STRING_ARRAY_FILTER_CATEGORY FilterCategory = 4
)

// Enum value maps for FilterCategory.
var (
	FilterCategory_name = map[int32]string{
		0: "UNKNOWN_FILTER_CATEGORY",
		1: "STRING_FILTER_CATEGORY",
		2: "INT_FILTER_CATEGORY",
		3: "STATUS_FILTER_CATEGORY",
		4: "STRING_ARRAY_FILTER_CATEGORY",
	}
	FilterCategory_value = map[string]int32{
		"UNKNOWN_FILTER_CATEGORY":      0,
		"STRING_FILTER_CATEGORY":       1,
		"INT_FILTER_CATEGORY":          2,
		"STATUS_FILTER_CATEGORY":       3,
		"STRING_ARRAY_FILTER_CATEGORY": 4,
	}
)

func (x FilterCategory) Enum() *FilterCategory {
	p := new(FilterCategory)
	*p = x
	return p
}

func (x FilterCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[4].Descriptor()
}

func (FilterCategory) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[4]
}

func (x FilterCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterCategory.Descriptor instead.
func (FilterCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{4}
}

type FilterArgumentCount int32

const (
	FilterArgumentCount_UNKNOWN_FILTER_ARGUMENT_COUNT FilterArgumentCount = 0
	FilterArgumentCount_ONE_FILTER_ARGUMENT_COUNT     FilterArgumentCount = 1
	FilterArgumentCount_MANY_FILTER_ARGUMENT_COUNT    FilterArgumentCount = 2
)

// Enum value maps for FilterArgumentCount.
var (
	FilterArgumentCount_name = map[int32]string{
		0: "UNKNOWN_FILTER_ARGUMENT_COUNT",
		1: "ONE_FILTER_ARGUMENT_COUNT",
		2: "MANY_FILTER_ARGUMENT_COUNT",
	}
	FilterArgumentCount_value = map[string]int32{
		"UNKNOWN_FILTER_ARGUMENT_COUNT": 0,
		"ONE_FILTER_ARGUMENT_COUNT":     1,
		"MANY_FILTER_ARGUMENT_COUNT":    2,
	}
)

func (x FilterArgumentCount) Enum() *FilterArgumentCount {
	p := new(FilterArgumentCount)
	*p = x
	return p
}

func (x FilterArgumentCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterArgumentCount) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[5].Descriptor()
}

func (FilterArgumentCount) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[5]
}

func (x FilterArgumentCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterArgumentCount.Descriptor instead.
func (FilterArgumentCount) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{5}
}

type ObjectTypes int32

const (
	ObjectTypes_UNKNOWN_OBJECTS       ObjectTypes = 0
	ObjectTypes_INVOCATION_OBJECTS    ObjectTypes = 1
	ObjectTypes_EXECUTION_OBJECTS     ObjectTypes = 2
	ObjectTypes_TARGET_STATUS_OBJECTS ObjectTypes = 3
)

// Enum value maps for ObjectTypes.
var (
	ObjectTypes_name = map[int32]string{
		0: "UNKNOWN_OBJECTS",
		1: "INVOCATION_OBJECTS",
		2: "EXECUTION_OBJECTS",
		3: "TARGET_STATUS_OBJECTS",
	}
	ObjectTypes_value = map[string]int32{
		"UNKNOWN_OBJECTS":       0,
		"INVOCATION_OBJECTS":    1,
		"EXECUTION_OBJECTS":     2,
		"TARGET_STATUS_OBJECTS": 3,
	}
)

func (x ObjectTypes) Enum() *ObjectTypes {
	p := new(ObjectTypes)
	*p = x
	return p
}

func (x ObjectTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[6].Descriptor()
}

func (ObjectTypes) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[6]
}

func (x ObjectTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectTypes.Descriptor instead.
func (ObjectTypes) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{6}
}

type FilterType int32

const (
	FilterType_UNKNOWN_FILTER_TYPE                             FilterType = 0
	FilterType_TEXT_MATCH_FILTER_TYPE                          FilterType = 1
	FilterType_REPO_URL_FILTER_TYPE                            FilterType = 2
	FilterType_USER_FILTER_TYPE                                FilterType = 3
	FilterType_INVOCATION_DURATION_USEC_FILTER_TYPE            FilterType = 4
	FilterType_PATTERN_FILTER_TYPE                             FilterType = 5
	FilterType_COMMAND_FILTER_TYPE                             FilterType = 6
	FilterType_HOST_FILTER_TYPE                                FilterType = 7
	FilterType_COMMIT_SHA_FILTER_TYPE                          FilterType = 8
	FilterType_BRANCH_FILTER_TYPE                              FilterType = 9
	FilterType_WORKER_FILTER_TYPE                              FilterType = 10
	FilterType_INVOCATION_CREATED_AT_USEC_FILTER_TYPE          FilterType = 11
	FilterType_EXECUTION_CREATED_AT_USEC_FILTER_TYPE           FilterType = 12
	FilterType_ROLE_FILTER_TYPE                                FilterType = 13
	FilterType_INVOCATION_UPDATED_AT_USEC_FILTER_TYPE          FilterType = 14
	FilterType_EXECUTION_UPDATED_AT_USEC_FILTER_TYPE           FilterType = 15
	FilterType_INVOCATION_STATUS_FILTER_TYPE                   FilterType = 16
	FilterType_TAG_FILTER_TYPE                                 FilterType = 17
	FilterType_INVOCATION_CAS_CACHE_MISSES_FILTER_TYPE         FilterType = 18
	FilterType_INVOCATION_ACTION_CACHE_MISSES_FILTER_TYPE      FilterType = 19
	FilterType_INVOCATION_CAS_CACHE_DOWNLOAD_BYTES_FILTER_TYPE FilterType = 20
	FilterType_INVOCATION_CAS_CACHE_DOWNLOAD_BPS_FILTER_TYPE   FilterType = 21
	FilterType_INVOCATION_CAS_CACHE_UPLOAD_BYTES_FILTER_TYPE   FilterType = 22
	FilterType_INVOCATION_CAS_CACHE_UPLOAD_BPS_FILTER_TYPE     FilterType = 23
	FilterType_INVOCATION_TIME_SAVED_USEC_FILTER_TYPE          FilterType = 24
	FilterType_EXECUTION_QUEUE_TIME_USEC_FILTER_TYPE           FilterType = 25
	FilterType_EXECUTION_INPUT_DOWNLOAD_TIME_USEC_FILTER_TYPE  FilterType = 26
	FilterType_EXECUTION_REAL_TIME_USEC_FILTER_TYPE            FilterType = 27
	FilterType_OUTPUT_UPLOAD_TIME_USEC_FILTER_TYPE             FilterType = 28
	FilterType_PEAK_MEMORY_BYTES_FILTER_TYPE                   FilterType = 29
	FilterType_INPUT_DOWNLOAD_SIZE_BYTES_FILTER_TYPE           FilterType = 30
	FilterType_OUTPUT_UPLOAD_SIZE_BYTES_FILTER_TYPE            FilterType = 31
	FilterType_EXECUTION_WALL_TIME_USEC_FILTER_TYPE            FilterType = 32
	FilterType_EXECUTION_CPU_NANOS_FILTER_TYPE                 FilterType = 33
	FilterType_EXECUTION_AVERAGE_MILLICORES_FILTER_TYPE        FilterType = 34
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0:  "UNKNOWN_FILTER_TYPE",
		1:  "TEXT_MATCH_FILTER_TYPE",
		2:  "REPO_URL_FILTER_TYPE",
		3:  "USER_FILTER_TYPE",
		4:  "INVOCATION_DURATION_USEC_FILTER_TYPE",
		5:  "PATTERN_FILTER_TYPE",
		6:  "COMMAND_FILTER_TYPE",
		7:  "HOST_FILTER_TYPE",
		8:  "COMMIT_SHA_FILTER_TYPE",
		9:  "BRANCH_FILTER_TYPE",
		10: "WORKER_FILTER_TYPE",
		11: "INVOCATION_CREATED_AT_USEC_FILTER_TYPE",
		12: "EXECUTION_CREATED_AT_USEC_FILTER_TYPE",
		13: "ROLE_FILTER_TYPE",
		14: "INVOCATION_UPDATED_AT_USEC_FILTER_TYPE",
		15: "EXECUTION_UPDATED_AT_USEC_FILTER_TYPE",
		16: "INVOCATION_STATUS_FILTER_TYPE",
		17: "TAG_FILTER_TYPE",
		18: "INVOCATION_CAS_CACHE_MISSES_FILTER_TYPE",
		19: "INVOCATION_ACTION_CACHE_MISSES_FILTER_TYPE",
		20: "INVOCATION_CAS_CACHE_DOWNLOAD_BYTES_FILTER_TYPE",
		21: "INVOCATION_CAS_CACHE_DOWNLOAD_BPS_FILTER_TYPE",
		22: "INVOCATION_CAS_CACHE_UPLOAD_BYTES_FILTER_TYPE",
		23: "INVOCATION_CAS_CACHE_UPLOAD_BPS_FILTER_TYPE",
		24: "INVOCATION_TIME_SAVED_USEC_FILTER_TYPE",
		25: "EXECUTION_QUEUE_TIME_USEC_FILTER_TYPE",
		26: "EXECUTION_INPUT_DOWNLOAD_TIME_USEC_FILTER_TYPE",
		27: "EXECUTION_REAL_TIME_USEC_FILTER_TYPE",
		28: "OUTPUT_UPLOAD_TIME_USEC_FILTER_TYPE",
		29: "PEAK_MEMORY_BYTES_FILTER_TYPE",
		30: "INPUT_DOWNLOAD_SIZE_BYTES_FILTER_TYPE",
		31: "OUTPUT_UPLOAD_SIZE_BYTES_FILTER_TYPE",
		32: "EXECUTION_WALL_TIME_USEC_FILTER_TYPE",
		33: "EXECUTION_CPU_NANOS_FILTER_TYPE",
		34: "EXECUTION_AVERAGE_MILLICORES_FILTER_TYPE",
	}
	FilterType_value = map[string]int32{
		"UNKNOWN_FILTER_TYPE":                             0,
		"TEXT_MATCH_FILTER_TYPE":                          1,
		"REPO_URL_FILTER_TYPE":                            2,
		"USER_FILTER_TYPE":                                3,
		"INVOCATION_DURATION_USEC_FILTER_TYPE":            4,
		"PATTERN_FILTER_TYPE":                             5,
		"COMMAND_FILTER_TYPE":                             6,
		"HOST_FILTER_TYPE":                                7,
		"COMMIT_SHA_FILTER_TYPE":                          8,
		"BRANCH_FILTER_TYPE":                              9,
		"WORKER_FILTER_TYPE":                              10,
		"INVOCATION_CREATED_AT_USEC_FILTER_TYPE":          11,
		"EXECUTION_CREATED_AT_USEC_FILTER_TYPE":           12,
		"ROLE_FILTER_TYPE":                                13,
		"INVOCATION_UPDATED_AT_USEC_FILTER_TYPE":          14,
		"EXECUTION_UPDATED_AT_USEC_FILTER_TYPE":           15,
		"INVOCATION_STATUS_FILTER_TYPE":                   16,
		"TAG_FILTER_TYPE":                                 17,
		"INVOCATION_CAS_CACHE_MISSES_FILTER_TYPE":         18,
		"INVOCATION_ACTION_CACHE_MISSES_FILTER_TYPE":      19,
		"INVOCATION_CAS_CACHE_DOWNLOAD_BYTES_FILTER_TYPE": 20,
		"INVOCATION_CAS_CACHE_DOWNLOAD_BPS_FILTER_TYPE":   21,
		"INVOCATION_CAS_CACHE_UPLOAD_BYTES_FILTER_TYPE":   22,
		"INVOCATION_CAS_CACHE_UPLOAD_BPS_FILTER_TYPE":     23,
		"INVOCATION_TIME_SAVED_USEC_FILTER_TYPE":          24,
		"EXECUTION_QUEUE_TIME_USEC_FILTER_TYPE":           25,
		"EXECUTION_INPUT_DOWNLOAD_TIME_USEC_FILTER_TYPE":  26,
		"EXECUTION_REAL_TIME_USEC_FILTER_TYPE":            27,
		"OUTPUT_UPLOAD_TIME_USEC_FILTER_TYPE":             28,
		"PEAK_MEMORY_BYTES_FILTER_TYPE":                   29,
		"INPUT_DOWNLOAD_SIZE_BYTES_FILTER_TYPE":           30,
		"OUTPUT_UPLOAD_SIZE_BYTES_FILTER_TYPE":            31,
		"EXECUTION_WALL_TIME_USEC_FILTER_TYPE":            32,
		"EXECUTION_CPU_NANOS_FILTER_TYPE":                 33,
		"EXECUTION_AVERAGE_MILLICORES_FILTER_TYPE":        34,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[7].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[7]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{7}
}

type FilterOperand int32

const (
	FilterOperand_UNKNOWN_FILTER_OPERAND  FilterOperand = 0
	FilterOperand_GREATER_THAN_OPERAND    FilterOperand = 1
	FilterOperand_LESS_THAN_OPERAND       FilterOperand = 2
	FilterOperand_IN_OPERAND              FilterOperand = 3
	FilterOperand_TEXT_MATCH_OPERAND      FilterOperand = 4
	FilterOperand_ARRAY_CONTAINS_OPERAND  FilterOperand = 5
	FilterOperand_STRING_CONTAINS_OPERAND FilterOperand = 6
)

// Enum value maps for FilterOperand.
var (
	FilterOperand_name = map[int32]string{
		0: "UNKNOWN_FILTER_OPERAND",
		1: "GREATER_THAN_OPERAND",
		2: "LESS_THAN_OPERAND",
		3: "IN_OPERAND",
		4: "TEXT_MATCH_OPERAND",
		5: "ARRAY_CONTAINS_OPERAND",
		6: "STRING_CONTAINS_OPERAND",
	}
	FilterOperand_value = map[string]int32{
		"UNKNOWN_FILTER_OPERAND":  0,
		"GREATER_THAN_OPERAND":    1,
		"LESS_THAN_OPERAND":       2,
		"IN_OPERAND":              3,
		"TEXT_MATCH_OPERAND":      4,
		"ARRAY_CONTAINS_OPERAND":  5,
		"STRING_CONTAINS_OPERAND": 6,
	}
)

func (x FilterOperand) Enum() *FilterOperand {
	p := new(FilterOperand)
	*p = x
	return p
}

func (x FilterOperand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stat_filter_proto_enumTypes[8].Descriptor()
}

func (FilterOperand) Type() protoreflect.EnumType {
	return &file_proto_stat_filter_proto_enumTypes[8]
}

func (x FilterOperand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperand.Descriptor instead.
func (FilterOperand) EnumDescriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{8}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invocation    *InvocationMetricType  `protobuf:"varint,1,opt,name=invocation,proto3,enum=stat_filter.InvocationMetricType,oneof" json:"invocation,omitempty"`
	Execution     *ExecutionMetricType   `protobuf:"varint,2,opt,name=execution,proto3,enum=stat_filter.ExecutionMetricType,oneof" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_stat_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetInvocation() InvocationMetricType {
	if x != nil && x.Invocation != nil {
		return *x.Invocation
	}
	return InvocationMetricType_UNKNOWN_INVOCATION_METRIC
}

func (x *Metric) GetExecution() ExecutionMetricType {
	if x != nil && x.Execution != nil {
		return *x.Execution
	}
	return ExecutionMetricType_UNKNOWN_EXECUTION_METRIC
}

type StatFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Min           *int64                 `protobuf:"varint,2,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int64                 `protobuf:"varint,3,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFilter) Reset() {
	*x = StatFilter{}
	mi := &file_proto_stat_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFilter) ProtoMessage() {}

func (x *StatFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFilter.ProtoReflect.Descriptor instead.
func (*StatFilter) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{1}
}

func (x *StatFilter) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *StatFilter) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *StatFilter) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type Dimension struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Invocation    *InvocationDimensionType `protobuf:"varint,1,opt,name=invocation,proto3,enum=stat_filter.InvocationDimensionType,oneof" json:"invocation,omitempty"`
	Execution     *ExecutionDimensionType  `protobuf:"varint,2,opt,name=execution,proto3,enum=stat_filter.ExecutionDimensionType,oneof" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_proto_stat_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Dimension) GetInvocation() InvocationDimensionType {
	if x != nil && x.Invocation != nil {
		return *x.Invocation
	}
	return InvocationDimensionType_UNKNOWN_INVOCATION_DIMENSION
}

func (x *Dimension) GetExecution() ExecutionDimensionType {
	if x != nil && x.Execution != nil {
		return *x.Execution
	}
	return ExecutionDimensionType_UNKNOWN_EXECUTION_DIMENSION
}

type DimensionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     *Dimension             `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionFilter) Reset() {
	*x = DimensionFilter{}
	mi := &file_proto_stat_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionFilter) ProtoMessage() {}

func (x *DimensionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionFilter.ProtoReflect.Descriptor instead.
func (*DimensionFilter) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{3}
}

func (x *DimensionFilter) GetDimension() *Dimension {
	if x != nil {
		return x.Dimension
	}
	return nil
}

func (x *DimensionFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FilterTypeOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Category           FilterCategory         `protobuf:"varint,1,opt,name=category,proto3,enum=stat_filter.FilterCategory" json:"category,omitempty"`
	DatabaseColumnName string                 `protobuf:"bytes,2,opt,name=database_column_name,json=databaseColumnName,proto3" json:"database_column_name,omitempty"`
	SupportedObjects   []ObjectTypes          `protobuf:"varint,3,rep,packed,name=supported_objects,json=supportedObjects,proto3,enum=stat_filter.ObjectTypes" json:"supported_objects,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FilterTypeOptions) Reset() {
	*x = FilterTypeOptions{}
	mi := &file_proto_stat_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTypeOptions) ProtoMessage() {}

func (x *FilterTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTypeOptions.ProtoReflect.Descriptor instead.
func (*FilterTypeOptions) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{4}
}

func (x *FilterTypeOptions) GetCategory() FilterCategory {
	if x != nil {
		return x.Category
	}
	return FilterCategory_UNKNOWN_FILTER_CATEGORY
}

func (x *FilterTypeOptions) GetDatabaseColumnName() string {
	if x != nil {
		return x.DatabaseColumnName
	}
	return ""
}

func (x *FilterTypeOptions) GetSupportedObjects() []ObjectTypes {
	if x != nil {
		return x.SupportedObjects
	}
	return nil
}

type FilterOperandOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportedCategories []FilterCategory       `protobuf:"varint,1,rep,packed,name=supported_categories,json=supportedCategories,proto3,enum=stat_filter.FilterCategory" json:"supported_categories,omitempty"`
	DatabaseQueryString string                 `protobuf:"bytes,2,opt,name=database_query_string,json=databaseQueryString,proto3" json:"database_query_string,omitempty"`
	ArgumentCount       FilterArgumentCount    `protobuf:"varint,3,opt,name=argument_count,json=argumentCount,proto3,enum=stat_filter.FilterArgumentCount" json:"argument_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FilterOperandOptions) Reset() {
	*x = FilterOperandOptions{}
	mi := &file_proto_stat_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOperandOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOperandOptions) ProtoMessage() {}

func (x *FilterOperandOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOperandOptions.ProtoReflect.Descriptor instead.
func (*FilterOperandOptions) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{5}
}

func (x *FilterOperandOptions) GetSupportedCategories() []FilterCategory {
	if x != nil {
		return x.SupportedCategories
	}
	return nil
}

func (x *FilterOperandOptions) GetDatabaseQueryString() string {
	if x != nil {
		return x.DatabaseQueryString
	}
	return ""
}

func (x *FilterOperandOptions) GetArgumentCount() FilterArgumentCount {
	if x != nil {
		return x.ArgumentCount
	}
	return FilterArgumentCount_UNKNOWN_FILTER_ARGUMENT_COUNT
}

type FilterValue struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	StringValue   []string                          `protobuf:"bytes,1,rep,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	IntValue      []int64                           `protobuf:"varint,2,rep,packed,name=int_value,json=intValue,proto3" json:"int_value,omitempty"`
	StatusValue   []invocation_status.OverallStatus `protobuf:"varint,3,rep,packed,name=status_value,json=statusValue,proto3,enum=invocation_status.OverallStatus" json:"status_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterValue) Reset() {
	*x = FilterValue{}
	mi := &file_proto_stat_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterValue) ProtoMessage() {}

func (x *FilterValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterValue.ProtoReflect.Descriptor instead.
func (*FilterValue) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{6}
}

func (x *FilterValue) GetStringValue() []string {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *FilterValue) GetIntValue() []int64 {
	if x != nil {
		return x.IntValue
	}
	return nil
}

func (x *FilterValue) GetStatusValue() []invocation_status.OverallStatus {
	if x != nil {
		return x.StatusValue
	}
	return nil
}

type GenericFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FilterType             `protobuf:"varint,1,opt,name=type,proto3,enum=stat_filter.FilterType" json:"type,omitempty"`
	Operand       FilterOperand          `protobuf:"varint,2,opt,name=operand,proto3,enum=stat_filter.FilterOperand" json:"operand,omitempty"`
	Value         *FilterValue           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Negate        bool                   `protobuf:"varint,4,opt,name=negate,proto3" json:"negate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericFilter) Reset() {
	*x = GenericFilter{}
	mi := &file_proto_stat_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericFilter) ProtoMessage() {}

func (x *GenericFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericFilter.ProtoReflect.Descriptor instead.
func (*GenericFilter) Descriptor() ([]byte, []int) {
	return file_proto_stat_filter_proto_rawDescGZIP(), []int{7}
}

func (x *GenericFilter) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_UNKNOWN_FILTER_TYPE
}

func (x *GenericFilter) GetOperand() FilterOperand {
	if x != nil {
		return x.Operand
	}
	return FilterOperand_UNKNOWN_FILTER_OPERAND
}

func (x *GenericFilter) GetValue() *FilterValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GenericFilter) GetNegate() bool {
	if x != nil {
		return x.Negate
	}
	return false
}

var file_proto_stat_filter_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*FilterTypeOptions)(nil),
		Field:         7000,
		Name:          "stat_filter.filter_type_options",
		Tag:           "bytes,7000,opt,name=filter_type_options",
		Filename:      "proto/stat_filter.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*FilterOperandOptions)(nil),
		Field:         7001,
		Name:          "stat_filter.filter_operand_options",
		Tag:           "bytes,7001,opt,name=filter_operand_options",
		Filename:      "proto/stat_filter.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional stat_filter.FilterTypeOptions filter_type_options = 7000;
	E_FilterTypeOptions = &file_proto_stat_filter_proto_extTypes[0]
	// optional stat_filter.FilterOperandOptions filter_operand_options = 7001;
	E_FilterOperandOptions = &file_proto_stat_filter_proto_extTypes[1]
)

var File_proto_stat_filter_proto protoreflect.FileDescriptor

const file_proto_stat_filter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/stat_filter.proto\x12\vstat_filter\x1a google/protobuf/descriptor.proto\x1a\x1dproto/invocation_status.proto\"\xb2\x01\n" +
	"\x06Metric\x12F\n" +
	"\n" +
	"invocation\x18\x01 \x01(\x0e2!.stat_filter.InvocationMetricTypeH\x00R\n" +
	"invocation\x88\x01\x01\x12C\n" +
	"\texecution\x18\x02 \x01(\x0e2 .stat_filter.ExecutionMetricTypeH\x01R\texecution\x88\x01\x01B\r\n" +
	"\v_invocationB\f\n" +
	"\n" +
	"_execution\"w\n" +
	"\n" +
	"StatFilter\x12+\n" +
	"\x06metric\x18\x01 \x01(\v2\x13.stat_filter.MetricR\x06metric\x12\x15\n" +
	"\x03min\x18\x02 \x01(\x03H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x03 \x01(\x03H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"\xbb\x01\n" +
	"\tDimension\x12I\n" +
	"\n" +
	"invocation\x18\x01 \x01(\x0e2$.stat_filter.InvocationDimensionTypeH\x00R\n" +
	"invocation\x88\x01\x01\x12F\n" +
	"\texecution\x18\x02 \x01(\x0e2#.stat_filter.ExecutionDimensionTypeH\x01R\texecution\x88\x01\x01B\r\n" +
	"\v_invocationB\f\n" +
	"\n" +
	"_execution\"]\n" +
	"\x0fDimensionFilter\x124\n" +
	"\tdimension\x18\x01 \x01(\v2\x16.stat_filter.DimensionR\tdimension\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc5\x01\n" +
	"\x11FilterTypeOptions\x127\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1b.stat_filter.FilterCategoryR\bcategory\x120\n" +
	"\x14database_column_name\x18\x02 \x01(\tR\x12databaseColumnName\x12E\n" +
	"\x11supported_objects\x18\x03 \x03(\x0e2\x18.stat_filter.ObjectTypesR\x10supportedObjects\"\xe3\x01\n" +
	"\x14FilterOperandOptions\x12N\n" +
	"\x14supported_categories\x18\x01 \x03(\x0e2\x1b.stat_filter.FilterCategoryR\x13supportedCategories\x122\n" +
	"\x15database_query_string\x18\x02 \x01(\tR\x13databaseQueryString\x12G\n" +
	"\x0eargument_count\x18\x03 \x01(\x0e2 .stat_filter.FilterArgumentCountR\rargumentCount\"\x92\x01\n" +
	"\vFilterValue\x12!\n" +
	"\fstring_value\x18\x01 \x03(\tR\vstringValue\x12\x1b\n" +
	"\tint_value\x18\x02 \x03(\x03R\bintValue\x12C\n" +
	"\fstatus_value\x18\x03 \x03(\x0e2 .invocation_status.OverallStatusR\vstatusValue\"\xba\x01\n" +
	"\rGenericFilter\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.stat_filter.FilterTypeR\x04type\x124\n" +
	"\aoperand\x18\x02 \x01(\x0e2\x1a.stat_filter.FilterOperandR\aoperand\x12.\n" +
	"\x05value\x18\x03 \x01(\v2\x18.stat_filter.FilterValueR\x05value\x12\x16\n" +
	"\x06negate\x18\x04 \x01(\bR\x06negate*\xb5\x03\n" +
	"\x14InvocationMetricType\x12\x1d\n" +
	"\x19UNKNOWN_INVOCATION_METRIC\x10\x00\x12#\n" +
	"\x1fDURATION_USEC_INVOCATION_METRIC\x10\x01\x12&\n" +
	"\"CAS_CACHE_MISSES_INVOCATION_METRIC\x10\x02\x12%\n" +
	"!UPDATED_AT_USEC_INVOCATION_METRIC\x10\x03\x12-\n" +
	")CAS_CACHE_DOWNLOAD_SIZE_INVOCATION_METRIC\x10\x04\x12.\n" +
	"*CAS_CACHE_DOWNLOAD_SPEED_INVOCATION_METRIC\x10\x05\x12+\n" +
	"'CAS_CACHE_UPLOAD_SIZE_INVOCATION_METRIC\x10\x06\x12,\n" +
	"(CAS_CACHE_UPLOAD_SPEED_INVOCATION_METRIC\x10\a\x12)\n" +
	"%ACTION_CACHE_MISSES_INVOCATION_METRIC\x10\b\x12%\n" +
	"!TIME_SAVED_USEC_INVOCATION_METRIC\x10\t*\xf8\x03\n" +
	"\x13ExecutionMetricType\x12\x1c\n" +
	"\x18UNKNOWN_EXECUTION_METRIC\x10\x00\x12$\n" +
	" QUEUE_TIME_USEC_EXECUTION_METRIC\x10\x01\x12$\n" +
	" UPDATED_AT_USEC_EXECUTION_METRIC\x10\x02\x12(\n" +
	"$INPUT_DOWNLOAD_TIME_EXECUTION_METRIC\x10\x03\x12(\n" +
	"$REAL_EXECUTION_TIME_EXECUTION_METRIC\x10\x04\x12'\n" +
	"#OUTPUT_UPLOAD_TIME_EXECUTION_METRIC\x10\x05\x12 \n" +
	"\x1cPEAK_MEMORY_EXECUTION_METRIC\x10\x06\x12(\n" +
	"$INPUT_DOWNLOAD_SIZE_EXECUTION_METRIC\x10\a\x12'\n" +
	"#OUTPUT_UPLOAD_SIZE_EXECUTION_METRIC\x10\b\x12(\n" +
	"$EXECUTION_WALL_TIME_EXECUTION_METRIC\x10\t\x12(\n" +
	"$EXECUTION_CPU_NANOS_EXECUTION_METRIC\x10\n" +
	"\x121\n" +
	"-EXECUTION_AVERAGE_MILLICORES_EXECUTION_METRIC\x10\v*\\\n" +
	"\x17InvocationDimensionType\x12 \n" +
	"\x1cUNKNOWN_INVOCATION_DIMENSION\x10\x00\x12\x1f\n" +
	"\x1bBRANCH_INVOCATION_DIMENSION\x10\x01*\xf3\x01\n" +
	"\x16ExecutionDimensionType\x12\x1f\n" +
	"\x1bUNKNOWN_EXECUTION_DIMENSION\x10\x00\x12\x1e\n" +
	"\x1aWORKER_EXECUTION_DIMENSION\x10\x01\x12$\n" +
	" TARGET_LABEL_EXECUTION_DIMENSION\x10\x02\x12'\n" +
	"#ACTION_MNEMONIC_EXECUTION_DIMENSION\x10\x03\x12&\n" +
	"\"EFFECTIVE_POOL_EXECUTION_DIMENSION\x10\x04\x12!\n" +
	"\x1dEXIT_CODE_EXECUTION_DIMENSION\x10\x05*\xa0\x01\n" +
	"\x0eFilterCategory\x12\x1b\n" +
	"\x17UNKNOWN_FILTER_CATEGORY\x10\x00\x12\x1a\n" +
	"\x16STRING_FILTER_CATEGORY\x10\x01\x12\x17\n" +
	"\x13INT_FILTER_CATEGORY\x10\x02\x12\x1a\n" +
	"\x16STATUS_FILTER_CATEGORY\x10\x03\x12 \n" +
	"\x1cSTRING_ARRAY_FILTER_CATEGORY\x10\x04*w\n" +
	"\x13FilterArgumentCount\x12!\n" +
	"\x1dUNKNOWN_FILTER_ARGUMENT_COUNT\x10\x00\x12\x1d\n" +
	"\x19ONE_FILTER_ARGUMENT_COUNT\x10\x01\x12\x1e\n" +
	"\x1aMANY_FILTER_ARGUMENT_COUNT\x10\x02*l\n" +
	"\vObjectTypes\x12\x13\n" +
	"\x0fUNKNOWN_OBJECTS\x10\x00\x12\x16\n" +
	"\x12INVOCATION_OBJECTS\x10\x01\x12\x15\n" +
	"\x11EXECUTION_OBJECTS\x10\x02\x12\x19\n" +
	"\x15TARGET_STATUS_OBJECTS\x10\x03*\x96\x16\n" +
	"\n" +
	"FilterType\x12\x1d\n" +
	"\x13UNKNOWN_FILTER_TYPE\x10\x00\x1a\x04µ\x03\x00\x12&\n" +
	"\x16TEXT_MATCH_FILTER_TYPE\x10\x01\x1a\n" +
	"µ\x03\x06\b\x01\x1a\x02\x01\x02\x12.\n" +
	"\x14REPO_URL_FILTER_TYPE\x10\x02\x1a\x14µ\x03\x10\b\x01\x12\brepo_url\x1a\x02\x01\x02\x12(\n" +
	"\x10USER_FILTER_TYPE\x10\x03\x1a\x12µ\x03\x0e\b\x01\x12\x06\"user\"\x1a\x02\x01\x02\x12B\n" +
	"$INVOCATION_DURATION_USEC_FILTER_TYPE\x10\x04\x1a\x18µ\x03\x14\b\x02\x12\rduration_usec\x1a\x01\x01\x12,\n" +
	"\x13PATTERN_FILTER_TYPE\x10\x05\x1a\x13µ\x03\x0f\b\x01\x12\apattern\x1a\x02\x01\x02\x12,\n" +
	"\x13COMMAND_FILTER_TYPE\x10\x06\x1a\x13µ\x03\x0f\b\x01\x12\acommand\x1a\x02\x01\x02\x12&\n" +
	"\x10HOST_FILTER_TYPE\x10\a\x1a\x10µ\x03\f\b\x01\x12\x04host\x1a\x02\x01\x02\x122\n" +
	"\x16COMMIT_SHA_FILTER_TYPE\x10\b\x1a\x16µ\x03\x12\b\x01\x12\n" +
	"commit_sha\x1a\x02\x01\x02\x12/\n" +
	"\x12BRANCH_FILTER_TYPE\x10\t\x1a\x17µ\x03\x13\b\x01\x12\vbranch_name\x1a\x02\x01\x02\x12)\n" +
	"\x12WORKER_FILTER_TYPE\x10\n" +
	"\x1a\x11µ\x03\r\b\x01\x12\x06worker\x1a\x01\x02\x12F\n" +
	"&INVOCATION_CREATED_AT_USEC_FILTER_TYPE\x10\v\x1a\x1aµ\x03\x16\b\x02\x12\x0fcreated_at_usec\x1a\x01\x01\x12E\n" +
	"%EXECUTION_CREATED_AT_USEC_FILTER_TYPE\x10\f\x1a\x1aµ\x03\x16\b\x02\x12\x0fcreated_at_usec\x1a\x01\x02\x12&\n" +
	"\x10ROLE_FILTER_TYPE\x10\r\x1a\x10µ\x03\f\b\x01\x12\x04role\x1a\x02\x01\x02\x12F\n" +
	"&INVOCATION_UPDATED_AT_USEC_FILTER_TYPE\x10\x0e\x1a\x1aµ\x03\x16\b\x02\x12\x0fupdated_at_usec\x1a\x01\x01\x12E\n" +
	"%EXECUTION_UPDATED_AT_USEC_FILTER_TYPE\x10\x0f\x1a\x1aµ\x03\x16\b\x02\x12\x0fupdated_at_usec\x1a\x01\x02\x12-\n" +
	"\x1dINVOCATION_STATUS_FILTER_TYPE\x10\x10\x1a\n" +
	"µ\x03\x06\b\x03\x1a\x02\x01\x02\x12%\n" +
	"\x0fTAG_FILTER_TYPE\x10\x11\x1a\x10µ\x03\f\b\x04\x12\x04tags\x1a\x02\x01\x02\x12H\n" +
	"'INVOCATION_CAS_CACHE_MISSES_FILTER_TYPE\x10\x12\x1a\x1bµ\x03\x17\b\x02\x12\x10cas_cache_misses\x1a\x01\x01\x12N\n" +
	"*INVOCATION_ACTION_CACHE_MISSES_FILTER_TYPE\x10\x13\x1a\x1eµ\x03\x1a\b\x02\x12\x13action_cache_misses\x1a\x01\x01\x12Y\n" +
	"/INVOCATION_CAS_CACHE_DOWNLOAD_BYTES_FILTER_TYPE\x10\x14\x1a$µ\x03 \b\x02\x12\x19total_download_size_bytes\x1a\x01\x01\x12b\n" +
	"-INVOCATION_CAS_CACHE_DOWNLOAD_BPS_FILTER_TYPE\x10\x15\x1a/µ\x03+\b\x02\x12$download_throughput_bytes_per_second\x1a\x01\x01\x12U\n" +
	"-INVOCATION_CAS_CACHE_UPLOAD_BYTES_FILTER_TYPE\x10\x16\x1a\"µ\x03\x1e\b\x02\x12\x17total_upload_size_bytes\x1a\x01\x01\x12^\n" +
	"+INVOCATION_CAS_CACHE_UPLOAD_BPS_FILTER_TYPE\x10\x17\x1a-µ\x03)\b\x02\x12\"upload_throughput_bytes_per_second\x1a\x01\x01\x12T\n" +
	"&INVOCATION_TIME_SAVED_USEC_FILTER_TYPE\x10\x18\x1a(µ\x03$\b\x02\x12\x1dtotal_cached_action_exec_usec\x1a\x01\x01\x12\xa7\x01\n" +
	"%EXECUTION_QUEUE_TIME_USEC_FILTER_TYPE\x10\x19\x1a|µ\x03x\b\x02\x12qIF(worker_start_timestamp_usec < queued_timestamp_usec, 0, (worker_start_timestamp_usec - queued_timestamp_usec))\x1a\x01\x02\x12\x88\x01\n" +
	".EXECUTION_INPUT_DOWNLOAD_TIME_USEC_FILTER_TYPE\x10\x1a\x1aTµ\x03P\b\x02\x12I(input_fetch_completed_timestamp_usec - input_fetch_start_timestamp_usec)\x1a\x01\x02\x12z\n" +
	"$EXECUTION_REAL_TIME_USEC_FILTER_TYPE\x10\x1b\x1aPµ\x03L\b\x02\x12E(execution_completed_timestamp_usec - execution_start_timestamp_usec)\x1a\x01\x02\x12\x81\x01\n" +
	"#OUTPUT_UPLOAD_TIME_USEC_FILTER_TYPE\x10\x1c\x1aXµ\x03T\b\x02\x12M(output_upload_completed_timestamp_usec - output_upload_start_timestamp_usec)\x1a\x01\x02\x12?\n" +
	"\x1dPEAK_MEMORY_BYTES_FILTER_TYPE\x10\x1d\x1a\x1cµ\x03\x18\b\x02\x12\x11peak_memory_bytes\x1a\x01\x02\x12N\n" +
	"%INPUT_DOWNLOAD_SIZE_BYTES_FILTER_TYPE\x10\x1e\x1a#µ\x03\x1f\b\x02\x12\x18file_download_size_bytes\x1a\x01\x02\x12K\n" +
	"$OUTPUT_UPLOAD_SIZE_BYTES_FILTER_TYPE\x10\x1f\x1a!µ\x03\x1d\b\x02\x12\x16file_upload_size_bytes\x1a\x01\x02\x12\xb0\x01\n" +
	"$EXECUTION_WALL_TIME_USEC_FILTER_TYPE\x10 \x1a\x85\x01µ\x03\x80\x01\b\x02\x12yIF(worker_completed_timestamp_usec < queued_timestamp_usec, 0, (worker_completed_timestamp_usec - queued_timestamp_usec))\x1a\x01\x02\x129\n" +
	"\x1fEXECUTION_CPU_NANOS_FILTER_TYPE\x10!\x1a\x14µ\x03\x10\b\x02\x12\tcpu_nanos\x1a\x01\x02\x12\x8b\x02\n" +
	"(EXECUTION_AVERAGE_MILLICORES_FILTER_TYPE\x10\"\x1a\xdc\x01µ\x03\xd7\x01\b\x02\x12\xcf\x01IF(cpu_nanos <= 0 OR (execution_completed_timestamp_usec - execution_start_timestamp_usec) <= 0, 0, intDivOrZero(cpu_nanos*1000, (execution_completed_timestamp_usec - execution_start_timestamp_usec) * 1000))\x1a\x01\x02*\xcb\x03\n" +
	"\rFilterOperand\x12 \n" +
	"\x16UNKNOWN_FILTER_OPERAND\x10\x00\x1a\x04ʵ\x03\x00\x124\n" +
	"\x14GREATER_THAN_OPERAND\x10\x01\x1a\x1aʵ\x03\x16\n" +
	"\x01\x02\x12\x0f?field > ?value\x18\x01\x121\n" +
	"\x11LESS_THAN_OPERAND\x10\x02\x1a\x1aʵ\x03\x16\n" +
	"\x01\x02\x12\x0f?field < ?value\x18\x01\x12-\n" +
	"\n" +
	"IN_OPERAND\x10\x03\x1a\x1dʵ\x03\x19\n" +
	"\x03\x02\x01\x03\x12\x10?field IN ?value\x18\x02\x12w\n" +
	"\x12TEXT_MATCH_OPERAND\x10\x04\x1a_ʵ\x03[\n" +
	"\x01\x01\x12TINSTR(pattern, ?value) > 0 OR INSTR(user, ?value) > 0 OR INSTR(repo_url, ?value) > 0\x18\x01\x12D\n" +
	"\x16ARRAY_CONTAINS_OPERAND\x10\x05\x1a(ʵ\x03$\n" +
	"\x01\x04\x12\x1dhasAny(?field, array(?value))\x18\x02\x12A\n" +
	"\x17STRING_CONTAINS_OPERAND\x10\x06\x1a$ʵ\x03 \n" +
	"\x01\x01\x12\x19INSTR(?field, ?value) > 0\x18\x01:r\n" +
	"\x13filter_type_options\x12!.google.protobuf.EnumValueOptions\x18\xd86 \x01(\v2\x1e.stat_filter.FilterTypeOptionsR\x11filterTypeOptions:{\n" +
	"\x16filter_operand_options\x12!.google.protobuf.EnumValueOptions\x18\xd96 \x01(\v2!.stat_filter.FilterOperandOptionsR\x14filterOperandOptionsb\x06proto3"

var (
	file_proto_stat_filter_proto_rawDescOnce sync.Once
	file_proto_stat_filter_proto_rawDescData []byte
)

func file_proto_stat_filter_proto_rawDescGZIP() []byte {
	file_proto_stat_filter_proto_rawDescOnce.Do(func() {
		file_proto_stat_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stat_filter_proto_rawDesc), len(file_proto_stat_filter_proto_rawDesc)))
	})
	return file_proto_stat_filter_proto_rawDescData
}

var file_proto_stat_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_proto_stat_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_stat_filter_proto_goTypes = []any{
	(InvocationMetricType)(0),             // 0: stat_filter.InvocationMetricType
	(ExecutionMetricType)(0),              // 1: stat_filter.ExecutionMetricType
	(InvocationDimensionType)(0),          // 2: stat_filter.InvocationDimensionType
	(ExecutionDimensionType)(0),           // 3: stat_filter.ExecutionDimensionType
	(FilterCategory)(0),                   // 4: stat_filter.FilterCategory
	(FilterArgumentCount)(0),              // 5: stat_filter.FilterArgumentCount
	(ObjectTypes)(0),                      // 6: stat_filter.ObjectTypes
	(FilterType)(0),                       // 7: stat_filter.FilterType
	(FilterOperand)(0),                    // 8: stat_filter.FilterOperand
	(*Metric)(nil),                        // 9: stat_filter.Metric
	(*StatFilter)(nil),                    // 10: stat_filter.StatFilter
	(*Dimension)(nil),                     // 11: stat_filter.Dimension
	(*DimensionFilter)(nil),               // 12: stat_filter.DimensionFilter
	(*FilterTypeOptions)(nil),             // 13: stat_filter.FilterTypeOptions
	(*FilterOperandOptions)(nil),          // 14: stat_filter.FilterOperandOptions
	(*FilterValue)(nil),                   // 15: stat_filter.FilterValue
	(*GenericFilter)(nil),                 // 16: stat_filter.GenericFilter
	(invocation_status.OverallStatus)(0),  // 17: invocation_status.OverallStatus
	(*descriptorpb.EnumValueOptions)(nil), // 18: google.protobuf.EnumValueOptions
}
var file_proto_stat_filter_proto_depIdxs = []int32{
	0,  // 0: stat_filter.Metric.invocation:type_name -> stat_filter.InvocationMetricType
	1,  // 1: stat_filter.Metric.execution:type_name -> stat_filter.ExecutionMetricType
	9,  // 2: stat_filter.StatFilter.metric:type_name -> stat_filter.Metric
	2,  // 3: stat_filter.Dimension.invocation:type_name -> stat_filter.InvocationDimensionType
	3,  // 4: stat_filter.Dimension.execution:type_name -> stat_filter.ExecutionDimensionType
	11, // 5: stat_filter.DimensionFilter.dimension:type_name -> stat_filter.Dimension
	4,  // 6: stat_filter.FilterTypeOptions.category:type_name -> stat_filter.FilterCategory
	6,  // 7: stat_filter.FilterTypeOptions.supported_objects:type_name -> stat_filter.ObjectTypes
	4,  // 8: stat_filter.FilterOperandOptions.supported_categories:type_name -> stat_filter.FilterCategory
	5,  // 9: stat_filter.FilterOperandOptions.argument_count:type_name -> stat_filter.FilterArgumentCount
	17, // 10: stat_filter.FilterValue.status_value:type_name -> invocation_status.OverallStatus
	7,  // 11: stat_filter.GenericFilter.type:type_name -> stat_filter.FilterType
	8,  // 12: stat_filter.GenericFilter.operand:type_name -> stat_filter.FilterOperand
	15, // 13: stat_filter.GenericFilter.value:type_name -> stat_filter.FilterValue
	18, // 14: stat_filter.filter_type_options:extendee -> google.protobuf.EnumValueOptions
	18, // 15: stat_filter.filter_operand_options:extendee -> google.protobuf.EnumValueOptions
	13, // 16: stat_filter.filter_type_options:type_name -> stat_filter.FilterTypeOptions
	14, // 17: stat_filter.filter_operand_options:type_name -> stat_filter.FilterOperandOptions
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	16, // [16:18] is the sub-list for extension type_name
	14, // [14:16] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_stat_filter_proto_init() }
func file_proto_stat_filter_proto_init() {
	if File_proto_stat_filter_proto != nil {
		return
	}
	file_proto_stat_filter_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_stat_filter_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_stat_filter_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stat_filter_proto_rawDesc), len(file_proto_stat_filter_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   8,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_stat_filter_proto_goTypes,
		DependencyIndexes: file_proto_stat_filter_proto_depIdxs,
		EnumInfos:         file_proto_stat_filter_proto_enumTypes,
		MessageInfos:      file_proto_stat_filter_proto_msgTypes,
		ExtensionInfos:    file_proto_stat_filter_proto_extTypes,
	}.Build()
	File_proto_stat_filter_proto = out.File
	file_proto_stat_filter_proto_goTypes = nil
	file_proto_stat_filter_proto_depIdxs = nil
}
