load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "flag_form",
    srcs = ["flag_form.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/parser/options/flag_form",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//cli:__subpackages__"])

