// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/capability.proto

package capability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability int32

const (
	Capability_UNKNOWN_CAPABILITY Capability = 0
	Capability_CACHE_WRITE        Capability = 1
	Capability_REGISTER_EXECUTOR  Capability = 2
	Capability_CAS_WRITE          Capability = 4
	Capability_ORG_ADMIN          Capability = 8
	Capability_AUDIT_LOG_READ     Capability = 16
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "UNKNOWN_CAPABILITY",
		1:  "CACHE_WRITE",
		2:  "REGISTER_EXECUTOR",
		4:  "CAS_WRITE",
		8:  "ORG_ADMIN",
		16: "AUDIT_LOG_READ",
	}
	Capability_value = map[string]int32{
		"UNKNOWN_CAPABILITY": 0,
		"CACHE_WRITE":        1,
		"REGISTER_EXECUTOR":  2,
		"CAS_WRITE":          4,
		"ORG_ADMIN":          8,
		"AUDIT_LOG_READ":     16,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_capability_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_proto_capability_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_proto_capability_proto_rawDescGZIP(), []int{0}
}

var File_proto_capability_proto protoreflect.FileDescriptor

const file_proto_capability_proto_rawDesc = "" +
	"\n" +
	"\x16proto/capability.proto\x12\n" +
	"capability*~\n" +
	"\n" +
	"Capability\x12\x16\n" +
	"\x12UNKNOWN_CAPABILITY\x10\x00\x12\x0f\n" +
	"\vCACHE_WRITE\x10\x01\x12\x15\n" +
	"\x11REGISTER_EXECUTOR\x10\x02\x12\r\n" +
	"\tCAS_WRITE\x10\x04\x12\r\n" +
	"\tORG_ADMIN\x10\b\x12\x12\n" +
	"\x0eAUDIT_LOG_READ\x10\x10b\x06proto3"

var (
	file_proto_capability_proto_rawDescOnce sync.Once
	file_proto_capability_proto_rawDescData []byte
)

func file_proto_capability_proto_rawDescGZIP() []byte {
	file_proto_capability_proto_rawDescOnce.Do(func() {
		file_proto_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_capability_proto_rawDesc), len(file_proto_capability_proto_rawDesc)))
	})
	return file_proto_capability_proto_rawDescData
}

var file_proto_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_capability_proto_goTypes = []any{
	(Capability)(0), // 0: capability.Capability
}
var file_proto_capability_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_capability_proto_init() }
func file_proto_capability_proto_init() {
	if File_proto_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_capability_proto_rawDesc), len(file_proto_capability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_capability_proto_goTypes,
		DependencyIndexes: file_proto_capability_proto_depIdxs,
		EnumInfos:         file_proto_capability_proto_enumTypes,
	}.Build()
	File_proto_capability_proto = out.File
	file_proto_capability_proto_goTypes = nil
	file_proto_capability_proto_depIdxs = nil
}
