// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/user_id.proto

package user_id

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_UNKNOWN_USER_TYPE AccountType = 0
	AccountType_GOOGLE            AccountType = 1
	AccountType_GITHUB            AccountType = 2
	AccountType_SAML              AccountType = 3
	AccountType_OIDC              AccountType = 4
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "UNKNOWN_USER_TYPE",
		1: "GOOGLE",
		2: "GITHUB",
		3: "SAML",
		4: "OIDC",
	}
	AccountType_value = map[string]int32{
		"UNKNOWN_USER_TYPE": 0,
		"GOOGLE":            1,
		"GITHUB":            2,
		"SAML":              3,
		"OIDC":              4,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_id_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_user_id_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_id_proto_rawDescGZIP(), []int{0}
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_proto_user_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_proto_user_id_proto_rawDescGZIP(), []int{0}
}

func (x *UserId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Full          string                 `protobuf:"bytes,1,opt,name=full,proto3" json:"full,omitempty"`
	First         string                 `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Last          string                 `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_proto_user_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_proto_user_id_proto_rawDescGZIP(), []int{1}
}

func (x *Name) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *Name) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *Name) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

type DisplayUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          *UserId                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            *Name                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,3,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AccountType     AccountType            `protobuf:"varint,5,opt,name=account_type,json=accountType,proto3,enum=user_id.AccountType" json:"account_type,omitempty"`
	Username        string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisplayUser) Reset() {
	*x = DisplayUser{}
	mi := &file_proto_user_id_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayUser) ProtoMessage() {}

func (x *DisplayUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_id_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayUser.ProtoReflect.Descriptor instead.
func (*DisplayUser) Descriptor() ([]byte, []int) {
	return file_proto_user_id_proto_rawDescGZIP(), []int{2}
}

func (x *DisplayUser) GetUserId() *UserId {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *DisplayUser) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DisplayUser) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *DisplayUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DisplayUser) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_UNKNOWN_USER_TYPE
}

func (x *DisplayUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_proto_user_id_proto protoreflect.FileDescriptor

const file_proto_user_id_proto_rawDesc = "" +
	"\n" +
	"\x13proto/user_id.proto\x12\auser_id\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x04Name\x12\x12\n" +
	"\x04full\x18\x01 \x01(\tR\x04full\x12\x14\n" +
	"\x05first\x18\x02 \x01(\tR\x05first\x12\x12\n" +
	"\x04last\x18\x03 \x01(\tR\x04last\"\xf1\x01\n" +
	"\vDisplayUser\x12(\n" +
	"\auser_id\x18\x01 \x01(\v2\x0f.user_id.UserIdR\x06userId\x12!\n" +
	"\x04name\x18\x02 \x01(\v2\r.user_id.NameR\x04name\x12*\n" +
	"\x11profile_image_url\x18\x03 \x01(\tR\x0fprofileImageUrl\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x127\n" +
	"\faccount_type\x18\x05 \x01(\x0e2\x14.user_id.AccountTypeR\vaccountType\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername*P\n" +
	"\vAccountType\x12\x15\n" +
	"\x11UNKNOWN_USER_TYPE\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x02\x12\b\n" +
	"\x04SAML\x10\x03\x12\b\n" +
	"\x04OIDC\x10\x04b\x06proto3"

var (
	file_proto_user_id_proto_rawDescOnce sync.Once
	file_proto_user_id_proto_rawDescData []byte
)

func file_proto_user_id_proto_rawDescGZIP() []byte {
	file_proto_user_id_proto_rawDescOnce.Do(func() {
		file_proto_user_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_id_proto_rawDesc), len(file_proto_user_id_proto_rawDesc)))
	})
	return file_proto_user_id_proto_rawDescData
}

var file_proto_user_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_id_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_id_proto_goTypes = []any{
	(AccountType)(0),    // 0: user_id.AccountType
	(*UserId)(nil),      // 1: user_id.UserId
	(*Name)(nil),        // 2: user_id.Name
	(*DisplayUser)(nil), // 3: user_id.DisplayUser
}
var file_proto_user_id_proto_depIdxs = []int32{
	1, // 0: user_id.DisplayUser.user_id:type_name -> user_id.UserId
	2, // 1: user_id.DisplayUser.name:type_name -> user_id.Name
	0, // 2: user_id.DisplayUser.account_type:type_name -> user_id.AccountType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_id_proto_init() }
func file_proto_user_id_proto_init() {
	if File_proto_user_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_id_proto_rawDesc), len(file_proto_user_id_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_id_proto_goTypes,
		DependencyIndexes: file_proto_user_id_proto_depIdxs,
		EnumInfos:         file_proto_user_id_proto_enumTypes,
		MessageInfos:      file_proto_user_id_proto_msgTypes,
	}.Build()
	File_proto_user_id_proto = out.File
	file_proto_user_id_proto_goTypes = nil
	file_proto_user_id_proto_depIdxs = nil
}
