// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/acl.proto

package acl

import (
	user_id "github.com/buildbuddy-io/buildbuddy/proto/user_id"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACL struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            *user_id.UserId        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId           string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OwnerPermissions  *ACL_Permissions       `protobuf:"bytes,3,opt,name=owner_permissions,json=ownerPermissions,proto3" json:"owner_permissions,omitempty"`
	GroupPermissions  *ACL_Permissions       `protobuf:"bytes,4,opt,name=group_permissions,json=groupPermissions,proto3" json:"group_permissions,omitempty"`
	OthersPermissions *ACL_Permissions       `protobuf:"bytes,5,opt,name=others_permissions,json=othersPermissions,proto3" json:"others_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ACL) Reset() {
	*x = ACL{}
	mi := &file_proto_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL) ProtoMessage() {}

func (x *ACL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL.ProtoReflect.Descriptor instead.
func (*ACL) Descriptor() ([]byte, []int) {
	return file_proto_acl_proto_rawDescGZIP(), []int{0}
}

func (x *ACL) GetUserId() *user_id.UserId {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ACL) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ACL) GetOwnerPermissions() *ACL_Permissions {
	if x != nil {
		return x.OwnerPermissions
	}
	return nil
}

func (x *ACL) GetGroupPermissions() *ACL_Permissions {
	if x != nil {
		return x.GroupPermissions
	}
	return nil
}

func (x *ACL) GetOthersPermissions() *ACL_Permissions {
	if x != nil {
		return x.OthersPermissions
	}
	return nil
}

type ACL_Permissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACL_Permissions) Reset() {
	*x = ACL_Permissions{}
	mi := &file_proto_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL_Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL_Permissions) ProtoMessage() {}

func (x *ACL_Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL_Permissions.ProtoReflect.Descriptor instead.
func (*ACL_Permissions) Descriptor() ([]byte, []int) {
	return file_proto_acl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ACL_Permissions) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *ACL_Permissions) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

var File_proto_acl_proto protoreflect.FileDescriptor

const file_proto_acl_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/acl.proto\x12\x03acl\x1a\x13proto/user_id.proto\"\xce\x02\n" +
	"\x03ACL\x12(\n" +
	"\auser_id\x18\x01 \x01(\v2\x0f.user_id.UserIdR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12A\n" +
	"\x11owner_permissions\x18\x03 \x01(\v2\x14.acl.ACL.PermissionsR\x10ownerPermissions\x12A\n" +
	"\x11group_permissions\x18\x04 \x01(\v2\x14.acl.ACL.PermissionsR\x10groupPermissions\x12C\n" +
	"\x12others_permissions\x18\x05 \x01(\v2\x14.acl.ACL.PermissionsR\x11othersPermissions\x1a7\n" +
	"\vPermissions\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05writeb\x06proto3"

var (
	file_proto_acl_proto_rawDescOnce sync.Once
	file_proto_acl_proto_rawDescData []byte
)

func file_proto_acl_proto_rawDescGZIP() []byte {
	file_proto_acl_proto_rawDescOnce.Do(func() {
		file_proto_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_acl_proto_rawDesc), len(file_proto_acl_proto_rawDesc)))
	})
	return file_proto_acl_proto_rawDescData
}

var file_proto_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_acl_proto_goTypes = []any{
	(*ACL)(nil),             // 0: acl.ACL
	(*ACL_Permissions)(nil), // 1: acl.ACL.Permissions
	(*user_id.UserId)(nil),  // 2: user_id.UserId
}
var file_proto_acl_proto_depIdxs = []int32{
	2, // 0: acl.ACL.user_id:type_name -> user_id.UserId
	1, // 1: acl.ACL.owner_permissions:type_name -> acl.ACL.Permissions
	1, // 2: acl.ACL.group_permissions:type_name -> acl.ACL.Permissions
	1, // 3: acl.ACL.others_permissions:type_name -> acl.ACL.Permissions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_acl_proto_init() }
func file_proto_acl_proto_init() {
	if File_proto_acl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_acl_proto_rawDesc), len(file_proto_acl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_acl_proto_goTypes,
		DependencyIndexes: file_proto_acl_proto_depIdxs,
		MessageInfos:      file_proto_acl_proto_msgTypes,
	}.Build()
	File_proto_acl_proto = out.File
	file_proto_acl_proto_goTypes = nil
	file_proto_acl_proto_depIdxs = nil
}
