load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "bytebufferpool",
    srcs = ["bytebufferpool.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/bytebufferpool",
    visibility = ["//visibility:public"],
)

