load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "peerset",
    srcs = ["peerset.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/peerset",
    visibility = ["//visibility:public"],
)

