load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "timeseries",
    srcs = ["timeseries.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/timeseries",
    visibility = ["//visibility:public"],
)

