// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/scheduler.proto

package scheduler

import (
	acl "github.com/buildbuddy-io/buildbuddy/proto/acl"
	context "github.com/buildbuddy-io/buildbuddy/proto/context"
	trace "github.com/buildbuddy-io/buildbuddy/proto/trace"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddress) Reset() {
	*x = NodeAddress{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddress) ProtoMessage() {}

func (x *NodeAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddress.ProtoReflect.Descriptor instead.
func (*NodeAddress) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *NodeAddress) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeAddress) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TaskExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExistsRequest) Reset() {
	*x = TaskExistsRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExistsRequest) ProtoMessage() {}

func (x *TaskExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExistsRequest.ProtoReflect.Descriptor instead.
func (*TaskExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExistsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExistsResponse) Reset() {
	*x = TaskExistsResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExistsResponse) ProtoMessage() {}

func (x *TaskExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExistsResponse.ProtoReflect.Descriptor instead.
func (*TaskExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *TaskExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type LeaseTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Finalize          bool                   `protobuf:"varint,2,opt,name=finalize,proto3" json:"finalize,omitempty"`
	Release           bool                   `protobuf:"varint,3,opt,name=release,proto3" json:"release,omitempty"`
	ExecutorId        string                 `protobuf:"bytes,4,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorHostname  string                 `protobuf:"bytes,9,opt,name=executor_hostname,json=executorHostname,proto3" json:"executor_hostname,omitempty"`
	ReEnqueue         bool                   `protobuf:"varint,5,opt,name=re_enqueue,json=reEnqueue,proto3" json:"re_enqueue,omitempty"`
	ReEnqueueReason   *status.Status         `protobuf:"bytes,6,opt,name=re_enqueue_reason,json=reEnqueueReason,proto3" json:"re_enqueue_reason,omitempty"`
	SupportsReconnect bool                   `protobuf:"varint,7,opt,name=supports_reconnect,json=supportsReconnect,proto3" json:"supports_reconnect,omitempty"`
	ReconnectToken    string                 `protobuf:"bytes,8,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaseTaskRequest) Reset() {
	*x = LeaseTaskRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTaskRequest) ProtoMessage() {}

func (x *LeaseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTaskRequest.ProtoReflect.Descriptor instead.
func (*LeaseTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LeaseTaskRequest) GetFinalize() bool {
	if x != nil {
		return x.Finalize
	}
	return false
}

func (x *LeaseTaskRequest) GetRelease() bool {
	if x != nil {
		return x.Release
	}
	return false
}

func (x *LeaseTaskRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *LeaseTaskRequest) GetExecutorHostname() string {
	if x != nil {
		return x.ExecutorHostname
	}
	return ""
}

func (x *LeaseTaskRequest) GetReEnqueue() bool {
	if x != nil {
		return x.ReEnqueue
	}
	return false
}

func (x *LeaseTaskRequest) GetReEnqueueReason() *status.Status {
	if x != nil {
		return x.ReEnqueueReason
	}
	return nil
}

func (x *LeaseTaskRequest) GetSupportsReconnect() bool {
	if x != nil {
		return x.SupportsReconnect
	}
	return false
}

func (x *LeaseTaskRequest) GetReconnectToken() string {
	if x != nil {
		return x.ReconnectToken
	}
	return ""
}

type LeaseTaskResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SerializedTask       []byte                 `protobuf:"bytes,1,opt,name=serialized_task,json=serializedTask,proto3" json:"serialized_task,omitempty"`
	LeaseDurationSeconds int64                  `protobuf:"varint,2,opt,name=lease_duration_seconds,json=leaseDurationSeconds,proto3" json:"lease_duration_seconds,omitempty"`
	ClosedCleanly        bool                   `protobuf:"varint,3,opt,name=closed_cleanly,json=closedCleanly,proto3" json:"closed_cleanly,omitempty"`
	ReconnectToken       string                 `protobuf:"bytes,4,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	LeaseId              string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	SupportsReconnect    bool                   `protobuf:"varint,6,opt,name=supports_reconnect,json=supportsReconnect,proto3" json:"supports_reconnect,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LeaseTaskResponse) Reset() {
	*x = LeaseTaskResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTaskResponse) ProtoMessage() {}

func (x *LeaseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTaskResponse.ProtoReflect.Descriptor instead.
func (*LeaseTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseTaskResponse) GetSerializedTask() []byte {
	if x != nil {
		return x.SerializedTask
	}
	return nil
}

func (x *LeaseTaskResponse) GetLeaseDurationSeconds() int64 {
	if x != nil {
		return x.LeaseDurationSeconds
	}
	return 0
}

func (x *LeaseTaskResponse) GetClosedCleanly() bool {
	if x != nil {
		return x.ClosedCleanly
	}
	return false
}

func (x *LeaseTaskResponse) GetReconnectToken() string {
	if x != nil {
		return x.ReconnectToken
	}
	return ""
}

func (x *LeaseTaskResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseTaskResponse) GetSupportsReconnect() bool {
	if x != nil {
		return x.SupportsReconnect
	}
	return false
}

type CustomResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResource) Reset() {
	*x = CustomResource{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResource) ProtoMessage() {}

func (x *CustomResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResource.ProtoReflect.Descriptor instead.
func (*CustomResource) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *CustomResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomResource) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TaskSize struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EstimatedMemoryBytes   int64                  `protobuf:"varint,1,opt,name=estimated_memory_bytes,json=estimatedMemoryBytes,proto3" json:"estimated_memory_bytes,omitempty"`
	EstimatedMilliCpu      int64                  `protobuf:"varint,2,opt,name=estimated_milli_cpu,json=estimatedMilliCpu,proto3" json:"estimated_milli_cpu,omitempty"`
	EstimatedFreeDiskBytes int64                  `protobuf:"varint,3,opt,name=estimated_free_disk_bytes,json=estimatedFreeDiskBytes,proto3" json:"estimated_free_disk_bytes,omitempty"`
	DiskReadBps            int64                  `protobuf:"varint,5,opt,name=disk_read_bps,json=diskReadBps,proto3" json:"disk_read_bps,omitempty"`
	DiskWriteBps           int64                  `protobuf:"varint,6,opt,name=disk_write_bps,json=diskWriteBps,proto3" json:"disk_write_bps,omitempty"`
	DiskReadIops           int64                  `protobuf:"varint,7,opt,name=disk_read_iops,json=diskReadIops,proto3" json:"disk_read_iops,omitempty"`
	DiskWriteIops          int64                  `protobuf:"varint,8,opt,name=disk_write_iops,json=diskWriteIops,proto3" json:"disk_write_iops,omitempty"`
	CustomResources        []*CustomResource      `protobuf:"bytes,4,rep,name=custom_resources,json=customResources,proto3" json:"custom_resources,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskSize) Reset() {
	*x = TaskSize{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSize) ProtoMessage() {}

func (x *TaskSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSize.ProtoReflect.Descriptor instead.
func (*TaskSize) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *TaskSize) GetEstimatedMemoryBytes() int64 {
	if x != nil {
		return x.EstimatedMemoryBytes
	}
	return 0
}

func (x *TaskSize) GetEstimatedMilliCpu() int64 {
	if x != nil {
		return x.EstimatedMilliCpu
	}
	return 0
}

func (x *TaskSize) GetEstimatedFreeDiskBytes() int64 {
	if x != nil {
		return x.EstimatedFreeDiskBytes
	}
	return 0
}

func (x *TaskSize) GetDiskReadBps() int64 {
	if x != nil {
		return x.DiskReadBps
	}
	return 0
}

func (x *TaskSize) GetDiskWriteBps() int64 {
	if x != nil {
		return x.DiskWriteBps
	}
	return 0
}

func (x *TaskSize) GetDiskReadIops() int64 {
	if x != nil {
		return x.DiskReadIops
	}
	return 0
}

func (x *TaskSize) GetDiskWriteIops() int64 {
	if x != nil {
		return x.DiskWriteIops
	}
	return 0
}

func (x *TaskSize) GetCustomResources() []*CustomResource {
	if x != nil {
		return x.CustomResources
	}
	return nil
}

type CgroupSettings struct {
	state                    protoimpl.MessageState        `protogen:"open.v1"`
	CpuWeight                *int64                        `protobuf:"varint,1,opt,name=cpu_weight,json=cpuWeight,proto3,oneof" json:"cpu_weight,omitempty"`
	CpuQuotaLimitUsec        *int64                        `protobuf:"varint,2,opt,name=cpu_quota_limit_usec,json=cpuQuotaLimitUsec,proto3,oneof" json:"cpu_quota_limit_usec,omitempty"`
	CpuQuotaPeriodUsec       *int64                        `protobuf:"varint,3,opt,name=cpu_quota_period_usec,json=cpuQuotaPeriodUsec,proto3,oneof" json:"cpu_quota_period_usec,omitempty"`
	CpuMaxBurstUsec          *int64                        `protobuf:"varint,4,opt,name=cpu_max_burst_usec,json=cpuMaxBurstUsec,proto3,oneof" json:"cpu_max_burst_usec,omitempty"`
	CpuUclampMin             *float32                      `protobuf:"fixed32,5,opt,name=cpu_uclamp_min,json=cpuUclampMin,proto3,oneof" json:"cpu_uclamp_min,omitempty"`
	CpuUclampMax             *float32                      `protobuf:"fixed32,6,opt,name=cpu_uclamp_max,json=cpuUclampMax,proto3,oneof" json:"cpu_uclamp_max,omitempty"`
	PidsMax                  *int64                        `protobuf:"varint,7,opt,name=pids_max,json=pidsMax,proto3,oneof" json:"pids_max,omitempty"`
	MemoryThrottleLimitBytes *int64                        `protobuf:"varint,8,opt,name=memory_throttle_limit_bytes,json=memoryThrottleLimitBytes,proto3,oneof" json:"memory_throttle_limit_bytes,omitempty"`
	MemoryLimitBytes         *int64                        `protobuf:"varint,9,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3,oneof" json:"memory_limit_bytes,omitempty"`
	MemorySoftGuaranteeBytes *int64                        `protobuf:"varint,10,opt,name=memory_soft_guarantee_bytes,json=memorySoftGuaranteeBytes,proto3,oneof" json:"memory_soft_guarantee_bytes,omitempty"`
	MemoryMinimumBytes       *int64                        `protobuf:"varint,11,opt,name=memory_minimum_bytes,json=memoryMinimumBytes,proto3,oneof" json:"memory_minimum_bytes,omitempty"`
	MemoryOomGroup           *bool                         `protobuf:"varint,12,opt,name=memory_oom_group,json=memoryOomGroup,proto3,oneof" json:"memory_oom_group,omitempty"`
	SwapThrottleLimitBytes   *int64                        `protobuf:"varint,13,opt,name=swap_throttle_limit_bytes,json=swapThrottleLimitBytes,proto3,oneof" json:"swap_throttle_limit_bytes,omitempty"`
	SwapLimitBytes           *int64                        `protobuf:"varint,14,opt,name=swap_limit_bytes,json=swapLimitBytes,proto3,oneof" json:"swap_limit_bytes,omitempty"`
	BlockIoLatencyTargetUsec *int64                        `protobuf:"varint,15,opt,name=block_io_latency_target_usec,json=blockIoLatencyTargetUsec,proto3,oneof" json:"block_io_latency_target_usec,omitempty"`
	BlockIoWeight            *int64                        `protobuf:"varint,16,opt,name=block_io_weight,json=blockIoWeight,proto3,oneof" json:"block_io_weight,omitempty"`
	BlockIoLimit             *CgroupSettings_BlockIOLimits `protobuf:"bytes,17,opt,name=block_io_limit,json=blockIoLimit,proto3" json:"block_io_limit,omitempty"`
	CpusetCpus               []int32                       `protobuf:"varint,18,rep,packed,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	NumaNode                 *int32                        `protobuf:"varint,19,opt,name=numa_node,json=numaNode,proto3,oneof" json:"numa_node,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CgroupSettings) Reset() {
	*x = CgroupSettings{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgroupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgroupSettings) ProtoMessage() {}

func (x *CgroupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CgroupSettings.ProtoReflect.Descriptor instead.
func (*CgroupSettings) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *CgroupSettings) GetCpuWeight() int64 {
	if x != nil && x.CpuWeight != nil {
		return *x.CpuWeight
	}
	return 0
}

func (x *CgroupSettings) GetCpuQuotaLimitUsec() int64 {
	if x != nil && x.CpuQuotaLimitUsec != nil {
		return *x.CpuQuotaLimitUsec
	}
	return 0
}

func (x *CgroupSettings) GetCpuQuotaPeriodUsec() int64 {
	if x != nil && x.CpuQuotaPeriodUsec != nil {
		return *x.CpuQuotaPeriodUsec
	}
	return 0
}

func (x *CgroupSettings) GetCpuMaxBurstUsec() int64 {
	if x != nil && x.CpuMaxBurstUsec != nil {
		return *x.CpuMaxBurstUsec
	}
	return 0
}

func (x *CgroupSettings) GetCpuUclampMin() float32 {
	if x != nil && x.CpuUclampMin != nil {
		return *x.CpuUclampMin
	}
	return 0
}

func (x *CgroupSettings) GetCpuUclampMax() float32 {
	if x != nil && x.CpuUclampMax != nil {
		return *x.CpuUclampMax
	}
	return 0
}

func (x *CgroupSettings) GetPidsMax() int64 {
	if x != nil && x.PidsMax != nil {
		return *x.PidsMax
	}
	return 0
}

func (x *CgroupSettings) GetMemoryThrottleLimitBytes() int64 {
	if x != nil && x.MemoryThrottleLimitBytes != nil {
		return *x.MemoryThrottleLimitBytes
	}
	return 0
}

func (x *CgroupSettings) GetMemoryLimitBytes() int64 {
	if x != nil && x.MemoryLimitBytes != nil {
		return *x.MemoryLimitBytes
	}
	return 0
}

func (x *CgroupSettings) GetMemorySoftGuaranteeBytes() int64 {
	if x != nil && x.MemorySoftGuaranteeBytes != nil {
		return *x.MemorySoftGuaranteeBytes
	}
	return 0
}

func (x *CgroupSettings) GetMemoryMinimumBytes() int64 {
	if x != nil && x.MemoryMinimumBytes != nil {
		return *x.MemoryMinimumBytes
	}
	return 0
}

func (x *CgroupSettings) GetMemoryOomGroup() bool {
	if x != nil && x.MemoryOomGroup != nil {
		return *x.MemoryOomGroup
	}
	return false
}

func (x *CgroupSettings) GetSwapThrottleLimitBytes() int64 {
	if x != nil && x.SwapThrottleLimitBytes != nil {
		return *x.SwapThrottleLimitBytes
	}
	return 0
}

func (x *CgroupSettings) GetSwapLimitBytes() int64 {
	if x != nil && x.SwapLimitBytes != nil {
		return *x.SwapLimitBytes
	}
	return 0
}

func (x *CgroupSettings) GetBlockIoLatencyTargetUsec() int64 {
	if x != nil && x.BlockIoLatencyTargetUsec != nil {
		return *x.BlockIoLatencyTargetUsec
	}
	return 0
}

func (x *CgroupSettings) GetBlockIoWeight() int64 {
	if x != nil && x.BlockIoWeight != nil {
		return *x.BlockIoWeight
	}
	return 0
}

func (x *CgroupSettings) GetBlockIoLimit() *CgroupSettings_BlockIOLimits {
	if x != nil {
		return x.BlockIoLimit
	}
	return nil
}

func (x *CgroupSettings) GetCpusetCpus() []int32 {
	if x != nil {
		return x.CpusetCpus
	}
	return nil
}

func (x *CgroupSettings) GetNumaNode() int32 {
	if x != nil && x.NumaNode != nil {
		return *x.NumaNode
	}
	return 0
}

type SchedulingMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in proto/scheduler.proto.
	TaskSize          *TaskSize `protobuf:"bytes,1,opt,name=task_size,json=taskSize,proto3" json:"task_size,omitempty"`
	DefaultTaskSize   *TaskSize `protobuf:"bytes,13,opt,name=default_task_size,json=defaultTaskSize,proto3" json:"default_task_size,omitempty"`
	MeasuredTaskSize  *TaskSize `protobuf:"bytes,7,opt,name=measured_task_size,json=measuredTaskSize,proto3" json:"measured_task_size,omitempty"`
	PredictedTaskSize *TaskSize `protobuf:"bytes,8,opt,name=predicted_task_size,json=predictedTaskSize,proto3" json:"predicted_task_size,omitempty"`
	RequestedTaskSize *TaskSize `protobuf:"bytes,10,opt,name=requested_task_size,json=requestedTaskSize,proto3" json:"requested_task_size,omitempty"`
	Os                string    `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch              string    `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Pool              string    `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`
	// Deprecated: Marked as deprecated in proto/scheduler.proto.
	HostnamePattern     string          `protobuf:"bytes,15,opt,name=hostname_pattern,json=hostnamePattern,proto3" json:"hostname_pattern,omitempty"`
	RoutingConfig       *RoutingConfig  `protobuf:"bytes,16,opt,name=routing_config,json=routingConfig,proto3" json:"routing_config,omitempty"`
	ExecutorGroupId     string          `protobuf:"bytes,5,opt,name=executor_group_id,json=executorGroupId,proto3" json:"executor_group_id,omitempty"`
	TaskGroupId         string          `protobuf:"bytes,6,opt,name=task_group_id,json=taskGroupId,proto3" json:"task_group_id,omitempty"`
	TrackQueuedTaskSize bool            `protobuf:"varint,9,opt,name=track_queued_task_size,json=trackQueuedTaskSize,proto3" json:"track_queued_task_size,omitempty"`
	Priority            int32           `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	CgroupSettings      *CgroupSettings `protobuf:"bytes,12,opt,name=cgroup_settings,json=cgroupSettings,proto3" json:"cgroup_settings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SchedulingMetadata) Reset() {
	*x = SchedulingMetadata{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingMetadata) ProtoMessage() {}

func (x *SchedulingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingMetadata.ProtoReflect.Descriptor instead.
func (*SchedulingMetadata) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

// Deprecated: Marked as deprecated in proto/scheduler.proto.
func (x *SchedulingMetadata) GetTaskSize() *TaskSize {
	if x != nil {
		return x.TaskSize
	}
	return nil
}

func (x *SchedulingMetadata) GetDefaultTaskSize() *TaskSize {
	if x != nil {
		return x.DefaultTaskSize
	}
	return nil
}

func (x *SchedulingMetadata) GetMeasuredTaskSize() *TaskSize {
	if x != nil {
		return x.MeasuredTaskSize
	}
	return nil
}

func (x *SchedulingMetadata) GetPredictedTaskSize() *TaskSize {
	if x != nil {
		return x.PredictedTaskSize
	}
	return nil
}

func (x *SchedulingMetadata) GetRequestedTaskSize() *TaskSize {
	if x != nil {
		return x.RequestedTaskSize
	}
	return nil
}

func (x *SchedulingMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SchedulingMetadata) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SchedulingMetadata) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/scheduler.proto.
func (x *SchedulingMetadata) GetHostnamePattern() string {
	if x != nil {
		return x.HostnamePattern
	}
	return ""
}

func (x *SchedulingMetadata) GetRoutingConfig() *RoutingConfig {
	if x != nil {
		return x.RoutingConfig
	}
	return nil
}

func (x *SchedulingMetadata) GetExecutorGroupId() string {
	if x != nil {
		return x.ExecutorGroupId
	}
	return ""
}

func (x *SchedulingMetadata) GetTaskGroupId() string {
	if x != nil {
		return x.TaskGroupId
	}
	return ""
}

func (x *SchedulingMetadata) GetTrackQueuedTaskSize() bool {
	if x != nil {
		return x.TrackQueuedTaskSize
	}
	return false
}

func (x *SchedulingMetadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SchedulingMetadata) GetCgroupSettings() *CgroupSettings {
	if x != nil {
		return x.CgroupSettings
	}
	return nil
}

type RoutingConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostnamePattern string                 `protobuf:"bytes,1,opt,name=hostname_pattern,json=hostnamePattern,proto3" json:"hostname_pattern,omitempty"`
	BestEffort      bool                   `protobuf:"varint,2,opt,name=best_effort,json=bestEffort,proto3" json:"best_effort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoutingConfig) Reset() {
	*x = RoutingConfig{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingConfig) ProtoMessage() {}

func (x *RoutingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingConfig.ProtoReflect.Descriptor instead.
func (*RoutingConfig) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *RoutingConfig) GetHostnamePattern() string {
	if x != nil {
		return x.HostnamePattern
	}
	return ""
}

func (x *RoutingConfig) GetBestEffort() bool {
	if x != nil {
		return x.BestEffort
	}
	return false
}

type ScheduleTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Metadata       *SchedulingMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SerializedTask []byte                 `protobuf:"bytes,3,opt,name=serialized_task,json=serializedTask,proto3" json:"serialized_task,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ScheduleTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScheduleTaskRequest) GetMetadata() *SchedulingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScheduleTaskRequest) GetSerializedTask() []byte {
	if x != nil {
		return x.SerializedTask
	}
	return nil
}

type ScheduleTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskResponse) Reset() {
	*x = ScheduleTaskResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskResponse) ProtoMessage() {}

func (x *ScheduleTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

type ReEnqueueTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEnqueueTaskRequest) Reset() {
	*x = ReEnqueueTaskRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEnqueueTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEnqueueTaskRequest) ProtoMessage() {}

func (x *ReEnqueueTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEnqueueTaskRequest.ProtoReflect.Descriptor instead.
func (*ReEnqueueTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *ReEnqueueTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReEnqueueTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReEnqueueTaskRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ReEnqueueTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEnqueueTaskResponse) Reset() {
	*x = ReEnqueueTaskResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEnqueueTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEnqueueTaskResponse) ProtoMessage() {}

func (x *ReEnqueueTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEnqueueTaskResponse.ProtoReflect.Descriptor instead.
func (*ReEnqueueTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

type EnqueueTaskReservationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskSize           *TaskSize              `protobuf:"bytes,2,opt,name=task_size,json=taskSize,proto3" json:"task_size,omitempty"`
	SchedulingMetadata *SchedulingMetadata    `protobuf:"bytes,3,opt,name=scheduling_metadata,json=schedulingMetadata,proto3" json:"scheduling_metadata,omitempty"`
	ExecutorId         string                 `protobuf:"bytes,4,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Delay              *durationpb.Duration   `protobuf:"bytes,5,opt,name=delay,proto3" json:"delay,omitempty"`
	Jwt                string                 `protobuf:"bytes,6,opt,name=jwt,proto3" json:"jwt,omitempty"`
	TraceMetadata      *trace.Metadata        `protobuf:"bytes,100,opt,name=trace_metadata,json=traceMetadata,proto3" json:"trace_metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnqueueTaskReservationRequest) Reset() {
	*x = EnqueueTaskReservationRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTaskReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTaskReservationRequest) ProtoMessage() {}

func (x *EnqueueTaskReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTaskReservationRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTaskReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *EnqueueTaskReservationRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EnqueueTaskReservationRequest) GetTaskSize() *TaskSize {
	if x != nil {
		return x.TaskSize
	}
	return nil
}

func (x *EnqueueTaskReservationRequest) GetSchedulingMetadata() *SchedulingMetadata {
	if x != nil {
		return x.SchedulingMetadata
	}
	return nil
}

func (x *EnqueueTaskReservationRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *EnqueueTaskReservationRequest) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *EnqueueTaskReservationRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *EnqueueTaskReservationRequest) GetTraceMetadata() *trace.Metadata {
	if x != nil {
		return x.TraceMetadata
	}
	return nil
}

type EnqueueTaskReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTaskReservationResponse) Reset() {
	*x = EnqueueTaskReservationResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTaskReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTaskReservationResponse) ProtoMessage() {}

func (x *EnqueueTaskReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTaskReservationResponse.ProtoReflect.Descriptor instead.
func (*EnqueueTaskReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *EnqueueTaskReservationResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReservationRequest) Reset() {
	*x = CancelTaskReservationRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReservationRequest) ProtoMessage() {}

func (x *CancelTaskReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskReservationRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RegisterExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *ExecutionNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterExecutorRequest) Reset() {
	*x = RegisterExecutorRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest) ProtoMessage() {}

func (x *RegisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterExecutorRequest) GetNode() *ExecutionNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type AskForMoreWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskForMoreWorkRequest) Reset() {
	*x = AskForMoreWorkRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskForMoreWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForMoreWorkRequest) ProtoMessage() {}

func (x *AskForMoreWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForMoreWorkRequest.ProtoReflect.Descriptor instead.
func (*AskForMoreWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{18}
}

type AskForMoreWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delay         *durationpb.Duration   `protobuf:"bytes,1,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskForMoreWorkResponse) Reset() {
	*x = AskForMoreWorkResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskForMoreWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForMoreWorkResponse) ProtoMessage() {}

func (x *AskForMoreWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForMoreWorkResponse.ProtoReflect.Descriptor instead.
func (*AskForMoreWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *AskForMoreWorkResponse) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

type ShuttingDownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        []string               `protobuf:"bytes,1,rep,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuttingDownRequest) Reset() {
	*x = ShuttingDownRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuttingDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuttingDownRequest) ProtoMessage() {}

func (x *ShuttingDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuttingDownRequest.ProtoReflect.Descriptor instead.
func (*ShuttingDownRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *ShuttingDownRequest) GetTaskId() []string {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type RegisterAndStreamWorkRequest struct {
	state                          protoimpl.MessageState          `protogen:"open.v1"`
	RegisterExecutorRequest        *RegisterExecutorRequest        `protobuf:"bytes,1,opt,name=register_executor_request,json=registerExecutorRequest,proto3" json:"register_executor_request,omitempty"`
	EnqueueTaskReservationResponse *EnqueueTaskReservationResponse `protobuf:"bytes,2,opt,name=enqueue_task_reservation_response,json=enqueueTaskReservationResponse,proto3" json:"enqueue_task_reservation_response,omitempty"`
	ShuttingDownRequest            *ShuttingDownRequest            `protobuf:"bytes,3,opt,name=shutting_down_request,json=shuttingDownRequest,proto3" json:"shutting_down_request,omitempty"`
	AskForMoreWorkRequest          *AskForMoreWorkRequest          `protobuf:"bytes,4,opt,name=ask_for_more_work_request,json=askForMoreWorkRequest,proto3" json:"ask_for_more_work_request,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RegisterAndStreamWorkRequest) Reset() {
	*x = RegisterAndStreamWorkRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAndStreamWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAndStreamWorkRequest) ProtoMessage() {}

func (x *RegisterAndStreamWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAndStreamWorkRequest.ProtoReflect.Descriptor instead.
func (*RegisterAndStreamWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterAndStreamWorkRequest) GetRegisterExecutorRequest() *RegisterExecutorRequest {
	if x != nil {
		return x.RegisterExecutorRequest
	}
	return nil
}

func (x *RegisterAndStreamWorkRequest) GetEnqueueTaskReservationResponse() *EnqueueTaskReservationResponse {
	if x != nil {
		return x.EnqueueTaskReservationResponse
	}
	return nil
}

func (x *RegisterAndStreamWorkRequest) GetShuttingDownRequest() *ShuttingDownRequest {
	if x != nil {
		return x.ShuttingDownRequest
	}
	return nil
}

func (x *RegisterAndStreamWorkRequest) GetAskForMoreWorkRequest() *AskForMoreWorkRequest {
	if x != nil {
		return x.AskForMoreWorkRequest
	}
	return nil
}

type RegisterAndStreamWorkResponse struct {
	state                         protoimpl.MessageState         `protogen:"open.v1"`
	EnqueueTaskReservationRequest *EnqueueTaskReservationRequest `protobuf:"bytes,3,opt,name=enqueue_task_reservation_request,json=enqueueTaskReservationRequest,proto3" json:"enqueue_task_reservation_request,omitempty"`
	AskForMoreWorkResponse        *AskForMoreWorkResponse        `protobuf:"bytes,4,opt,name=ask_for_more_work_response,json=askForMoreWorkResponse,proto3" json:"ask_for_more_work_response,omitempty"`
	CancelTaskReservationRequest  *CancelTaskReservationRequest  `protobuf:"bytes,5,opt,name=cancel_task_reservation_request,json=cancelTaskReservationRequest,proto3" json:"cancel_task_reservation_request,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RegisterAndStreamWorkResponse) Reset() {
	*x = RegisterAndStreamWorkResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAndStreamWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAndStreamWorkResponse) ProtoMessage() {}

func (x *RegisterAndStreamWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAndStreamWorkResponse.ProtoReflect.Descriptor instead.
func (*RegisterAndStreamWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterAndStreamWorkResponse) GetEnqueueTaskReservationRequest() *EnqueueTaskReservationRequest {
	if x != nil {
		return x.EnqueueTaskReservationRequest
	}
	return nil
}

func (x *RegisterAndStreamWorkResponse) GetAskForMoreWorkResponse() *AskForMoreWorkResponse {
	if x != nil {
		return x.AskForMoreWorkResponse
	}
	return nil
}

func (x *RegisterAndStreamWorkResponse) GetCancelTaskReservationRequest() *CancelTaskReservationRequest {
	if x != nil {
		return x.CancelTaskReservationRequest
	}
	return nil
}

type ExecutionNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Deprecated: Marked as deprecated in proto/scheduler.proto.
	Port                          int32             `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	AssignableMemoryBytes         int64             `protobuf:"varint,3,opt,name=assignable_memory_bytes,json=assignableMemoryBytes,proto3" json:"assignable_memory_bytes,omitempty"`
	AssignableMilliCpu            int64             `protobuf:"varint,4,opt,name=assignable_milli_cpu,json=assignableMilliCpu,proto3" json:"assignable_milli_cpu,omitempty"`
	AssignableCustomResources     []*CustomResource `protobuf:"bytes,11,rep,name=assignable_custom_resources,json=assignableCustomResources,proto3" json:"assignable_custom_resources,omitempty"`
	OsFamily                      string            `protobuf:"bytes,5,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	OsDisplayName                 string            `protobuf:"bytes,15,opt,name=os_display_name,json=osDisplayName,proto3" json:"os_display_name,omitempty"`
	Arch                          string            `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	Pool                          string            `protobuf:"bytes,7,opt,name=pool,proto3" json:"pool,omitempty"`
	Version                       string            `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	ExecutorId                    string            `protobuf:"bytes,9,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorHostId                string            `protobuf:"bytes,10,opt,name=executor_host_id,json=executorHostId,proto3" json:"executor_host_id,omitempty"`
	SupportedIsolationTypes       []string          `protobuf:"bytes,12,rep,name=supported_isolation_types,json=supportedIsolationTypes,proto3" json:"supported_isolation_types,omitempty"`
	CurrentQueueLength            int32             `protobuf:"varint,13,opt,name=current_queue_length,json=currentQueueLength,proto3" json:"current_queue_length,omitempty"`
	ActiveActionCount             int32             `protobuf:"varint,14,opt,name=active_action_count,json=activeActionCount,proto3" json:"active_action_count,omitempty"`
	XcodeVersions                 []string          `protobuf:"bytes,16,rep,name=xcode_versions,json=xcodeVersions,proto3" json:"xcode_versions,omitempty"`
	XcodeSdks                     []string          `protobuf:"bytes,17,rep,name=xcode_sdks,json=xcodeSdks,proto3" json:"xcode_sdks,omitempty"`
	SupportsProactiveCancellation bool              `protobuf:"varint,18,opt,name=supports_proactive_cancellation,json=supportsProactiveCancellation,proto3" json:"supports_proactive_cancellation,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ExecutionNode) Reset() {
	*x = ExecutionNode{}
	mi := &file_proto_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionNode) ProtoMessage() {}

func (x *ExecutionNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionNode.ProtoReflect.Descriptor instead.
func (*ExecutionNode) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{23}
}

func (x *ExecutionNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/scheduler.proto.
func (x *ExecutionNode) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExecutionNode) GetAssignableMemoryBytes() int64 {
	if x != nil {
		return x.AssignableMemoryBytes
	}
	return 0
}

func (x *ExecutionNode) GetAssignableMilliCpu() int64 {
	if x != nil {
		return x.AssignableMilliCpu
	}
	return 0
}

func (x *ExecutionNode) GetAssignableCustomResources() []*CustomResource {
	if x != nil {
		return x.AssignableCustomResources
	}
	return nil
}

func (x *ExecutionNode) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *ExecutionNode) GetOsDisplayName() string {
	if x != nil {
		return x.OsDisplayName
	}
	return ""
}

func (x *ExecutionNode) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ExecutionNode) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *ExecutionNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExecutionNode) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecutionNode) GetExecutorHostId() string {
	if x != nil {
		return x.ExecutorHostId
	}
	return ""
}

func (x *ExecutionNode) GetSupportedIsolationTypes() []string {
	if x != nil {
		return x.SupportedIsolationTypes
	}
	return nil
}

func (x *ExecutionNode) GetCurrentQueueLength() int32 {
	if x != nil {
		return x.CurrentQueueLength
	}
	return 0
}

func (x *ExecutionNode) GetActiveActionCount() int32 {
	if x != nil {
		return x.ActiveActionCount
	}
	return 0
}

func (x *ExecutionNode) GetXcodeVersions() []string {
	if x != nil {
		return x.XcodeVersions
	}
	return nil
}

func (x *ExecutionNode) GetXcodeSdks() []string {
	if x != nil {
		return x.XcodeSdks
	}
	return nil
}

func (x *ExecutionNode) GetSupportsProactiveCancellation() bool {
	if x != nil {
		return x.SupportsProactiveCancellation
	}
	return false
}

type GetExecutionNodesRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetExecutionNodesRequest) Reset() {
	*x = GetExecutionNodesRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionNodesRequest) ProtoMessage() {}

func (x *GetExecutionNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionNodesRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *GetExecutionNodesRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

type GetExecutionNodesResponse struct {
	state                       protoimpl.MessageState                `protogen:"open.v1"`
	ResponseContext             *context.ResponseContext              `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	Executor                    []*GetExecutionNodesResponse_Executor `protobuf:"bytes,2,rep,name=executor,proto3" json:"executor,omitempty"`
	UserOwnedExecutorsSupported bool                                  `protobuf:"varint,3,opt,name=user_owned_executors_supported,json=userOwnedExecutorsSupported,proto3" json:"user_owned_executors_supported,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetExecutionNodesResponse) Reset() {
	*x = GetExecutionNodesResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionNodesResponse) ProtoMessage() {}

func (x *GetExecutionNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionNodesResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *GetExecutionNodesResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *GetExecutionNodesResponse) GetExecutor() []*GetExecutionNodesResponse_Executor {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *GetExecutionNodesResponse) GetUserOwnedExecutorsSupported() bool {
	if x != nil {
		return x.UserOwnedExecutorsSupported
	}
	return false
}

type RegisteredExecutionNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Registration      *ExecutionNode         `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	SchedulerHostPort string                 `protobuf:"bytes,2,opt,name=scheduler_host_port,json=schedulerHostPort,proto3" json:"scheduler_host_port,omitempty"`
	GroupId           string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Acl               *acl.ACL               `protobuf:"bytes,4,opt,name=acl,proto3" json:"acl,omitempty"`
	LastPingTime      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_ping_time,json=lastPingTime,proto3" json:"last_ping_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisteredExecutionNode) Reset() {
	*x = RegisteredExecutionNode{}
	mi := &file_proto_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredExecutionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredExecutionNode) ProtoMessage() {}

func (x *RegisteredExecutionNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredExecutionNode.ProtoReflect.Descriptor instead.
func (*RegisteredExecutionNode) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *RegisteredExecutionNode) GetRegistration() *ExecutionNode {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *RegisteredExecutionNode) GetSchedulerHostPort() string {
	if x != nil {
		return x.SchedulerHostPort
	}
	return ""
}

func (x *RegisteredExecutionNode) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RegisteredExecutionNode) GetAcl() *acl.ACL {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *RegisteredExecutionNode) GetLastPingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPingTime
	}
	return nil
}

type CgroupSettings_BlockIOLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Riops         *int64                 `protobuf:"varint,1,opt,name=riops,proto3,oneof" json:"riops,omitempty"`
	Wiops         *int64                 `protobuf:"varint,2,opt,name=wiops,proto3,oneof" json:"wiops,omitempty"`
	Rbps          *int64                 `protobuf:"varint,3,opt,name=rbps,proto3,oneof" json:"rbps,omitempty"`
	Wbps          *int64                 `protobuf:"varint,4,opt,name=wbps,proto3,oneof" json:"wbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CgroupSettings_BlockIOLimits) Reset() {
	*x = CgroupSettings_BlockIOLimits{}
	mi := &file_proto_scheduler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgroupSettings_BlockIOLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgroupSettings_BlockIOLimits) ProtoMessage() {}

func (x *CgroupSettings_BlockIOLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CgroupSettings_BlockIOLimits.ProtoReflect.Descriptor instead.
func (*CgroupSettings_BlockIOLimits) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7, 0}
}

func (x *CgroupSettings_BlockIOLimits) GetRiops() int64 {
	if x != nil && x.Riops != nil {
		return *x.Riops
	}
	return 0
}

func (x *CgroupSettings_BlockIOLimits) GetWiops() int64 {
	if x != nil && x.Wiops != nil {
		return *x.Wiops
	}
	return 0
}

func (x *CgroupSettings_BlockIOLimits) GetRbps() int64 {
	if x != nil && x.Rbps != nil {
		return *x.Rbps
	}
	return 0
}

func (x *CgroupSettings_BlockIOLimits) GetWbps() int64 {
	if x != nil && x.Wbps != nil {
		return *x.Wbps
	}
	return 0
}

type GetExecutionNodesResponse_Executor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Node            *ExecutionNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	IsDefault       bool                   `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	LastCheckInTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check_in_time,json=lastCheckInTime,proto3" json:"last_check_in_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExecutionNodesResponse_Executor) Reset() {
	*x = GetExecutionNodesResponse_Executor{}
	mi := &file_proto_scheduler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionNodesResponse_Executor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionNodesResponse_Executor) ProtoMessage() {}

func (x *GetExecutionNodesResponse_Executor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionNodesResponse_Executor.ProtoReflect.Descriptor instead.
func (*GetExecutionNodesResponse_Executor) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{25, 0}
}

func (x *GetExecutionNodesResponse_Executor) GetNode() *ExecutionNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GetExecutionNodesResponse_Executor) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *GetExecutionNodesResponse_Executor) GetLastCheckInTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckInTime
	}
	return nil
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\x1a\x17google/rpc/status.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fproto/acl.proto\x1a\x13proto/context.proto\x1a\x11proto/trace.proto\"5\n" +
	"\vNodeAddress\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\",\n" +
	"\x11TaskExistsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\",\n" +
	"\x12TaskExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xe6\x02\n" +
	"\x10LeaseTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfinalize\x18\x02 \x01(\bR\bfinalize\x12\x18\n" +
	"\arelease\x18\x03 \x01(\bR\arelease\x12\x1f\n" +
	"\vexecutor_id\x18\x04 \x01(\tR\n" +
	"executorId\x12+\n" +
	"\x11executor_hostname\x18\t \x01(\tR\x10executorHostname\x12\x1d\n" +
	"\n" +
	"re_enqueue\x18\x05 \x01(\bR\treEnqueue\x12>\n" +
	"\x11re_enqueue_reason\x18\x06 \x01(\v2\x12.google.rpc.StatusR\x0freEnqueueReason\x12-\n" +
	"\x12supports_reconnect\x18\a \x01(\bR\x11supportsReconnect\x12'\n" +
	"\x0freconnect_token\x18\b \x01(\tR\x0ereconnectToken\"\x8c\x02\n" +
	"\x11LeaseTaskResponse\x12'\n" +
	"\x0fserialized_task\x18\x01 \x01(\fR\x0eserializedTask\x124\n" +
	"\x16lease_duration_seconds\x18\x02 \x01(\x03R\x14leaseDurationSeconds\x12%\n" +
	"\x0eclosed_cleanly\x18\x03 \x01(\bR\rclosedCleanly\x12'\n" +
	"\x0freconnect_token\x18\x04 \x01(\tR\x0ereconnectToken\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12-\n" +
	"\x12supports_reconnect\x18\x06 \x01(\bR\x11supportsReconnect\":\n" +
	"\x0eCustomResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"\x89\x03\n" +
	"\bTaskSize\x124\n" +
	"\x16estimated_memory_bytes\x18\x01 \x01(\x03R\x14estimatedMemoryBytes\x12.\n" +
	"\x13estimated_milli_cpu\x18\x02 \x01(\x03R\x11estimatedMilliCpu\x129\n" +
	"\x19estimated_free_disk_bytes\x18\x03 \x01(\x03R\x16estimatedFreeDiskBytes\x12\"\n" +
	"\rdisk_read_bps\x18\x05 \x01(\x03R\vdiskReadBps\x12$\n" +
	"\x0edisk_write_bps\x18\x06 \x01(\x03R\fdiskWriteBps\x12$\n" +
	"\x0edisk_read_iops\x18\a \x01(\x03R\fdiskReadIops\x12&\n" +
	"\x0fdisk_write_iops\x18\b \x01(\x03R\rdiskWriteIops\x12D\n" +
	"\x10custom_resources\x18\x04 \x03(\v2\x19.scheduler.CustomResourceR\x0fcustomResources\"\x85\f\n" +
	"\x0eCgroupSettings\x12\"\n" +
	"\n" +
	"cpu_weight\x18\x01 \x01(\x03H\x00R\tcpuWeight\x88\x01\x01\x124\n" +
	"\x14cpu_quota_limit_usec\x18\x02 \x01(\x03H\x01R\x11cpuQuotaLimitUsec\x88\x01\x01\x126\n" +
	"\x15cpu_quota_period_usec\x18\x03 \x01(\x03H\x02R\x12cpuQuotaPeriodUsec\x88\x01\x01\x120\n" +
	"\x12cpu_max_burst_usec\x18\x04 \x01(\x03H\x03R\x0fcpuMaxBurstUsec\x88\x01\x01\x12)\n" +
	"\x0ecpu_uclamp_min\x18\x05 \x01(\x02H\x04R\fcpuUclampMin\x88\x01\x01\x12)\n" +
	"\x0ecpu_uclamp_max\x18\x06 \x01(\x02H\x05R\fcpuUclampMax\x88\x01\x01\x12\x1e\n" +
	"\bpids_max\x18\a \x01(\x03H\x06R\apidsMax\x88\x01\x01\x12B\n" +
	"\x1bmemory_throttle_limit_bytes\x18\b \x01(\x03H\aR\x18memoryThrottleLimitBytes\x88\x01\x01\x121\n" +
	"\x12memory_limit_bytes\x18\t \x01(\x03H\bR\x10memoryLimitBytes\x88\x01\x01\x12B\n" +
	"\x1bmemory_soft_guarantee_bytes\x18\n" +
	" \x01(\x03H\tR\x18memorySoftGuaranteeBytes\x88\x01\x01\x125\n" +
	"\x14memory_minimum_bytes\x18\v \x01(\x03H\n" +
	"R\x12memoryMinimumBytes\x88\x01\x01\x12-\n" +
	"\x10memory_oom_group\x18\f \x01(\bH\vR\x0ememoryOomGroup\x88\x01\x01\x12>\n" +
	"\x19swap_throttle_limit_bytes\x18\r \x01(\x03H\fR\x16swapThrottleLimitBytes\x88\x01\x01\x12-\n" +
	"\x10swap_limit_bytes\x18\x0e \x01(\x03H\rR\x0eswapLimitBytes\x88\x01\x01\x12C\n" +
	"\x1cblock_io_latency_target_usec\x18\x0f \x01(\x03H\x0eR\x18blockIoLatencyTargetUsec\x88\x01\x01\x12+\n" +
	"\x0fblock_io_weight\x18\x10 \x01(\x03H\x0fR\rblockIoWeight\x88\x01\x01\x12M\n" +
	"\x0eblock_io_limit\x18\x11 \x01(\v2'.scheduler.CgroupSettings.BlockIOLimitsR\fblockIoLimit\x12\x1f\n" +
	"\vcpuset_cpus\x18\x12 \x03(\x05R\n" +
	"cpusetCpus\x12 \n" +
	"\tnuma_node\x18\x13 \x01(\x05H\x10R\bnumaNode\x88\x01\x01\x1a\x9d\x01\n" +
	"\rBlockIOLimits\x12\x19\n" +
	"\x05riops\x18\x01 \x01(\x03H\x00R\x05riops\x88\x01\x01\x12\x19\n" +
	"\x05wiops\x18\x02 \x01(\x03H\x01R\x05wiops\x88\x01\x01\x12\x17\n" +
	"\x04rbps\x18\x03 \x01(\x03H\x02R\x04rbps\x88\x01\x01\x12\x17\n" +
	"\x04wbps\x18\x04 \x01(\x03H\x03R\x04wbps\x88\x01\x01B\b\n" +
	"\x06_riopsB\b\n" +
	"\x06_wiopsB\a\n" +
	"\x05_rbpsB\a\n" +
	"\x05_wbpsB\r\n" +
	"\v_cpu_weightB\x17\n" +
	"\x15_cpu_quota_limit_usecB\x18\n" +
	"\x16_cpu_quota_period_usecB\x15\n" +
	"\x13_cpu_max_burst_usecB\x11\n" +
	"\x0f_cpu_uclamp_minB\x11\n" +
	"\x0f_cpu_uclamp_maxB\v\n" +
	"\t_pids_maxB\x1e\n" +
	"\x1c_memory_throttle_limit_bytesB\x15\n" +
	"\x13_memory_limit_bytesB\x1e\n" +
	"\x1c_memory_soft_guarantee_bytesB\x17\n" +
	"\x15_memory_minimum_bytesB\x13\n" +
	"\x11_memory_oom_groupB\x1c\n" +
	"\x1a_swap_throttle_limit_bytesB\x13\n" +
	"\x11_swap_limit_bytesB\x1f\n" +
	"\x1d_block_io_latency_target_usecB\x12\n" +
	"\x10_block_io_weightB\f\n" +
	"\n" +
	"_numa_node\"\xeb\x05\n" +
	"\x12SchedulingMetadata\x124\n" +
	"\ttask_size\x18\x01 \x01(\v2\x13.scheduler.TaskSizeB\x02\x18\x01R\btaskSize\x12?\n" +
	"\x11default_task_size\x18\r \x01(\v2\x13.scheduler.TaskSizeR\x0fdefaultTaskSize\x12A\n" +
	"\x12measured_task_size\x18\a \x01(\v2\x13.scheduler.TaskSizeR\x10measuredTaskSize\x12C\n" +
	"\x13predicted_task_size\x18\b \x01(\v2\x13.scheduler.TaskSizeR\x11predictedTaskSize\x12C\n" +
	"\x13requested_task_size\x18\n" +
	" \x01(\v2\x13.scheduler.TaskSizeR\x11requestedTaskSize\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\x12-\n" +
	"\x10hostname_pattern\x18\x0f \x01(\tB\x02\x18\x01R\x0fhostnamePattern\x12?\n" +
	"\x0erouting_config\x18\x10 \x01(\v2\x18.scheduler.RoutingConfigR\rroutingConfig\x12*\n" +
	"\x11executor_group_id\x18\x05 \x01(\tR\x0fexecutorGroupId\x12\"\n" +
	"\rtask_group_id\x18\x06 \x01(\tR\vtaskGroupId\x123\n" +
	"\x16track_queued_task_size\x18\t \x01(\bR\x13trackQueuedTaskSize\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12B\n" +
	"\x0fcgroup_settings\x18\f \x01(\v2\x19.scheduler.CgroupSettingsR\x0ecgroupSettingsJ\x04\b\x0e\x10\x0f\"[\n" +
	"\rRoutingConfig\x12)\n" +
	"\x10hostname_pattern\x18\x01 \x01(\tR\x0fhostnamePattern\x12\x1f\n" +
	"\vbest_effort\x18\x02 \x01(\bR\n" +
	"bestEffort\"\x92\x01\n" +
	"\x13ScheduleTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.scheduler.SchedulingMetadataR\bmetadata\x12'\n" +
	"\x0fserialized_task\x18\x03 \x01(\fR\x0eserializedTask\"\x16\n" +
	"\x14ScheduleTaskResponse\"b\n" +
	"\x14ReEnqueueTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\"\x17\n" +
	"\x15ReEnqueueTaskResponse\"\xd6\x02\n" +
	"\x1dEnqueueTaskReservationRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\ttask_size\x18\x02 \x01(\v2\x13.scheduler.TaskSizeR\btaskSize\x12N\n" +
	"\x13scheduling_metadata\x18\x03 \x01(\v2\x1d.scheduler.SchedulingMetadataR\x12schedulingMetadata\x12\x1f\n" +
	"\vexecutor_id\x18\x04 \x01(\tR\n" +
	"executorId\x12/\n" +
	"\x05delay\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12\x10\n" +
	"\x03jwt\x18\x06 \x01(\tR\x03jwt\x126\n" +
	"\x0etrace_metadata\x18d \x01(\v2\x0f.trace.MetadataR\rtraceMetadata\"9\n" +
	"\x1eEnqueueTaskReservationResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"7\n" +
	"\x1cCancelTaskReservationRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"G\n" +
	"\x17RegisterExecutorRequest\x12,\n" +
	"\x04node\x18\x01 \x01(\v2\x18.scheduler.ExecutionNodeR\x04node\"\x17\n" +
	"\x15AskForMoreWorkRequest\"I\n" +
	"\x16AskForMoreWorkResponse\x12/\n" +
	"\x05delay\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05delay\".\n" +
	"\x13ShuttingDownRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x03(\tR\x06taskId\"\xa4\x03\n" +
	"\x1cRegisterAndStreamWorkRequest\x12^\n" +
	"\x19register_executor_request\x18\x01 \x01(\v2\".scheduler.RegisterExecutorRequestR\x17registerExecutorRequest\x12t\n" +
	"!enqueue_task_reservation_response\x18\x02 \x01(\v2).scheduler.EnqueueTaskReservationResponseR\x1eenqueueTaskReservationResponse\x12R\n" +
	"\x15shutting_down_request\x18\x03 \x01(\v2\x1e.scheduler.ShuttingDownRequestR\x13shuttingDownRequest\x12Z\n" +
	"\x19ask_for_more_work_request\x18\x04 \x01(\v2 .scheduler.AskForMoreWorkRequestR\x15askForMoreWorkRequest\"\xe1\x02\n" +
	"\x1dRegisterAndStreamWorkResponse\x12q\n" +
	" enqueue_task_reservation_request\x18\x03 \x01(\v2(.scheduler.EnqueueTaskReservationRequestR\x1denqueueTaskReservationRequest\x12]\n" +
	"\x1aask_for_more_work_response\x18\x04 \x01(\v2!.scheduler.AskForMoreWorkResponseR\x16askForMoreWorkResponse\x12n\n" +
	"\x1fcancel_task_reservation_request\x18\x05 \x01(\v2'.scheduler.CancelTaskReservationRequestR\x1ccancelTaskReservationRequest\"\xfe\x05\n" +
	"\rExecutionNode\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x04port\x18\x02 \x01(\x05B\x02\x18\x01R\x04port\x126\n" +
	"\x17assignable_memory_bytes\x18\x03 \x01(\x03R\x15assignableMemoryBytes\x120\n" +
	"\x14assignable_milli_cpu\x18\x04 \x01(\x03R\x12assignableMilliCpu\x12Y\n" +
	"\x1bassignable_custom_resources\x18\v \x03(\v2\x19.scheduler.CustomResourceR\x19assignableCustomResources\x12\x1b\n" +
	"\tos_family\x18\x05 \x01(\tR\bosFamily\x12&\n" +
	"\x0fos_display_name\x18\x0f \x01(\tR\rosDisplayName\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x12\n" +
	"\x04pool\x18\a \x01(\tR\x04pool\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x1f\n" +
	"\vexecutor_id\x18\t \x01(\tR\n" +
	"executorId\x12(\n" +
	"\x10executor_host_id\x18\n" +
	" \x01(\tR\x0eexecutorHostId\x12:\n" +
	"\x19supported_isolation_types\x18\f \x03(\tR\x17supportedIsolationTypes\x120\n" +
	"\x14current_queue_length\x18\r \x01(\x05R\x12currentQueueLength\x12.\n" +
	"\x13active_action_count\x18\x0e \x01(\x05R\x11activeActionCount\x12%\n" +
	"\x0excode_versions\x18\x10 \x03(\tR\rxcodeVersions\x12\x1d\n" +
	"\n" +
	"xcode_sdks\x18\x11 \x03(\tR\txcodeSdks\x12F\n" +
	"\x1fsupports_proactive_cancellation\x18\x12 \x01(\bR\x1dsupportsProactiveCancellation\"\\\n" +
	"\x18GetExecutionNodesRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\"\x93\x03\n" +
	"\x19GetExecutionNodesResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x12I\n" +
	"\bexecutor\x18\x02 \x03(\v2-.scheduler.GetExecutionNodesResponse.ExecutorR\bexecutor\x12C\n" +
	"\x1euser_owned_executors_supported\x18\x03 \x01(\bR\x1buserOwnedExecutorsSupported\x1a\xa0\x01\n" +
	"\bExecutor\x12,\n" +
	"\x04node\x18\x01 \x01(\v2\x18.scheduler.ExecutionNodeR\x04node\x12\x1d\n" +
	"\n" +
	"is_default\x18\x02 \x01(\bR\tisDefault\x12G\n" +
	"\x12last_check_in_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastCheckInTime\"\x80\x02\n" +
	"\x17RegisteredExecutionNode\x12<\n" +
	"\fregistration\x18\x01 \x01(\v2\x18.scheduler.ExecutionNodeR\fregistration\x12.\n" +
	"\x13scheduler_host_port\x18\x02 \x01(\tR\x11schedulerHostPort\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1a\n" +
	"\x03acl\x18\x04 \x01(\v2\b.acl.ACLR\x03acl\x12@\n" +
	"\x0elast_ping_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastPingTime2\xb2\x04\n" +
	"\tScheduler\x12p\n" +
	"\x15RegisterAndStreamWork\x12'.scheduler.RegisterAndStreamWorkRequest\x1a(.scheduler.RegisterAndStreamWorkResponse\"\x00(\x010\x01\x12L\n" +
	"\tLeaseTask\x12\x1b.scheduler.LeaseTaskRequest\x1a\x1c.scheduler.LeaseTaskResponse\"\x00(\x010\x01\x12K\n" +
	"\n" +
	"TaskExists\x12\x1c.scheduler.TaskExistsRequest\x1a\x1d.scheduler.TaskExistsResponse\"\x00\x12Q\n" +
	"\fScheduleTask\x12\x1e.scheduler.ScheduleTaskRequest\x1a\x1f.scheduler.ScheduleTaskResponse\"\x00\x12T\n" +
	"\rReEnqueueTask\x12\x1f.scheduler.ReEnqueueTaskRequest\x1a .scheduler.ReEnqueueTaskResponse\"\x00\x12o\n" +
	"\x16EnqueueTaskReservation\x12(.scheduler.EnqueueTaskReservationRequest\x1a).scheduler.EnqueueTaskReservationResponse\"\x00b\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_scheduler_proto_goTypes = []any{
	(*NodeAddress)(nil),                        // 0: scheduler.NodeAddress
	(*TaskExistsRequest)(nil),                  // 1: scheduler.TaskExistsRequest
	(*TaskExistsResponse)(nil),                 // 2: scheduler.TaskExistsResponse
	(*LeaseTaskRequest)(nil),                   // 3: scheduler.LeaseTaskRequest
	(*LeaseTaskResponse)(nil),                  // 4: scheduler.LeaseTaskResponse
	(*CustomResource)(nil),                     // 5: scheduler.CustomResource
	(*TaskSize)(nil),                           // 6: scheduler.TaskSize
	(*CgroupSettings)(nil),                     // 7: scheduler.CgroupSettings
	(*SchedulingMetadata)(nil),                 // 8: scheduler.SchedulingMetadata
	(*RoutingConfig)(nil),                      // 9: scheduler.RoutingConfig
	(*ScheduleTaskRequest)(nil),                // 10: scheduler.ScheduleTaskRequest
	(*ScheduleTaskResponse)(nil),               // 11: scheduler.ScheduleTaskResponse
	(*ReEnqueueTaskRequest)(nil),               // 12: scheduler.ReEnqueueTaskRequest
	(*ReEnqueueTaskResponse)(nil),              // 13: scheduler.ReEnqueueTaskResponse
	(*EnqueueTaskReservationRequest)(nil),      // 14: scheduler.EnqueueTaskReservationRequest
	(*EnqueueTaskReservationResponse)(nil),     // 15: scheduler.EnqueueTaskReservationResponse
	(*CancelTaskReservationRequest)(nil),       // 16: scheduler.CancelTaskReservationRequest
	(*RegisterExecutorRequest)(nil),            // 17: scheduler.RegisterExecutorRequest
	(*AskForMoreWorkRequest)(nil),              // 18: scheduler.AskForMoreWorkRequest
	(*AskForMoreWorkResponse)(nil),             // 19: scheduler.AskForMoreWorkResponse
	(*ShuttingDownRequest)(nil),                // 20: scheduler.ShuttingDownRequest
	(*RegisterAndStreamWorkRequest)(nil),       // 21: scheduler.RegisterAndStreamWorkRequest
	(*RegisterAndStreamWorkResponse)(nil),      // 22: scheduler.RegisterAndStreamWorkResponse
	(*ExecutionNode)(nil),                      // 23: scheduler.ExecutionNode
	(*GetExecutionNodesRequest)(nil),           // 24: scheduler.GetExecutionNodesRequest
	(*GetExecutionNodesResponse)(nil),          // 25: scheduler.GetExecutionNodesResponse
	(*RegisteredExecutionNode)(nil),            // 26: scheduler.RegisteredExecutionNode
	(*CgroupSettings_BlockIOLimits)(nil),       // 27: scheduler.CgroupSettings.BlockIOLimits
	(*GetExecutionNodesResponse_Executor)(nil), // 28: scheduler.GetExecutionNodesResponse.Executor
	(*status.Status)(nil),                      // 29: google.rpc.Status
	(*durationpb.Duration)(nil),                // 30: google.protobuf.Duration
	(*trace.Metadata)(nil),                     // 31: trace.Metadata
	(*context.RequestContext)(nil),             // 32: context.RequestContext
	(*context.ResponseContext)(nil),            // 33: context.ResponseContext
	(*acl.ACL)(nil),                            // 34: acl.ACL
	(*timestamppb.Timestamp)(nil),              // 35: google.protobuf.Timestamp
}
var file_proto_scheduler_proto_depIdxs = []int32{
	29, // 0: scheduler.LeaseTaskRequest.re_enqueue_reason:type_name -> google.rpc.Status
	5,  // 1: scheduler.TaskSize.custom_resources:type_name -> scheduler.CustomResource
	27, // 2: scheduler.CgroupSettings.block_io_limit:type_name -> scheduler.CgroupSettings.BlockIOLimits
	6,  // 3: scheduler.SchedulingMetadata.task_size:type_name -> scheduler.TaskSize
	6,  // 4: scheduler.SchedulingMetadata.default_task_size:type_name -> scheduler.TaskSize
	6,  // 5: scheduler.SchedulingMetadata.measured_task_size:type_name -> scheduler.TaskSize
	6,  // 6: scheduler.SchedulingMetadata.predicted_task_size:type_name -> scheduler.TaskSize
	6,  // 7: scheduler.SchedulingMetadata.requested_task_size:type_name -> scheduler.TaskSize
	9,  // 8: scheduler.SchedulingMetadata.routing_config:type_name -> scheduler.RoutingConfig
	7,  // 9: scheduler.SchedulingMetadata.cgroup_settings:type_name -> scheduler.CgroupSettings
	8,  // 10: scheduler.ScheduleTaskRequest.metadata:type_name -> scheduler.SchedulingMetadata
	6,  // 11: scheduler.EnqueueTaskReservationRequest.task_size:type_name -> scheduler.TaskSize
	8,  // 12: scheduler.EnqueueTaskReservationRequest.scheduling_metadata:type_name -> scheduler.SchedulingMetadata
	30, // 13: scheduler.EnqueueTaskReservationRequest.delay:type_name -> google.protobuf.Duration
	31, // 14: scheduler.EnqueueTaskReservationRequest.trace_metadata:type_name -> trace.Metadata
	23, // 15: scheduler.RegisterExecutorRequest.node:type_name -> scheduler.ExecutionNode
	30, // 16: scheduler.AskForMoreWorkResponse.delay:type_name -> google.protobuf.Duration
	17, // 17: scheduler.RegisterAndStreamWorkRequest.register_executor_request:type_name -> scheduler.RegisterExecutorRequest
	15, // 18: scheduler.RegisterAndStreamWorkRequest.enqueue_task_reservation_response:type_name -> scheduler.EnqueueTaskReservationResponse
	20, // 19: scheduler.RegisterAndStreamWorkRequest.shutting_down_request:type_name -> scheduler.ShuttingDownRequest
	18, // 20: scheduler.RegisterAndStreamWorkRequest.ask_for_more_work_request:type_name -> scheduler.AskForMoreWorkRequest
	14, // 21: scheduler.RegisterAndStreamWorkResponse.enqueue_task_reservation_request:type_name -> scheduler.EnqueueTaskReservationRequest
	19, // 22: scheduler.RegisterAndStreamWorkResponse.ask_for_more_work_response:type_name -> scheduler.AskForMoreWorkResponse
	16, // 23: scheduler.RegisterAndStreamWorkResponse.cancel_task_reservation_request:type_name -> scheduler.CancelTaskReservationRequest
	5,  // 24: scheduler.ExecutionNode.assignable_custom_resources:type_name -> scheduler.CustomResource
	32, // 25: scheduler.GetExecutionNodesRequest.request_context:type_name -> context.RequestContext
	33, // 26: scheduler.GetExecutionNodesResponse.response_context:type_name -> context.ResponseContext
	28, // 27: scheduler.GetExecutionNodesResponse.executor:type_name -> scheduler.GetExecutionNodesResponse.Executor
	23, // 28: scheduler.RegisteredExecutionNode.registration:type_name -> scheduler.ExecutionNode
	34, // 29: scheduler.RegisteredExecutionNode.acl:type_name -> acl.ACL
	35, // 30: scheduler.RegisteredExecutionNode.last_ping_time:type_name -> google.protobuf.Timestamp
	23, // 31: scheduler.GetExecutionNodesResponse.Executor.node:type_name -> scheduler.ExecutionNode
	35, // 32: scheduler.GetExecutionNodesResponse.Executor.last_check_in_time:type_name -> google.protobuf.Timestamp
	21, // 33: scheduler.Scheduler.RegisterAndStreamWork:input_type -> scheduler.RegisterAndStreamWorkRequest
	3,  // 34: scheduler.Scheduler.LeaseTask:input_type -> scheduler.LeaseTaskRequest
	1,  // 35: scheduler.Scheduler.TaskExists:input_type -> scheduler.TaskExistsRequest
	10, // 36: scheduler.Scheduler.ScheduleTask:input_type -> scheduler.ScheduleTaskRequest
	12, // 37: scheduler.Scheduler.ReEnqueueTask:input_type -> scheduler.ReEnqueueTaskRequest
	14, // 38: scheduler.Scheduler.EnqueueTaskReservation:input_type -> scheduler.EnqueueTaskReservationRequest
	22, // 39: scheduler.Scheduler.RegisterAndStreamWork:output_type -> scheduler.RegisterAndStreamWorkResponse
	4,  // 40: scheduler.Scheduler.LeaseTask:output_type -> scheduler.LeaseTaskResponse
	2,  // 41: scheduler.Scheduler.TaskExists:output_type -> scheduler.TaskExistsResponse
	11, // 42: scheduler.Scheduler.ScheduleTask:output_type -> scheduler.ScheduleTaskResponse
	13, // 43: scheduler.Scheduler.ReEnqueueTask:output_type -> scheduler.ReEnqueueTaskResponse
	15, // 44: scheduler.Scheduler.EnqueueTaskReservation:output_type -> scheduler.EnqueueTaskReservationResponse
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	file_proto_scheduler_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_scheduler_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
