// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: proto/scheduler.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduler_RegisterAndStreamWork_FullMethodName  = "/scheduler.Scheduler/RegisterAndStreamWork"
	Scheduler_LeaseTask_FullMethodName              = "/scheduler.Scheduler/LeaseTask"
	Scheduler_TaskExists_FullMethodName             = "/scheduler.Scheduler/TaskExists"
	Scheduler_ScheduleTask_FullMethodName           = "/scheduler.Scheduler/ScheduleTask"
	Scheduler_ReEnqueueTask_FullMethodName          = "/scheduler.Scheduler/ReEnqueueTask"
	Scheduler_EnqueueTaskReservation_FullMethodName = "/scheduler.Scheduler/EnqueueTaskReservation"
)

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	RegisterAndStreamWork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse], error)
	LeaseTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseTaskRequest, LeaseTaskResponse], error)
	TaskExists(ctx context.Context, in *TaskExistsRequest, opts ...grpc.CallOption) (*TaskExistsResponse, error)
	ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error)
	ReEnqueueTask(ctx context.Context, in *ReEnqueueTaskRequest, opts ...grpc.CallOption) (*ReEnqueueTaskResponse, error)
	EnqueueTaskReservation(ctx context.Context, in *EnqueueTaskReservationRequest, opts ...grpc.CallOption) (*EnqueueTaskReservationResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) RegisterAndStreamWork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scheduler_ServiceDesc.Streams[0], Scheduler_RegisterAndStreamWork_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduler_RegisterAndStreamWorkClient = grpc.BidiStreamingClient[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]

func (c *schedulerClient) LeaseTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseTaskRequest, LeaseTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scheduler_ServiceDesc.Streams[1], Scheduler_LeaseTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeaseTaskRequest, LeaseTaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduler_LeaseTaskClient = grpc.BidiStreamingClient[LeaseTaskRequest, LeaseTaskResponse]

func (c *schedulerClient) TaskExists(ctx context.Context, in *TaskExistsRequest, opts ...grpc.CallOption) (*TaskExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExistsResponse)
	err := c.cc.Invoke(ctx, Scheduler_TaskExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTaskResponse)
	err := c.cc.Invoke(ctx, Scheduler_ScheduleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ReEnqueueTask(ctx context.Context, in *ReEnqueueTaskRequest, opts ...grpc.CallOption) (*ReEnqueueTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReEnqueueTaskResponse)
	err := c.cc.Invoke(ctx, Scheduler_ReEnqueueTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) EnqueueTaskReservation(ctx context.Context, in *EnqueueTaskReservationRequest, opts ...grpc.CallOption) (*EnqueueTaskReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueTaskReservationResponse)
	err := c.cc.Invoke(ctx, Scheduler_EnqueueTaskReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations should embed UnimplementedSchedulerServer
// for forward compatibility.
type SchedulerServer interface {
	RegisterAndStreamWork(grpc.BidiStreamingServer[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]) error
	LeaseTask(grpc.BidiStreamingServer[LeaseTaskRequest, LeaseTaskResponse]) error
	TaskExists(context.Context, *TaskExistsRequest) (*TaskExistsResponse, error)
	ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error)
	ReEnqueueTask(context.Context, *ReEnqueueTaskRequest) (*ReEnqueueTaskResponse, error)
	EnqueueTaskReservation(context.Context, *EnqueueTaskReservationRequest) (*EnqueueTaskReservationResponse, error)
}

// UnimplementedSchedulerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServer struct{}

func (UnimplementedSchedulerServer) RegisterAndStreamWork(grpc.BidiStreamingServer[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterAndStreamWork not implemented")
}
func (UnimplementedSchedulerServer) LeaseTask(grpc.BidiStreamingServer[LeaseTaskRequest, LeaseTaskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method LeaseTask not implemented")
}
func (UnimplementedSchedulerServer) TaskExists(context.Context, *TaskExistsRequest) (*TaskExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskExists not implemented")
}
func (UnimplementedSchedulerServer) ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleTask not implemented")
}
func (UnimplementedSchedulerServer) ReEnqueueTask(context.Context, *ReEnqueueTaskRequest) (*ReEnqueueTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReEnqueueTask not implemented")
}
func (UnimplementedSchedulerServer) EnqueueTaskReservation(context.Context, *EnqueueTaskReservationRequest) (*EnqueueTaskReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueTaskReservation not implemented")
}
func (UnimplementedSchedulerServer) testEmbeddedByValue() {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	// If the following call pancis, it indicates UnimplementedSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_RegisterAndStreamWork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerServer).RegisterAndStreamWork(&grpc.GenericServerStream[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduler_RegisterAndStreamWorkServer = grpc.BidiStreamingServer[RegisterAndStreamWorkRequest, RegisterAndStreamWorkResponse]

func _Scheduler_LeaseTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerServer).LeaseTask(&grpc.GenericServerStream[LeaseTaskRequest, LeaseTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduler_LeaseTaskServer = grpc.BidiStreamingServer[LeaseTaskRequest, LeaseTaskResponse]

func _Scheduler_TaskExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).TaskExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_TaskExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).TaskExists(ctx, req.(*TaskExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ScheduleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScheduleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ScheduleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScheduleTask(ctx, req.(*ScheduleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ReEnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEnqueueTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ReEnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ReEnqueueTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ReEnqueueTask(ctx, req.(*ReEnqueueTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_EnqueueTaskReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueTaskReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).EnqueueTaskReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_EnqueueTaskReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).EnqueueTaskReservation(ctx, req.(*EnqueueTaskReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskExists",
			Handler:    _Scheduler_TaskExists_Handler,
		},
		{
			MethodName: "ScheduleTask",
			Handler:    _Scheduler_ScheduleTask_Handler,
		},
		{
			MethodName: "ReEnqueueTask",
			Handler:    _Scheduler_ReEnqueueTask_Handler,
		},
		{
			MethodName: "EnqueueTaskReservation",
			Handler:    _Scheduler_EnqueueTaskReservation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterAndStreamWork",
			Handler:       _Scheduler_RegisterAndStreamWork_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LeaseTask",
			Handler:       _Scheduler_LeaseTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/scheduler.proto",
}
