load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lockingbuffer",
    srcs = ["lockingbuffer.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/lockingbuffer",
    visibility = ["//visibility:public"],
)

