// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/resource.proto

package resource

import (
	remote_execution "github.com/buildbuddy-io/buildbuddy/proto/remote_execution"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheType int32

const (
	CacheType_UNKNOWN_CACHE_TYPE CacheType = 0
	CacheType_AC                 CacheType = 1
	CacheType_CAS                CacheType = 2
)

// Enum value maps for CacheType.
var (
	CacheType_name = map[int32]string{
		0: "UNKNOWN_CACHE_TYPE",
		1: "AC",
		2: "CAS",
	}
	CacheType_value = map[string]int32{
		"UNKNOWN_CACHE_TYPE": 0,
		"AC":                 1,
		"CAS":                2,
	}
)

func (x CacheType) Enum() *CacheType {
	p := new(CacheType)
	*p = x
	return p
}

func (x CacheType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resource_proto_enumTypes[0].Descriptor()
}

func (CacheType) Type() protoreflect.EnumType {
	return &file_proto_resource_proto_enumTypes[0]
}

func (x CacheType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheType.Descriptor instead.
func (CacheType) EnumDescriptor() ([]byte, []int) {
	return file_proto_resource_proto_rawDescGZIP(), []int{0}
}

type ResourceName struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	Digest         *remote_execution.Digest              `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	InstanceName   string                                `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Compressor     remote_execution.Compressor_Value     `protobuf:"varint,3,opt,name=compressor,proto3,enum=build.bazel.remote.execution.v2.Compressor_Value" json:"compressor,omitempty"`
	CacheType      CacheType                             `protobuf:"varint,4,opt,name=cache_type,json=cacheType,proto3,enum=resource.CacheType" json:"cache_type,omitempty"`
	DigestFunction remote_execution.DigestFunction_Value `protobuf:"varint,5,opt,name=digest_function,json=digestFunction,proto3,enum=build.bazel.remote.execution.v2.DigestFunction_Value" json:"digest_function,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceName) Reset() {
	*x = ResourceName{}
	mi := &file_proto_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceName) ProtoMessage() {}

func (x *ResourceName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceName.ProtoReflect.Descriptor instead.
func (*ResourceName) Descriptor() ([]byte, []int) {
	return file_proto_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceName) GetDigest() *remote_execution.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ResourceName) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ResourceName) GetCompressor() remote_execution.Compressor_Value {
	if x != nil {
		return x.Compressor
	}
	return remote_execution.Compressor_Value(0)
}

func (x *ResourceName) GetCacheType() CacheType {
	if x != nil {
		return x.CacheType
	}
	return CacheType_UNKNOWN_CACHE_TYPE
}

func (x *ResourceName) GetDigestFunction() remote_execution.DigestFunction_Value {
	if x != nil {
		return x.DigestFunction
	}
	return remote_execution.DigestFunction_Value(0)
}

var File_proto_resource_proto protoreflect.FileDescriptor

const file_proto_resource_proto_rawDesc = "" +
	"\n" +
	"\x14proto/resource.proto\x12\bresource\x1a\x1cproto/remote_execution.proto\"\xdb\x02\n" +
	"\fResourceName\x12?\n" +
	"\x06digest\x18\x01 \x01(\v2'.build.bazel.remote.execution.v2.DigestR\x06digest\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12Q\n" +
	"\n" +
	"compressor\x18\x03 \x01(\x0e21.build.bazel.remote.execution.v2.Compressor.ValueR\n" +
	"compressor\x122\n" +
	"\n" +
	"cache_type\x18\x04 \x01(\x0e2\x13.resource.CacheTypeR\tcacheType\x12^\n" +
	"\x0fdigest_function\x18\x05 \x01(\x0e25.build.bazel.remote.execution.v2.DigestFunction.ValueR\x0edigestFunction*4\n" +
	"\tCacheType\x12\x16\n" +
	"\x12UNKNOWN_CACHE_TYPE\x10\x00\x12\x06\n" +
	"\x02AC\x10\x01\x12\a\n" +
	"\x03CAS\x10\x02b\x06proto3"

var (
	file_proto_resource_proto_rawDescOnce sync.Once
	file_proto_resource_proto_rawDescData []byte
)

func file_proto_resource_proto_rawDescGZIP() []byte {
	file_proto_resource_proto_rawDescOnce.Do(func() {
		file_proto_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resource_proto_rawDesc), len(file_proto_resource_proto_rawDesc)))
	})
	return file_proto_resource_proto_rawDescData
}

var file_proto_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_resource_proto_goTypes = []any{
	(CacheType)(0),                             // 0: resource.CacheType
	(*ResourceName)(nil),                       // 1: resource.ResourceName
	(*remote_execution.Digest)(nil),            // 2: build.bazel.remote.execution.v2.Digest
	(remote_execution.Compressor_Value)(0),     // 3: build.bazel.remote.execution.v2.Compressor.Value
	(remote_execution.DigestFunction_Value)(0), // 4: build.bazel.remote.execution.v2.DigestFunction.Value
}
var file_proto_resource_proto_depIdxs = []int32{
	2, // 0: resource.ResourceName.digest:type_name -> build.bazel.remote.execution.v2.Digest
	3, // 1: resource.ResourceName.compressor:type_name -> build.bazel.remote.execution.v2.Compressor.Value
	0, // 2: resource.ResourceName.cache_type:type_name -> resource.CacheType
	4, // 3: resource.ResourceName.digest_function:type_name -> build.bazel.remote.execution.v2.DigestFunction.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_resource_proto_init() }
func file_proto_resource_proto_init() {
	if File_proto_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resource_proto_rawDesc), len(file_proto_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_resource_proto_goTypes,
		DependencyIndexes: file_proto_resource_proto_depIdxs,
		EnumInfos:         file_proto_resource_proto_enumTypes,
		MessageInfos:      file_proto_resource_proto_msgTypes,
	}.Build()
	File_proto_resource_proto = out.File
	file_proto_resource_proto_goTypes = nil
	file_proto_resource_proto_depIdxs = nil
}
