// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/api/v1/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_BUILDING           Status = 1
	Status_BUILT              Status = 2
	Status_FAILED_TO_BUILD    Status = 3
	Status_TESTING            Status = 4
	Status_PASSED             Status = 5
	Status_FAILED             Status = 6
	Status_TIMED_OUT          Status = 7
	Status_CANCELLED          Status = 8
	Status_TOOL_FAILED        Status = 9
	Status_INCOMPLETE         Status = 10
	Status_FLAKY              Status = 11
	Status_UNKNOWN            Status = 12
	Status_SKIPPED            Status = 13
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:  "STATUS_UNSPECIFIED",
		1:  "BUILDING",
		2:  "BUILT",
		3:  "FAILED_TO_BUILD",
		4:  "TESTING",
		5:  "PASSED",
		6:  "FAILED",
		7:  "TIMED_OUT",
		8:  "CANCELLED",
		9:  "TOOL_FAILED",
		10: "INCOMPLETE",
		11: "FLAKY",
		12: "UNKNOWN",
		13: "SKIPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"BUILDING":           1,
		"BUILT":              2,
		"FAILED_TO_BUILD":    3,
		"TESTING":            4,
		"PASSED":             5,
		"FAILED":             6,
		"TIMED_OUT":          7,
		"CANCELLED":          8,
		"TOOL_FAILED":        9,
		"INCOMPLETE":         10,
		"FLAKY":              11,
		"UNKNOWN":            12,
		"SKIPPED":            13,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_api_v1_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_common_proto_rawDescGZIP(), []int{0}
}

type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_APPLICATION             TargetType = 1
	TargetType_BINARY                  TargetType = 2
	TargetType_LIBRARY                 TargetType = 3
	TargetType_PACKAGE                 TargetType = 4
	TargetType_TEST                    TargetType = 5
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "APPLICATION",
		2: "BINARY",
		3: "LIBRARY",
		4: "PACKAGE",
		5: "TEST",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"APPLICATION":             1,
		"BINARY":                  2,
		"LIBRARY":                 3,
		"PACKAGE":                 4,
		"TEST":                    5,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_common_proto_enumTypes[1].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_proto_api_v1_common_proto_enumTypes[1]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_common_proto_rawDescGZIP(), []int{1}
}

type TestSize int32

const (
	TestSize_TEST_SIZE_UNSPECIFIED TestSize = 0
	TestSize_SMALL                 TestSize = 1
	TestSize_MEDIUM                TestSize = 2
	TestSize_LARGE                 TestSize = 3
	TestSize_ENORMOUS              TestSize = 4
	TestSize_OTHER_SIZE            TestSize = 5
)

// Enum value maps for TestSize.
var (
	TestSize_name = map[int32]string{
		0: "TEST_SIZE_UNSPECIFIED",
		1: "SMALL",
		2: "MEDIUM",
		3: "LARGE",
		4: "ENORMOUS",
		5: "OTHER_SIZE",
	}
	TestSize_value = map[string]int32{
		"TEST_SIZE_UNSPECIFIED": 0,
		"SMALL":                 1,
		"MEDIUM":                2,
		"LARGE":                 3,
		"ENORMOUS":              4,
		"OTHER_SIZE":            5,
	}
)

func (x TestSize) Enum() *TestSize {
	p := new(TestSize)
	*p = x
	return p
}

func (x TestSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestSize) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_common_proto_enumTypes[2].Descriptor()
}

func (TestSize) Type() protoreflect.EnumType {
	return &file_proto_api_v1_common_proto_enumTypes[2]
}

func (x TestSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestSize.Descriptor instead.
func (TestSize) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_common_proto_rawDescGZIP(), []int{2}
}

type Timing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timing) Reset() {
	*x = Timing{}
	mi := &file_proto_api_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timing) ProtoMessage() {}

func (x *Timing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timing.ProtoReflect.Descriptor instead.
func (*Timing) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Timing) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Timing) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_proto_api_v1_common_proto protoreflect.FileDescriptor

const file_proto_api_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/api/v1/common.proto\x12\x06api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\x06Timing\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration*\xd7\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bBUILDING\x10\x01\x12\t\n" +
	"\x05BUILT\x10\x02\x12\x13\n" +
	"\x0fFAILED_TO_BUILD\x10\x03\x12\v\n" +
	"\aTESTING\x10\x04\x12\n" +
	"\n" +
	"\x06PASSED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\x12\r\n" +
	"\tTIMED_OUT\x10\a\x12\r\n" +
	"\tCANCELLED\x10\b\x12\x0f\n" +
	"\vTOOL_FAILED\x10\t\x12\x0e\n" +
	"\n" +
	"INCOMPLETE\x10\n" +
	"\x12\t\n" +
	"\x05FLAKY\x10\v\x12\v\n" +
	"\aUNKNOWN\x10\f\x12\v\n" +
	"\aSKIPPED\x10\r*j\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vAPPLICATION\x10\x01\x12\n" +
	"\n" +
	"\x06BINARY\x10\x02\x12\v\n" +
	"\aLIBRARY\x10\x03\x12\v\n" +
	"\aPACKAGE\x10\x04\x12\b\n" +
	"\x04TEST\x10\x05*e\n" +
	"\bTestSize\x12\x19\n" +
	"\x15TEST_SIZE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05SMALL\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\t\n" +
	"\x05LARGE\x10\x03\x12\f\n" +
	"\bENORMOUS\x10\x04\x12\x0e\n" +
	"\n" +
	"OTHER_SIZE\x10\x05b\x06proto3"

var (
	file_proto_api_v1_common_proto_rawDescOnce sync.Once
	file_proto_api_v1_common_proto_rawDescData []byte
)

func file_proto_api_v1_common_proto_rawDescGZIP() []byte {
	file_proto_api_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_common_proto_rawDesc), len(file_proto_api_v1_common_proto_rawDesc)))
	})
	return file_proto_api_v1_common_proto_rawDescData
}

var file_proto_api_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_api_v1_common_proto_goTypes = []any{
	(Status)(0),                   // 0: api.v1.Status
	(TargetType)(0),               // 1: api.v1.TargetType
	(TestSize)(0),                 // 2: api.v1.TestSize
	(*Timing)(nil),                // 3: api.v1.Timing
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
}
var file_proto_api_v1_common_proto_depIdxs = []int32{
	4, // 0: api.v1.Timing.start_time:type_name -> google.protobuf.Timestamp
	5, // 1: api.v1.Timing.duration:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_api_v1_common_proto_init() }
func file_proto_api_v1_common_proto_init() {
	if File_proto_api_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_common_proto_rawDesc), len(file_proto_api_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_common_proto_msgTypes,
	}.Build()
	File_proto_api_v1_common_proto = out.File
	file_proto_api_v1_common_proto_goTypes = nil
	file_proto_api_v1_common_proto_depIdxs = nil
}
