// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/invocation_status.proto

package invocation_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverallStatus int32

const (
	OverallStatus_UNKNOWN_OVERALL_STATUS OverallStatus = 0
	OverallStatus_SUCCESS                OverallStatus = 1
	OverallStatus_FAILURE                OverallStatus = 2
	OverallStatus_IN_PROGRESS            OverallStatus = 3
	OverallStatus_DISCONNECTED           OverallStatus = 4
)

// Enum value maps for OverallStatus.
var (
	OverallStatus_name = map[int32]string{
		0: "UNKNOWN_OVERALL_STATUS",
		1: "SUCCESS",
		2: "FAILURE",
		3: "IN_PROGRESS",
		4: "DISCONNECTED",
	}
	OverallStatus_value = map[string]int32{
		"UNKNOWN_OVERALL_STATUS": 0,
		"SUCCESS":                1,
		"FAILURE":                2,
		"IN_PROGRESS":            3,
		"DISCONNECTED":           4,
	}
)

func (x OverallStatus) Enum() *OverallStatus {
	p := new(OverallStatus)
	*p = x
	return p
}

func (x OverallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_status_proto_enumTypes[0].Descriptor()
}

func (OverallStatus) Type() protoreflect.EnumType {
	return &file_proto_invocation_status_proto_enumTypes[0]
}

func (x OverallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverallStatus.Descriptor instead.
func (OverallStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_status_proto_rawDescGZIP(), []int{0}
}

type InvocationStatus int32

const (
	InvocationStatus_UNKNOWN_INVOCATION_STATUS      InvocationStatus = 0
	InvocationStatus_COMPLETE_INVOCATION_STATUS     InvocationStatus = 1
	InvocationStatus_PARTIAL_INVOCATION_STATUS      InvocationStatus = 2
	InvocationStatus_DISCONNECTED_INVOCATION_STATUS InvocationStatus = 3
)

// Enum value maps for InvocationStatus.
var (
	InvocationStatus_name = map[int32]string{
		0: "UNKNOWN_INVOCATION_STATUS",
		1: "COMPLETE_INVOCATION_STATUS",
		2: "PARTIAL_INVOCATION_STATUS",
		3: "DISCONNECTED_INVOCATION_STATUS",
	}
	InvocationStatus_value = map[string]int32{
		"UNKNOWN_INVOCATION_STATUS":      0,
		"COMPLETE_INVOCATION_STATUS":     1,
		"PARTIAL_INVOCATION_STATUS":      2,
		"DISCONNECTED_INVOCATION_STATUS": 3,
	}
)

func (x InvocationStatus) Enum() *InvocationStatus {
	p := new(InvocationStatus)
	*p = x
	return p
}

func (x InvocationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_status_proto_enumTypes[1].Descriptor()
}

func (InvocationStatus) Type() protoreflect.EnumType {
	return &file_proto_invocation_status_proto_enumTypes[1]
}

func (x InvocationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationStatus.Descriptor instead.
func (InvocationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_status_proto_rawDescGZIP(), []int{1}
}

var File_proto_invocation_status_proto protoreflect.FileDescriptor

const file_proto_invocation_status_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/invocation_status.proto\x12\x11invocation_status*h\n" +
	"\rOverallStatus\x12\x1a\n" +
	"\x16UNKNOWN_OVERALL_STATUS\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x03\x12\x10\n" +
	"\fDISCONNECTED\x10\x04*\x94\x01\n" +
	"\x10InvocationStatus\x12\x1d\n" +
	"\x19UNKNOWN_INVOCATION_STATUS\x10\x00\x12\x1e\n" +
	"\x1aCOMPLETE_INVOCATION_STATUS\x10\x01\x12\x1d\n" +
	"\x19PARTIAL_INVOCATION_STATUS\x10\x02\x12\"\n" +
	"\x1eDISCONNECTED_INVOCATION_STATUS\x10\x03b\x06proto3"

var (
	file_proto_invocation_status_proto_rawDescOnce sync.Once
	file_proto_invocation_status_proto_rawDescData []byte
)

func file_proto_invocation_status_proto_rawDescGZIP() []byte {
	file_proto_invocation_status_proto_rawDescOnce.Do(func() {
		file_proto_invocation_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_invocation_status_proto_rawDesc), len(file_proto_invocation_status_proto_rawDesc)))
	})
	return file_proto_invocation_status_proto_rawDescData
}

var file_proto_invocation_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_invocation_status_proto_goTypes = []any{
	(OverallStatus)(0),    // 0: invocation_status.OverallStatus
	(InvocationStatus)(0), // 1: invocation_status.InvocationStatus
}
var file_proto_invocation_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_invocation_status_proto_init() }
func file_proto_invocation_status_proto_init() {
	if File_proto_invocation_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_invocation_status_proto_rawDesc), len(file_proto_invocation_status_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_invocation_status_proto_goTypes,
		DependencyIndexes: file_proto_invocation_status_proto_depIdxs,
		EnumInfos:         file_proto_invocation_status_proto_enumTypes,
	}.Build()
	File_proto_invocation_status_proto = out.File
	file_proto_invocation_status_proto_goTypes = nil
	file_proto_invocation_status_proto_depIdxs = nil
}
