// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/invocation.proto

package invocation

import (
	acl "github.com/buildbuddy-io/buildbuddy/proto/acl"
	build_event_stream "github.com/buildbuddy-io/buildbuddy/proto/build_event_stream"
	cache "github.com/buildbuddy-io/buildbuddy/proto/cache"
	capability "github.com/buildbuddy-io/buildbuddy/proto/capability"
	command_line "github.com/buildbuddy-io/buildbuddy/proto/command_line"
	context "github.com/buildbuddy-io/buildbuddy/proto/context"
	invocation_status "github.com/buildbuddy-io/buildbuddy/proto/invocation_status"
	stat_filter "github.com/buildbuddy-io/buildbuddy/proto/stat_filter"
	target "github.com/buildbuddy-io/buildbuddy/proto/target"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadOutputsOption int32

const (
	DownloadOutputsOption_UNKNOWN_DOWNLOAD_OUTPUTS_OPTION DownloadOutputsOption = 0
	DownloadOutputsOption_NONE                            DownloadOutputsOption = 1
	DownloadOutputsOption_ALL                             DownloadOutputsOption = 2
	DownloadOutputsOption_TOP_LEVEL                       DownloadOutputsOption = 3
	DownloadOutputsOption_MINIMAL                         DownloadOutputsOption = 4
)

// Enum value maps for DownloadOutputsOption.
var (
	DownloadOutputsOption_name = map[int32]string{
		0: "UNKNOWN_DOWNLOAD_OUTPUTS_OPTION",
		1: "NONE",
		2: "ALL",
		3: "TOP_LEVEL",
		4: "MINIMAL",
	}
	DownloadOutputsOption_value = map[string]int32{
		"UNKNOWN_DOWNLOAD_OUTPUTS_OPTION": 0,
		"NONE":                            1,
		"ALL":                             2,
		"TOP_LEVEL":                       3,
		"MINIMAL":                         4,
	}
)

func (x DownloadOutputsOption) Enum() *DownloadOutputsOption {
	p := new(DownloadOutputsOption)
	*p = x
	return p
}

func (x DownloadOutputsOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadOutputsOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_proto_enumTypes[0].Descriptor()
}

func (DownloadOutputsOption) Type() protoreflect.EnumType {
	return &file_proto_invocation_proto_enumTypes[0]
}

func (x DownloadOutputsOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadOutputsOption.Descriptor instead.
func (DownloadOutputsOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{0}
}

type InvocationPermission int32

const (
	InvocationPermission_UNKNOWN_PERMISSION InvocationPermission = 0
	InvocationPermission_OWNER              InvocationPermission = 1
	InvocationPermission_GROUP              InvocationPermission = 2
	InvocationPermission_PUBLIC             InvocationPermission = 3
)

// Enum value maps for InvocationPermission.
var (
	InvocationPermission_name = map[int32]string{
		0: "UNKNOWN_PERMISSION",
		1: "OWNER",
		2: "GROUP",
		3: "PUBLIC",
	}
	InvocationPermission_value = map[string]int32{
		"UNKNOWN_PERMISSION": 0,
		"OWNER":              1,
		"GROUP":              2,
		"PUBLIC":             3,
	}
)

func (x InvocationPermission) Enum() *InvocationPermission {
	p := new(InvocationPermission)
	*p = x
	return p
}

func (x InvocationPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_proto_enumTypes[1].Descriptor()
}

func (InvocationPermission) Type() protoreflect.EnumType {
	return &file_proto_invocation_proto_enumTypes[1]
}

func (x InvocationPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationPermission.Descriptor instead.
func (InvocationPermission) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{1}
}

type AggType int32

const (
	AggType_UNKNOWN_AGGREGATION_TYPE    AggType = 0
	AggType_USER_AGGREGATION_TYPE       AggType = 1
	AggType_HOSTNAME_AGGREGATION_TYPE   AggType = 2
	AggType_GROUP_ID_AGGREGATION_TYPE   AggType = 3
	AggType_REPO_URL_AGGREGATION_TYPE   AggType = 4
	AggType_COMMIT_SHA_AGGREGATION_TYPE AggType = 5
	AggType_DATE_AGGREGATION_TYPE       AggType = 6
	AggType_BRANCH_AGGREGATION_TYPE     AggType = 7
	AggType_PATTERN_AGGREGATION_TYPE    AggType = 8
)

// Enum value maps for AggType.
var (
	AggType_name = map[int32]string{
		0: "UNKNOWN_AGGREGATION_TYPE",
		1: "USER_AGGREGATION_TYPE",
		2: "HOSTNAME_AGGREGATION_TYPE",
		3: "GROUP_ID_AGGREGATION_TYPE",
		4: "REPO_URL_AGGREGATION_TYPE",
		5: "COMMIT_SHA_AGGREGATION_TYPE",
		6: "DATE_AGGREGATION_TYPE",
		7: "BRANCH_AGGREGATION_TYPE",
		8: "PATTERN_AGGREGATION_TYPE",
	}
	AggType_value = map[string]int32{
		"UNKNOWN_AGGREGATION_TYPE":    0,
		"USER_AGGREGATION_TYPE":       1,
		"HOSTNAME_AGGREGATION_TYPE":   2,
		"GROUP_ID_AGGREGATION_TYPE":   3,
		"REPO_URL_AGGREGATION_TYPE":   4,
		"COMMIT_SHA_AGGREGATION_TYPE": 5,
		"DATE_AGGREGATION_TYPE":       6,
		"BRANCH_AGGREGATION_TYPE":     7,
		"PATTERN_AGGREGATION_TYPE":    8,
	}
)

func (x AggType) Enum() *AggType {
	p := new(AggType)
	*p = x
	return p
}

func (x AggType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_proto_enumTypes[2].Descriptor()
}

func (AggType) Type() protoreflect.EnumType {
	return &file_proto_invocation_proto_enumTypes[2]
}

func (x AggType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggType.Descriptor instead.
func (AggType) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{2}
}

type InvocationSort_SortField int32

const (
	InvocationSort_UNKNOWN_SORT_FIELD                                   InvocationSort_SortField = 0
	InvocationSort_CREATED_AT_USEC_SORT_FIELD                           InvocationSort_SortField = 1
	InvocationSort_UPDATED_AT_USEC_SORT_FIELD                           InvocationSort_SortField = 2
	InvocationSort_DURATION_SORT_FIELD                                  InvocationSort_SortField = 3
	InvocationSort_ACTION_CACHE_HIT_RATIO_SORT_FIELD                    InvocationSort_SortField = 4
	InvocationSort_CONTENT_ADDRESSABLE_STORE_CACHE_HIT_RATIO_SORT_FIELD InvocationSort_SortField = 5
	InvocationSort_CACHE_DOWNLOADED_SORT_FIELD                          InvocationSort_SortField = 6
	InvocationSort_CACHE_UPLOADED_SORT_FIELD                            InvocationSort_SortField = 7
	InvocationSort_CACHE_TRANSFERRED_SORT_FIELD                         InvocationSort_SortField = 8
)

// Enum value maps for InvocationSort_SortField.
var (
	InvocationSort_SortField_name = map[int32]string{
		0: "UNKNOWN_SORT_FIELD",
		1: "CREATED_AT_USEC_SORT_FIELD",
		2: "UPDATED_AT_USEC_SORT_FIELD",
		3: "DURATION_SORT_FIELD",
		4: "ACTION_CACHE_HIT_RATIO_SORT_FIELD",
		5: "CONTENT_ADDRESSABLE_STORE_CACHE_HIT_RATIO_SORT_FIELD",
		6: "CACHE_DOWNLOADED_SORT_FIELD",
		7: "CACHE_UPLOADED_SORT_FIELD",
		8: "CACHE_TRANSFERRED_SORT_FIELD",
	}
	InvocationSort_SortField_value = map[string]int32{
		"UNKNOWN_SORT_FIELD":                                   0,
		"CREATED_AT_USEC_SORT_FIELD":                           1,
		"UPDATED_AT_USEC_SORT_FIELD":                           2,
		"DURATION_SORT_FIELD":                                  3,
		"ACTION_CACHE_HIT_RATIO_SORT_FIELD":                    4,
		"CONTENT_ADDRESSABLE_STORE_CACHE_HIT_RATIO_SORT_FIELD": 5,
		"CACHE_DOWNLOADED_SORT_FIELD":                          6,
		"CACHE_UPLOADED_SORT_FIELD":                            7,
		"CACHE_TRANSFERRED_SORT_FIELD":                         8,
	}
)

func (x InvocationSort_SortField) Enum() *InvocationSort_SortField {
	p := new(InvocationSort_SortField)
	*p = x
	return p
}

func (x InvocationSort_SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationSort_SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invocation_proto_enumTypes[3].Descriptor()
}

func (InvocationSort_SortField) Type() protoreflect.EnumType {
	return &file_proto_invocation_proto_enumTypes[3]
}

func (x InvocationSort_SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationSort_SortField.Descriptor instead.
func (InvocationSort_SortField) EnumDescriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{14, 0}
}

type Invocation struct {
	state                     protoimpl.MessageState             `protogen:"open.v1"`
	InvocationId              string                             `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Event                     []*InvocationEvent                 `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
	Success                   bool                               `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	User                      string                             `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	DurationUsec              int64                              `protobuf:"varint,5,opt,name=duration_usec,json=durationUsec,proto3" json:"duration_usec,omitempty"`
	Host                      string                             `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	Command                   string                             `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`
	Pattern                   []string                           `protobuf:"bytes,8,rep,name=pattern,proto3" json:"pattern,omitempty"`
	ActionCount               int64                              `protobuf:"varint,9,opt,name=action_count,json=actionCount,proto3" json:"action_count,omitempty"`
	InvocationStatus          invocation_status.InvocationStatus `protobuf:"varint,10,opt,name=invocation_status,json=invocationStatus,proto3,enum=invocation_status.InvocationStatus" json:"invocation_status,omitempty"`
	ConsoleBuffer             string                             `protobuf:"bytes,11,opt,name=console_buffer,json=consoleBuffer,proto3" json:"console_buffer,omitempty"`
	StructuredCommandLine     []*command_line.CommandLine        `protobuf:"bytes,12,rep,name=structured_command_line,json=structuredCommandLine,proto3" json:"structured_command_line,omitempty"`
	CreatedAtUsec             int64                              `protobuf:"varint,13,opt,name=created_at_usec,json=createdAtUsec,proto3" json:"created_at_usec,omitempty"`
	UpdatedAtUsec             int64                              `protobuf:"varint,14,opt,name=updated_at_usec,json=updatedAtUsec,proto3" json:"updated_at_usec,omitempty"`
	RepoUrl                   string                             `protobuf:"bytes,15,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	CommitSha                 string                             `protobuf:"bytes,16,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	ReadPermission            InvocationPermission               `protobuf:"varint,17,opt,name=read_permission,json=readPermission,proto3,enum=invocation.InvocationPermission" json:"read_permission,omitempty"`
	CacheStats                *cache.CacheStats                  `protobuf:"bytes,18,opt,name=cache_stats,json=cacheStats,proto3" json:"cache_stats,omitempty"`
	ScoreCard                 *cache.ScoreCard                   `protobuf:"bytes,24,opt,name=score_card,json=scoreCard,proto3" json:"score_card,omitempty"`
	Role                      string                             `protobuf:"bytes,19,opt,name=role,proto3" json:"role,omitempty"`
	Acl                       *acl.ACL                           `protobuf:"bytes,20,opt,name=acl,proto3" json:"acl,omitempty"`
	LastChunkId               string                             `protobuf:"bytes,21,opt,name=last_chunk_id,json=lastChunkId,proto3" json:"last_chunk_id,omitempty"`
	HasChunkedEventLogs       bool                               `protobuf:"varint,22,opt,name=has_chunked_event_logs,json=hasChunkedEventLogs,proto3" json:"has_chunked_event_logs,omitempty"`
	BranchName                string                             `protobuf:"bytes,23,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Attempt                   uint64                             `protobuf:"varint,25,opt,name=attempt,proto3" json:"attempt,omitempty"`
	BazelExitCode             string                             `protobuf:"bytes,26,opt,name=bazel_exit_code,json=bazelExitCode,proto3" json:"bazel_exit_code,omitempty"`
	CreatedWithCapabilities   []capability.Capability            `protobuf:"varint,27,rep,packed,name=created_with_capabilities,json=createdWithCapabilities,proto3,enum=capability.Capability" json:"created_with_capabilities,omitempty"`
	DownloadOutputsOption     DownloadOutputsOption              `protobuf:"varint,28,opt,name=download_outputs_option,json=downloadOutputsOption,proto3,enum=invocation.DownloadOutputsOption" json:"download_outputs_option,omitempty"`
	UploadLocalResultsEnabled bool                               `protobuf:"varint,29,opt,name=upload_local_results_enabled,json=uploadLocalResultsEnabled,proto3" json:"upload_local_results_enabled,omitempty"`
	RemoteExecutionEnabled    bool                               `protobuf:"varint,30,opt,name=remote_execution_enabled,json=remoteExecutionEnabled,proto3" json:"remote_execution_enabled,omitempty"`
	Tags                      []*Invocation_Tag                  `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty"`
	TargetGroups              []*target.TargetGroup              `protobuf:"bytes,32,rep,name=target_groups,json=targetGroups,proto3" json:"target_groups,omitempty"`
	PatternsTruncated         bool                               `protobuf:"varint,33,opt,name=patterns_truncated,json=patternsTruncated,proto3" json:"patterns_truncated,omitempty"`
	TargetConfiguredCount     int64                              `protobuf:"varint,34,opt,name=target_configured_count,json=targetConfiguredCount,proto3" json:"target_configured_count,omitempty"`
	ChildInvocations          []*Invocation                      `protobuf:"bytes,36,rep,name=child_invocations,json=childInvocations,proto3" json:"child_invocations,omitempty"`
	RunId                     string                             `protobuf:"bytes,37,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ParentRunId               string                             `protobuf:"bytes,38,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	// Deprecated: Marked as deprecated in proto/invocation.proto.
	ParentInvocationId string                          `protobuf:"bytes,35,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	RunStatus          invocation_status.OverallStatus `protobuf:"varint,39,opt,name=run_status,json=runStatus,proto3,enum=invocation_status.OverallStatus" json:"run_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Invocation) Reset() {
	*x = Invocation{}
	mi := &file_proto_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation) ProtoMessage() {}

func (x *Invocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation.ProtoReflect.Descriptor instead.
func (*Invocation) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *Invocation) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Invocation) GetEvent() []*InvocationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Invocation) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Invocation) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Invocation) GetDurationUsec() int64 {
	if x != nil {
		return x.DurationUsec
	}
	return 0
}

func (x *Invocation) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Invocation) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Invocation) GetPattern() []string {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *Invocation) GetActionCount() int64 {
	if x != nil {
		return x.ActionCount
	}
	return 0
}

func (x *Invocation) GetInvocationStatus() invocation_status.InvocationStatus {
	if x != nil {
		return x.InvocationStatus
	}
	return invocation_status.InvocationStatus(0)
}

func (x *Invocation) GetConsoleBuffer() string {
	if x != nil {
		return x.ConsoleBuffer
	}
	return ""
}

func (x *Invocation) GetStructuredCommandLine() []*command_line.CommandLine {
	if x != nil {
		return x.StructuredCommandLine
	}
	return nil
}

func (x *Invocation) GetCreatedAtUsec() int64 {
	if x != nil {
		return x.CreatedAtUsec
	}
	return 0
}

func (x *Invocation) GetUpdatedAtUsec() int64 {
	if x != nil {
		return x.UpdatedAtUsec
	}
	return 0
}

func (x *Invocation) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Invocation) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Invocation) GetReadPermission() InvocationPermission {
	if x != nil {
		return x.ReadPermission
	}
	return InvocationPermission_UNKNOWN_PERMISSION
}

func (x *Invocation) GetCacheStats() *cache.CacheStats {
	if x != nil {
		return x.CacheStats
	}
	return nil
}

func (x *Invocation) GetScoreCard() *cache.ScoreCard {
	if x != nil {
		return x.ScoreCard
	}
	return nil
}

func (x *Invocation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Invocation) GetAcl() *acl.ACL {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *Invocation) GetLastChunkId() string {
	if x != nil {
		return x.LastChunkId
	}
	return ""
}

func (x *Invocation) GetHasChunkedEventLogs() bool {
	if x != nil {
		return x.HasChunkedEventLogs
	}
	return false
}

func (x *Invocation) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Invocation) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Invocation) GetBazelExitCode() string {
	if x != nil {
		return x.BazelExitCode
	}
	return ""
}

func (x *Invocation) GetCreatedWithCapabilities() []capability.Capability {
	if x != nil {
		return x.CreatedWithCapabilities
	}
	return nil
}

func (x *Invocation) GetDownloadOutputsOption() DownloadOutputsOption {
	if x != nil {
		return x.DownloadOutputsOption
	}
	return DownloadOutputsOption_UNKNOWN_DOWNLOAD_OUTPUTS_OPTION
}

func (x *Invocation) GetUploadLocalResultsEnabled() bool {
	if x != nil {
		return x.UploadLocalResultsEnabled
	}
	return false
}

func (x *Invocation) GetRemoteExecutionEnabled() bool {
	if x != nil {
		return x.RemoteExecutionEnabled
	}
	return false
}

func (x *Invocation) GetTags() []*Invocation_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Invocation) GetTargetGroups() []*target.TargetGroup {
	if x != nil {
		return x.TargetGroups
	}
	return nil
}

func (x *Invocation) GetPatternsTruncated() bool {
	if x != nil {
		return x.PatternsTruncated
	}
	return false
}

func (x *Invocation) GetTargetConfiguredCount() int64 {
	if x != nil {
		return x.TargetConfiguredCount
	}
	return 0
}

func (x *Invocation) GetChildInvocations() []*Invocation {
	if x != nil {
		return x.ChildInvocations
	}
	return nil
}

func (x *Invocation) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Invocation) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/invocation.proto.
func (x *Invocation) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

func (x *Invocation) GetRunStatus() invocation_status.OverallStatus {
	if x != nil {
		return x.RunStatus
	}
	return invocation_status.OverallStatus(0)
}

type InvocationEvent struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	EventTime      *timestamppb.Timestamp         `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	BuildEvent     *build_event_stream.BuildEvent `protobuf:"bytes,2,opt,name=build_event,json=buildEvent,proto3" json:"build_event,omitempty"`
	SequenceNumber int64                          `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvocationEvent) Reset() {
	*x = InvocationEvent{}
	mi := &file_proto_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationEvent) ProtoMessage() {}

func (x *InvocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationEvent.ProtoReflect.Descriptor instead.
func (*InvocationEvent) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *InvocationEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *InvocationEvent) GetBuildEvent() *build_event_stream.BuildEvent {
	if x != nil {
		return x.BuildEvent
	}
	return nil
}

func (x *InvocationEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type InvocationLookup struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	InvocationId          string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	FetchChildInvocations bool                   `protobuf:"varint,2,opt,name=fetch_child_invocations,json=fetchChildInvocations,proto3" json:"fetch_child_invocations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InvocationLookup) Reset() {
	*x = InvocationLookup{}
	mi := &file_proto_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationLookup) ProtoMessage() {}

func (x *InvocationLookup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationLookup.ProtoReflect.Descriptor instead.
func (*InvocationLookup) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *InvocationLookup) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvocationLookup) GetFetchChildInvocations() bool {
	if x != nil {
		return x.FetchChildInvocations
	}
	return false
}

type GetInvocationRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	Lookup         *InvocationLookup       `protobuf:"bytes,2,opt,name=lookup,proto3" json:"lookup,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInvocationRequest) Reset() {
	*x = GetInvocationRequest{}
	mi := &file_proto_invocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationRequest) ProtoMessage() {}

func (x *GetInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationRequest.ProtoReflect.Descriptor instead.
func (*GetInvocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvocationRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetInvocationRequest) GetLookup() *InvocationLookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

type GetInvocationResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	Invocation      []*Invocation            `protobuf:"bytes,2,rep,name=invocation,proto3" json:"invocation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInvocationResponse) Reset() {
	*x = GetInvocationResponse{}
	mi := &file_proto_invocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationResponse) ProtoMessage() {}

func (x *GetInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationResponse.ProtoReflect.Descriptor instead.
func (*GetInvocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvocationResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *GetInvocationResponse) GetInvocation() []*Invocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

type GetInvocationOwnerRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	InvocationId   string                  `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInvocationOwnerRequest) Reset() {
	*x = GetInvocationOwnerRequest{}
	mi := &file_proto_invocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationOwnerRequest) ProtoMessage() {}

func (x *GetInvocationOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetInvocationOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvocationOwnerRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetInvocationOwnerRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

type GetInvocationOwnerResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	GroupId         string                   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupUrl        string                   `protobuf:"bytes,3,opt,name=group_url,json=groupUrl,proto3" json:"group_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInvocationOwnerResponse) Reset() {
	*x = GetInvocationOwnerResponse{}
	mi := &file_proto_invocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationOwnerResponse) ProtoMessage() {}

func (x *GetInvocationOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetInvocationOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvocationOwnerResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *GetInvocationOwnerResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetInvocationOwnerResponse) GetGroupUrl() string {
	if x != nil {
		return x.GroupUrl
	}
	return ""
}

type UpdateInvocationRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	InvocationId   string                  `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Acl            *acl.ACL                `protobuf:"bytes,3,opt,name=acl,proto3" json:"acl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateInvocationRequest) Reset() {
	*x = UpdateInvocationRequest{}
	mi := &file_proto_invocation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvocationRequest) ProtoMessage() {}

func (x *UpdateInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInvocationRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *UpdateInvocationRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *UpdateInvocationRequest) GetAcl() *acl.ACL {
	if x != nil {
		return x.Acl
	}
	return nil
}

type UpdateInvocationResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateInvocationResponse) Reset() {
	*x = UpdateInvocationResponse{}
	mi := &file_proto_invocation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvocationResponse) ProtoMessage() {}

func (x *UpdateInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateInvocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInvocationResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

type DeleteInvocationRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	InvocationId   string                  `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteInvocationRequest) Reset() {
	*x = DeleteInvocationRequest{}
	mi := &file_proto_invocation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvocationRequest) ProtoMessage() {}

func (x *DeleteInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteInvocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInvocationRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *DeleteInvocationRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

type DeleteInvocationResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteInvocationResponse) Reset() {
	*x = DeleteInvocationResponse{}
	mi := &file_proto_invocation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvocationResponse) ProtoMessage() {}

func (x *DeleteInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteInvocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInvocationResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

type CancelExecutionsRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	InvocationId   string                  `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelExecutionsRequest) Reset() {
	*x = CancelExecutionsRequest{}
	mi := &file_proto_invocation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionsRequest) ProtoMessage() {}

func (x *CancelExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionsRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{11}
}

func (x *CancelExecutionsRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *CancelExecutionsRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

type CancelExecutionsResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelExecutionsResponse) Reset() {
	*x = CancelExecutionsResponse{}
	mi := &file_proto_invocation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionsResponse) ProtoMessage() {}

func (x *CancelExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionsResponse.ProtoReflect.Descriptor instead.
func (*CancelExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{12}
}

func (x *CancelExecutionsResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

type InvocationQuery struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	User            string                            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Host            string                            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	GroupId         string                            `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RepoUrl         string                            `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	CommitSha       string                            `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Role            []string                          `protobuf:"bytes,6,rep,name=role,proto3" json:"role,omitempty"`
	UpdatedAfter    *timestamppb.Timestamp            `protobuf:"bytes,7,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	UpdatedBefore   *timestamppb.Timestamp            `protobuf:"bytes,8,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
	Status          []invocation_status.OverallStatus `protobuf:"varint,9,rep,packed,name=status,proto3,enum=invocation_status.OverallStatus" json:"status,omitempty"`
	BranchName      string                            `protobuf:"bytes,10,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Command         string                            `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`
	MinimumDuration *durationpb.Duration              `protobuf:"bytes,12,opt,name=minimum_duration,json=minimumDuration,proto3" json:"minimum_duration,omitempty"`
	MaximumDuration *durationpb.Duration              `protobuf:"bytes,13,opt,name=maximum_duration,json=maximumDuration,proto3" json:"maximum_duration,omitempty"`
	Filter          []*stat_filter.StatFilter         `protobuf:"bytes,14,rep,name=filter,proto3" json:"filter,omitempty"`
	DimensionFilter []*stat_filter.DimensionFilter    `protobuf:"bytes,17,rep,name=dimension_filter,json=dimensionFilter,proto3" json:"dimension_filter,omitempty"`
	Pattern         string                            `protobuf:"bytes,15,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Tags            []string                          `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	GenericFilters  []*stat_filter.GenericFilter      `protobuf:"bytes,18,rep,name=generic_filters,json=genericFilters,proto3" json:"generic_filters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvocationQuery) Reset() {
	*x = InvocationQuery{}
	mi := &file_proto_invocation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationQuery) ProtoMessage() {}

func (x *InvocationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationQuery.ProtoReflect.Descriptor instead.
func (*InvocationQuery) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{13}
}

func (x *InvocationQuery) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *InvocationQuery) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InvocationQuery) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *InvocationQuery) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *InvocationQuery) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *InvocationQuery) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *InvocationQuery) GetUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAfter
	}
	return nil
}

func (x *InvocationQuery) GetUpdatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedBefore
	}
	return nil
}

func (x *InvocationQuery) GetStatus() []invocation_status.OverallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InvocationQuery) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *InvocationQuery) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InvocationQuery) GetMinimumDuration() *durationpb.Duration {
	if x != nil {
		return x.MinimumDuration
	}
	return nil
}

func (x *InvocationQuery) GetMaximumDuration() *durationpb.Duration {
	if x != nil {
		return x.MaximumDuration
	}
	return nil
}

func (x *InvocationQuery) GetFilter() []*stat_filter.StatFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *InvocationQuery) GetDimensionFilter() []*stat_filter.DimensionFilter {
	if x != nil {
		return x.DimensionFilter
	}
	return nil
}

func (x *InvocationQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *InvocationQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InvocationQuery) GetGenericFilters() []*stat_filter.GenericFilter {
	if x != nil {
		return x.GenericFilters
	}
	return nil
}

type InvocationSort struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	SortField     InvocationSort_SortField `protobuf:"varint,1,opt,name=sort_field,json=sortField,proto3,enum=invocation.InvocationSort_SortField" json:"sort_field,omitempty"`
	Ascending     bool                     `protobuf:"varint,2,opt,name=ascending,proto3" json:"ascending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationSort) Reset() {
	*x = InvocationSort{}
	mi := &file_proto_invocation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationSort) ProtoMessage() {}

func (x *InvocationSort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationSort.ProtoReflect.Descriptor instead.
func (*InvocationSort) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{14}
}

func (x *InvocationSort) GetSortField() InvocationSort_SortField {
	if x != nil {
		return x.SortField
	}
	return InvocationSort_UNKNOWN_SORT_FIELD
}

func (x *InvocationSort) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

type SearchInvocationRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	Query          *InvocationQuery        `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Sort           *InvocationSort         `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Count          int32                   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	PageToken      string                  `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchInvocationRequest) Reset() {
	*x = SearchInvocationRequest{}
	mi := &file_proto_invocation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvocationRequest) ProtoMessage() {}

func (x *SearchInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvocationRequest.ProtoReflect.Descriptor instead.
func (*SearchInvocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{15}
}

func (x *SearchInvocationRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *SearchInvocationRequest) GetQuery() *InvocationQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchInvocationRequest) GetSort() *InvocationSort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchInvocationRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchInvocationRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchInvocationResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	Invocation      []*Invocation            `protobuf:"bytes,2,rep,name=invocation,proto3" json:"invocation,omitempty"`
	NextPageToken   string                   `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchInvocationResponse) Reset() {
	*x = SearchInvocationResponse{}
	mi := &file_proto_invocation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvocationResponse) ProtoMessage() {}

func (x *SearchInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvocationResponse.ProtoReflect.Descriptor instead.
func (*SearchInvocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{16}
}

func (x *SearchInvocationResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *SearchInvocationResponse) GetInvocation() []*Invocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

func (x *SearchInvocationResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type InvocationStat struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalBuildTimeUsec      int64                  `protobuf:"varint,3,opt,name=total_build_time_usec,json=totalBuildTimeUsec,proto3" json:"total_build_time_usec,omitempty"`
	LatestBuildTimeUsec     int64                  `protobuf:"varint,5,opt,name=latest_build_time_usec,json=latestBuildTimeUsec,proto3" json:"latest_build_time_usec,omitempty"`
	LastGreenBuildUsec      int64                  `protobuf:"varint,7,opt,name=last_green_build_usec,json=lastGreenBuildUsec,proto3" json:"last_green_build_usec,omitempty"`
	LastRedBuildUsec        int64                  `protobuf:"varint,10,opt,name=last_red_build_usec,json=lastRedBuildUsec,proto3" json:"last_red_build_usec,omitempty"`
	TotalNumBuilds          int64                  `protobuf:"varint,4,opt,name=total_num_builds,json=totalNumBuilds,proto3" json:"total_num_builds,omitempty"`
	TotalNumSucessfulBuilds int64                  `protobuf:"varint,8,opt,name=total_num_sucessful_builds,json=totalNumSucessfulBuilds,proto3" json:"total_num_sucessful_builds,omitempty"`
	TotalNumFailingBuilds   int64                  `protobuf:"varint,9,opt,name=total_num_failing_builds,json=totalNumFailingBuilds,proto3" json:"total_num_failing_builds,omitempty"`
	TotalActions            int64                  `protobuf:"varint,6,opt,name=total_actions,json=totalActions,proto3" json:"total_actions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InvocationStat) Reset() {
	*x = InvocationStat{}
	mi := &file_proto_invocation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationStat) ProtoMessage() {}

func (x *InvocationStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationStat.ProtoReflect.Descriptor instead.
func (*InvocationStat) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{17}
}

func (x *InvocationStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvocationStat) GetTotalBuildTimeUsec() int64 {
	if x != nil {
		return x.TotalBuildTimeUsec
	}
	return 0
}

func (x *InvocationStat) GetLatestBuildTimeUsec() int64 {
	if x != nil {
		return x.LatestBuildTimeUsec
	}
	return 0
}

func (x *InvocationStat) GetLastGreenBuildUsec() int64 {
	if x != nil {
		return x.LastGreenBuildUsec
	}
	return 0
}

func (x *InvocationStat) GetLastRedBuildUsec() int64 {
	if x != nil {
		return x.LastRedBuildUsec
	}
	return 0
}

func (x *InvocationStat) GetTotalNumBuilds() int64 {
	if x != nil {
		return x.TotalNumBuilds
	}
	return 0
}

func (x *InvocationStat) GetTotalNumSucessfulBuilds() int64 {
	if x != nil {
		return x.TotalNumSucessfulBuilds
	}
	return 0
}

func (x *InvocationStat) GetTotalNumFailingBuilds() int64 {
	if x != nil {
		return x.TotalNumFailingBuilds
	}
	return 0
}

func (x *InvocationStat) GetTotalActions() int64 {
	if x != nil {
		return x.TotalActions
	}
	return 0
}

type InvocationStatQuery struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	User            string                            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Host            string                            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	RepoUrl         string                            `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	CommitSha       string                            `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Role            []string                          `protobuf:"bytes,6,rep,name=role,proto3" json:"role,omitempty"`
	UpdatedAfter    *timestamppb.Timestamp            `protobuf:"bytes,7,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	UpdatedBefore   *timestamppb.Timestamp            `protobuf:"bytes,8,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
	Status          []invocation_status.OverallStatus `protobuf:"varint,9,rep,packed,name=status,proto3,enum=invocation_status.OverallStatus" json:"status,omitempty"`
	BranchName      string                            `protobuf:"bytes,10,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Command         string                            `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`
	Filter          []*stat_filter.StatFilter         `protobuf:"bytes,12,rep,name=filter,proto3" json:"filter,omitempty"`
	MinimumDuration *durationpb.Duration              `protobuf:"bytes,17,opt,name=minimum_duration,json=minimumDuration,proto3" json:"minimum_duration,omitempty"`
	MaximumDuration *durationpb.Duration              `protobuf:"bytes,18,opt,name=maximum_duration,json=maximumDuration,proto3" json:"maximum_duration,omitempty"`
	DimensionFilter []*stat_filter.DimensionFilter    `protobuf:"bytes,15,rep,name=dimension_filter,json=dimensionFilter,proto3" json:"dimension_filter,omitempty"`
	GenericFilters  []*stat_filter.GenericFilter      `protobuf:"bytes,16,rep,name=generic_filters,json=genericFilters,proto3" json:"generic_filters,omitempty"`
	Pattern         string                            `protobuf:"bytes,13,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Tags            []string                          `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvocationStatQuery) Reset() {
	*x = InvocationStatQuery{}
	mi := &file_proto_invocation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationStatQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationStatQuery) ProtoMessage() {}

func (x *InvocationStatQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationStatQuery.ProtoReflect.Descriptor instead.
func (*InvocationStatQuery) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{18}
}

func (x *InvocationStatQuery) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *InvocationStatQuery) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InvocationStatQuery) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *InvocationStatQuery) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *InvocationStatQuery) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *InvocationStatQuery) GetUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAfter
	}
	return nil
}

func (x *InvocationStatQuery) GetUpdatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedBefore
	}
	return nil
}

func (x *InvocationStatQuery) GetStatus() []invocation_status.OverallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InvocationStatQuery) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *InvocationStatQuery) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InvocationStatQuery) GetFilter() []*stat_filter.StatFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *InvocationStatQuery) GetMinimumDuration() *durationpb.Duration {
	if x != nil {
		return x.MinimumDuration
	}
	return nil
}

func (x *InvocationStatQuery) GetMaximumDuration() *durationpb.Duration {
	if x != nil {
		return x.MaximumDuration
	}
	return nil
}

func (x *InvocationStatQuery) GetDimensionFilter() []*stat_filter.DimensionFilter {
	if x != nil {
		return x.DimensionFilter
	}
	return nil
}

func (x *InvocationStatQuery) GetGenericFilters() []*stat_filter.GenericFilter {
	if x != nil {
		return x.GenericFilters
	}
	return nil
}

func (x *InvocationStatQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *InvocationStatQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetInvocationStatRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	RequestContext  *context.RequestContext `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	AggregationType AggType                 `protobuf:"varint,2,opt,name=aggregation_type,json=aggregationType,proto3,enum=invocation.AggType" json:"aggregation_type,omitempty"`
	Limit           int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Query           *InvocationStatQuery    `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInvocationStatRequest) Reset() {
	*x = GetInvocationStatRequest{}
	mi := &file_proto_invocation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationStatRequest) ProtoMessage() {}

func (x *GetInvocationStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationStatRequest.ProtoReflect.Descriptor instead.
func (*GetInvocationStatRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{19}
}

func (x *GetInvocationStatRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetInvocationStatRequest) GetAggregationType() AggType {
	if x != nil {
		return x.AggregationType
	}
	return AggType_UNKNOWN_AGGREGATION_TYPE
}

func (x *GetInvocationStatRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetInvocationStatRequest) GetQuery() *InvocationStatQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetInvocationStatResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ResponseContext *context.ResponseContext `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	InvocationStat  []*InvocationStat        `protobuf:"bytes,2,rep,name=invocation_stat,json=invocationStat,proto3" json:"invocation_stat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInvocationStatResponse) Reset() {
	*x = GetInvocationStatResponse{}
	mi := &file_proto_invocation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationStatResponse) ProtoMessage() {}

func (x *GetInvocationStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationStatResponse.ProtoReflect.Descriptor instead.
func (*GetInvocationStatResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{20}
}

func (x *GetInvocationStatResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *GetInvocationStatResponse) GetInvocationStat() []*InvocationStat {
	if x != nil {
		return x.InvocationStat
	}
	return nil
}

type GetInvocationFilterSuggestionsRequest struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	RequestContext *context.RequestContext      `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	Filters        []*stat_filter.GenericFilter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInvocationFilterSuggestionsRequest) Reset() {
	*x = GetInvocationFilterSuggestionsRequest{}
	mi := &file_proto_invocation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationFilterSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationFilterSuggestionsRequest) ProtoMessage() {}

func (x *GetInvocationFilterSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationFilterSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetInvocationFilterSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{21}
}

func (x *GetInvocationFilterSuggestionsRequest) GetRequestContext() *context.RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetInvocationFilterSuggestionsRequest) GetFilters() []*stat_filter.GenericFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetInvocationFilterSuggestionsResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	ResponseContext *context.ResponseContext     `protobuf:"bytes,1,opt,name=response_context,json=responseContext,proto3" json:"response_context,omitempty"`
	Suggestions     []*stat_filter.GenericFilter `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInvocationFilterSuggestionsResponse) Reset() {
	*x = GetInvocationFilterSuggestionsResponse{}
	mi := &file_proto_invocation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationFilterSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationFilterSuggestionsResponse) ProtoMessage() {}

func (x *GetInvocationFilterSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationFilterSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetInvocationFilterSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{22}
}

func (x *GetInvocationFilterSuggestionsResponse) GetResponseContext() *context.ResponseContext {
	if x != nil {
		return x.ResponseContext
	}
	return nil
}

func (x *GetInvocationFilterSuggestionsResponse) GetSuggestions() []*stat_filter.GenericFilter {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type Invocation_Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invocation_Tag) Reset() {
	*x = Invocation_Tag{}
	mi := &file_proto_invocation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation_Tag) ProtoMessage() {}

func (x *Invocation_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invocation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation_Tag.ProtoReflect.Descriptor instead.
func (*Invocation_Tag) Descriptor() ([]byte, []int) {
	return file_proto_invocation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Invocation_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_invocation_proto protoreflect.FileDescriptor

const file_proto_invocation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/invocation.proto\x12\n" +
	"invocation\x1a\x0fproto/acl.proto\x1a\x1eproto/build_event_stream.proto\x1a\x11proto/cache.proto\x1a\x16proto/capability.proto\x1a\x18proto/command_line.proto\x1a\x13proto/context.proto\x1a\x1dproto/invocation_status.proto\x1a\x17proto/stat_filter.proto\x1a\x12proto/target.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa1\x0e\n" +
	"\n" +
	"Invocation\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x121\n" +
	"\x05event\x18\x02 \x03(\v2\x1b.invocation.InvocationEventR\x05event\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12#\n" +
	"\rduration_usec\x18\x05 \x01(\x03R\fdurationUsec\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x18\n" +
	"\acommand\x18\a \x01(\tR\acommand\x12\x18\n" +
	"\apattern\x18\b \x03(\tR\apattern\x12!\n" +
	"\faction_count\x18\t \x01(\x03R\vactionCount\x12P\n" +
	"\x11invocation_status\x18\n" +
	" \x01(\x0e2#.invocation_status.InvocationStatusR\x10invocationStatus\x12%\n" +
	"\x0econsole_buffer\x18\v \x01(\tR\rconsoleBuffer\x12Q\n" +
	"\x17structured_command_line\x18\f \x03(\v2\x19.command_line.CommandLineR\x15structuredCommandLine\x12&\n" +
	"\x0fcreated_at_usec\x18\r \x01(\x03R\rcreatedAtUsec\x12&\n" +
	"\x0fupdated_at_usec\x18\x0e \x01(\x03R\rupdatedAtUsec\x12\x19\n" +
	"\brepo_url\x18\x0f \x01(\tR\arepoUrl\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x10 \x01(\tR\tcommitSha\x12I\n" +
	"\x0fread_permission\x18\x11 \x01(\x0e2 .invocation.InvocationPermissionR\x0ereadPermission\x122\n" +
	"\vcache_stats\x18\x12 \x01(\v2\x11.cache.CacheStatsR\n" +
	"cacheStats\x12/\n" +
	"\n" +
	"score_card\x18\x18 \x01(\v2\x10.cache.ScoreCardR\tscoreCard\x12\x12\n" +
	"\x04role\x18\x13 \x01(\tR\x04role\x12\x1a\n" +
	"\x03acl\x18\x14 \x01(\v2\b.acl.ACLR\x03acl\x12\"\n" +
	"\rlast_chunk_id\x18\x15 \x01(\tR\vlastChunkId\x123\n" +
	"\x16has_chunked_event_logs\x18\x16 \x01(\bR\x13hasChunkedEventLogs\x12\x1f\n" +
	"\vbranch_name\x18\x17 \x01(\tR\n" +
	"branchName\x12\x18\n" +
	"\aattempt\x18\x19 \x01(\x04R\aattempt\x12&\n" +
	"\x0fbazel_exit_code\x18\x1a \x01(\tR\rbazelExitCode\x12R\n" +
	"\x19created_with_capabilities\x18\x1b \x03(\x0e2\x16.capability.CapabilityR\x17createdWithCapabilities\x12Y\n" +
	"\x17download_outputs_option\x18\x1c \x01(\x0e2!.invocation.DownloadOutputsOptionR\x15downloadOutputsOption\x12?\n" +
	"\x1cupload_local_results_enabled\x18\x1d \x01(\bR\x19uploadLocalResultsEnabled\x128\n" +
	"\x18remote_execution_enabled\x18\x1e \x01(\bR\x16remoteExecutionEnabled\x12.\n" +
	"\x04tags\x18\x1f \x03(\v2\x1a.invocation.Invocation.TagR\x04tags\x128\n" +
	"\rtarget_groups\x18  \x03(\v2\x13.target.TargetGroupR\ftargetGroups\x12-\n" +
	"\x12patterns_truncated\x18! \x01(\bR\x11patternsTruncated\x126\n" +
	"\x17target_configured_count\x18\" \x01(\x03R\x15targetConfiguredCount\x12C\n" +
	"\x11child_invocations\x18$ \x03(\v2\x16.invocation.InvocationR\x10childInvocations\x12\x15\n" +
	"\x06run_id\x18% \x01(\tR\x05runId\x12\"\n" +
	"\rparent_run_id\x18& \x01(\tR\vparentRunId\x124\n" +
	"\x14parent_invocation_id\x18# \x01(\tB\x02\x18\x01R\x12parentInvocationId\x12?\n" +
	"\n" +
	"run_status\x18' \x01(\x0e2 .invocation_status.OverallStatusR\trunStatus\x1a\x19\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb6\x01\n" +
	"\x0fInvocationEvent\x129\n" +
	"\n" +
	"event_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12?\n" +
	"\vbuild_event\x18\x02 \x01(\v2\x1e.build_event_stream.BuildEventR\n" +
	"buildEvent\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\"o\n" +
	"\x10InvocationLookup\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x126\n" +
	"\x17fetch_child_invocations\x18\x02 \x01(\bR\x15fetchChildInvocations\"\x8e\x01\n" +
	"\x14GetInvocationRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x124\n" +
	"\x06lookup\x18\x02 \x01(\v2\x1c.invocation.InvocationLookupR\x06lookup\"\x94\x01\n" +
	"\x15GetInvocationResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x126\n" +
	"\n" +
	"invocation\x18\x02 \x03(\v2\x16.invocation.InvocationR\n" +
	"invocation\"\x82\x01\n" +
	"\x19GetInvocationOwnerRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\"\x99\x01\n" +
	"\x1aGetInvocationOwnerResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tgroup_url\x18\x03 \x01(\tR\bgroupUrl\"\x9c\x01\n" +
	"\x17UpdateInvocationRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x1a\n" +
	"\x03acl\x18\x03 \x01(\v2\b.acl.ACLR\x03acl\"_\n" +
	"\x18UpdateInvocationResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\"\x80\x01\n" +
	"\x17DeleteInvocationRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\"_\n" +
	"\x18DeleteInvocationResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\"\x80\x01\n" +
	"\x17CancelExecutionsRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\"_\n" +
	"\x18CancelExecutionsResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\"\x94\x06\n" +
	"\x0fInvocationQuery\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\x12\x12\n" +
	"\x04role\x18\x06 \x03(\tR\x04role\x12?\n" +
	"\rupdated_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedAfter\x12A\n" +
	"\x0eupdated_before\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rupdatedBefore\x128\n" +
	"\x06status\x18\t \x03(\x0e2 .invocation_status.OverallStatusR\x06status\x12\x1f\n" +
	"\vbranch_name\x18\n" +
	" \x01(\tR\n" +
	"branchName\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand\x12D\n" +
	"\x10minimum_duration\x18\f \x01(\v2\x19.google.protobuf.DurationR\x0fminimumDuration\x12D\n" +
	"\x10maximum_duration\x18\r \x01(\v2\x19.google.protobuf.DurationR\x0fmaximumDuration\x12/\n" +
	"\x06filter\x18\x0e \x03(\v2\x17.stat_filter.StatFilterR\x06filter\x12G\n" +
	"\x10dimension_filter\x18\x11 \x03(\v2\x1c.stat_filter.DimensionFilterR\x0fdimensionFilter\x12\x18\n" +
	"\apattern\x18\x0f \x01(\tR\apattern\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\x12C\n" +
	"\x0fgeneric_filters\x18\x12 \x03(\v2\x1a.stat_filter.GenericFilterR\x0egenericFilters\"\xb5\x03\n" +
	"\x0eInvocationSort\x12C\n" +
	"\n" +
	"sort_field\x18\x01 \x01(\x0e2$.invocation.InvocationSort.SortFieldR\tsortField\x12\x1c\n" +
	"\tascending\x18\x02 \x01(\bR\tascending\"\xbf\x02\n" +
	"\tSortField\x12\x16\n" +
	"\x12UNKNOWN_SORT_FIELD\x10\x00\x12\x1e\n" +
	"\x1aCREATED_AT_USEC_SORT_FIELD\x10\x01\x12\x1e\n" +
	"\x1aUPDATED_AT_USEC_SORT_FIELD\x10\x02\x12\x17\n" +
	"\x13DURATION_SORT_FIELD\x10\x03\x12%\n" +
	"!ACTION_CACHE_HIT_RATIO_SORT_FIELD\x10\x04\x128\n" +
	"4CONTENT_ADDRESSABLE_STORE_CACHE_HIT_RATIO_SORT_FIELD\x10\x05\x12\x1f\n" +
	"\x1bCACHE_DOWNLOADED_SORT_FIELD\x10\x06\x12\x1d\n" +
	"\x19CACHE_UPLOADED_SORT_FIELD\x10\a\x12 \n" +
	"\x1cCACHE_TRANSFERRED_SORT_FIELD\x10\b\"\xf3\x01\n" +
	"\x17SearchInvocationRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x121\n" +
	"\x05query\x18\x02 \x01(\v2\x1b.invocation.InvocationQueryR\x05query\x12.\n" +
	"\x04sort\x18\x03 \x01(\v2\x1a.invocation.InvocationSortR\x04sort\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\xbf\x01\n" +
	"\x18SearchInvocationResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x126\n" +
	"\n" +
	"invocation\x18\x02 \x03(\v2\x16.invocation.InvocationR\n" +
	"invocation\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xb3\x03\n" +
	"\x0eInvocationStat\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x15total_build_time_usec\x18\x03 \x01(\x03R\x12totalBuildTimeUsec\x123\n" +
	"\x16latest_build_time_usec\x18\x05 \x01(\x03R\x13latestBuildTimeUsec\x121\n" +
	"\x15last_green_build_usec\x18\a \x01(\x03R\x12lastGreenBuildUsec\x12-\n" +
	"\x13last_red_build_usec\x18\n" +
	" \x01(\x03R\x10lastRedBuildUsec\x12(\n" +
	"\x10total_num_builds\x18\x04 \x01(\x03R\x0etotalNumBuilds\x12;\n" +
	"\x1atotal_num_sucessful_builds\x18\b \x01(\x03R\x17totalNumSucessfulBuilds\x127\n" +
	"\x18total_num_failing_builds\x18\t \x01(\x03R\x15totalNumFailingBuilds\x12#\n" +
	"\rtotal_actions\x18\x06 \x01(\x03R\ftotalActions\"\xfd\x05\n" +
	"\x13InvocationStatQuery\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\x12\x12\n" +
	"\x04role\x18\x06 \x03(\tR\x04role\x12?\n" +
	"\rupdated_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedAfter\x12A\n" +
	"\x0eupdated_before\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rupdatedBefore\x128\n" +
	"\x06status\x18\t \x03(\x0e2 .invocation_status.OverallStatusR\x06status\x12\x1f\n" +
	"\vbranch_name\x18\n" +
	" \x01(\tR\n" +
	"branchName\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand\x12/\n" +
	"\x06filter\x18\f \x03(\v2\x17.stat_filter.StatFilterR\x06filter\x12D\n" +
	"\x10minimum_duration\x18\x11 \x01(\v2\x19.google.protobuf.DurationR\x0fminimumDuration\x12D\n" +
	"\x10maximum_duration\x18\x12 \x01(\v2\x19.google.protobuf.DurationR\x0fmaximumDuration\x12G\n" +
	"\x10dimension_filter\x18\x0f \x03(\v2\x1c.stat_filter.DimensionFilterR\x0fdimensionFilter\x12C\n" +
	"\x0fgeneric_filters\x18\x10 \x03(\v2\x1a.stat_filter.GenericFilterR\x0egenericFilters\x12\x18\n" +
	"\apattern\x18\r \x01(\tR\apattern\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\"\xe9\x01\n" +
	"\x18GetInvocationStatRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x12>\n" +
	"\x10aggregation_type\x18\x02 \x01(\x0e2\x13.invocation.AggTypeR\x0faggregationType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x125\n" +
	"\x05query\x18\x04 \x01(\v2\x1f.invocation.InvocationStatQueryR\x05query\"\xa5\x01\n" +
	"\x19GetInvocationStatResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x12C\n" +
	"\x0finvocation_stat\x18\x02 \x03(\v2\x1a.invocation.InvocationStatR\x0einvocationStat\"\x9f\x01\n" +
	"%GetInvocationFilterSuggestionsRequest\x12@\n" +
	"\x0frequest_context\x18\x01 \x01(\v2\x17.context.RequestContextR\x0erequestContext\x124\n" +
	"\afilters\x18\x02 \x03(\v2\x1a.stat_filter.GenericFilterR\afilters\"\xab\x01\n" +
	"&GetInvocationFilterSuggestionsResponse\x12C\n" +
	"\x10response_context\x18\x01 \x01(\v2\x18.context.ResponseContextR\x0fresponseContext\x12<\n" +
	"\vsuggestions\x18\x02 \x03(\v2\x1a.stat_filter.GenericFilterR\vsuggestions*k\n" +
	"\x15DownloadOutputsOption\x12#\n" +
	"\x1fUNKNOWN_DOWNLOAD_OUTPUTS_OPTION\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\a\n" +
	"\x03ALL\x10\x02\x12\r\n" +
	"\tTOP_LEVEL\x10\x03\x12\v\n" +
	"\aMINIMAL\x10\x04*P\n" +
	"\x14InvocationPermission\x12\x16\n" +
	"\x12UNKNOWN_PERMISSION\x10\x00\x12\t\n" +
	"\x05OWNER\x10\x01\x12\t\n" +
	"\x05GROUP\x10\x02\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x03*\x96\x02\n" +
	"\aAggType\x12\x1c\n" +
	"\x18UNKNOWN_AGGREGATION_TYPE\x10\x00\x12\x19\n" +
	"\x15USER_AGGREGATION_TYPE\x10\x01\x12\x1d\n" +
	"\x19HOSTNAME_AGGREGATION_TYPE\x10\x02\x12\x1d\n" +
	"\x19GROUP_ID_AGGREGATION_TYPE\x10\x03\x12\x1d\n" +
	"\x19REPO_URL_AGGREGATION_TYPE\x10\x04\x12\x1f\n" +
	"\x1bCOMMIT_SHA_AGGREGATION_TYPE\x10\x05\x12\x19\n" +
	"\x15DATE_AGGREGATION_TYPE\x10\x06\x12\x1b\n" +
	"\x17BRANCH_AGGREGATION_TYPE\x10\a\x12\x1c\n" +
	"\x18PATTERN_AGGREGATION_TYPE\x10\bb\x06proto3"

var (
	file_proto_invocation_proto_rawDescOnce sync.Once
	file_proto_invocation_proto_rawDescData []byte
)

func file_proto_invocation_proto_rawDescGZIP() []byte {
	file_proto_invocation_proto_rawDescOnce.Do(func() {
		file_proto_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_invocation_proto_rawDesc), len(file_proto_invocation_proto_rawDesc)))
	})
	return file_proto_invocation_proto_rawDescData
}

var file_proto_invocation_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_invocation_proto_goTypes = []any{
	(DownloadOutputsOption)(0),                     // 0: invocation.DownloadOutputsOption
	(InvocationPermission)(0),                      // 1: invocation.InvocationPermission
	(AggType)(0),                                   // 2: invocation.AggType
	(InvocationSort_SortField)(0),                  // 3: invocation.InvocationSort.SortField
	(*Invocation)(nil),                             // 4: invocation.Invocation
	(*InvocationEvent)(nil),                        // 5: invocation.InvocationEvent
	(*InvocationLookup)(nil),                       // 6: invocation.InvocationLookup
	(*GetInvocationRequest)(nil),                   // 7: invocation.GetInvocationRequest
	(*GetInvocationResponse)(nil),                  // 8: invocation.GetInvocationResponse
	(*GetInvocationOwnerRequest)(nil),              // 9: invocation.GetInvocationOwnerRequest
	(*GetInvocationOwnerResponse)(nil),             // 10: invocation.GetInvocationOwnerResponse
	(*UpdateInvocationRequest)(nil),                // 11: invocation.UpdateInvocationRequest
	(*UpdateInvocationResponse)(nil),               // 12: invocation.UpdateInvocationResponse
	(*DeleteInvocationRequest)(nil),                // 13: invocation.DeleteInvocationRequest
	(*DeleteInvocationResponse)(nil),               // 14: invocation.DeleteInvocationResponse
	(*CancelExecutionsRequest)(nil),                // 15: invocation.CancelExecutionsRequest
	(*CancelExecutionsResponse)(nil),               // 16: invocation.CancelExecutionsResponse
	(*InvocationQuery)(nil),                        // 17: invocation.InvocationQuery
	(*InvocationSort)(nil),                         // 18: invocation.InvocationSort
	(*SearchInvocationRequest)(nil),                // 19: invocation.SearchInvocationRequest
	(*SearchInvocationResponse)(nil),               // 20: invocation.SearchInvocationResponse
	(*InvocationStat)(nil),                         // 21: invocation.InvocationStat
	(*InvocationStatQuery)(nil),                    // 22: invocation.InvocationStatQuery
	(*GetInvocationStatRequest)(nil),               // 23: invocation.GetInvocationStatRequest
	(*GetInvocationStatResponse)(nil),              // 24: invocation.GetInvocationStatResponse
	(*GetInvocationFilterSuggestionsRequest)(nil),  // 25: invocation.GetInvocationFilterSuggestionsRequest
	(*GetInvocationFilterSuggestionsResponse)(nil), // 26: invocation.GetInvocationFilterSuggestionsResponse
	(*Invocation_Tag)(nil),                         // 27: invocation.Invocation.Tag
	(invocation_status.InvocationStatus)(0),        // 28: invocation_status.InvocationStatus
	(*command_line.CommandLine)(nil),               // 29: command_line.CommandLine
	(*cache.CacheStats)(nil),                       // 30: cache.CacheStats
	(*cache.ScoreCard)(nil),                        // 31: cache.ScoreCard
	(*acl.ACL)(nil),                                // 32: acl.ACL
	(capability.Capability)(0),                     // 33: capability.Capability
	(*target.TargetGroup)(nil),                     // 34: target.TargetGroup
	(invocation_status.OverallStatus)(0),           // 35: invocation_status.OverallStatus
	(*timestamppb.Timestamp)(nil),                  // 36: google.protobuf.Timestamp
	(*build_event_stream.BuildEvent)(nil),          // 37: build_event_stream.BuildEvent
	(*context.RequestContext)(nil),                 // 38: context.RequestContext
	(*context.ResponseContext)(nil),                // 39: context.ResponseContext
	(*durationpb.Duration)(nil),                    // 40: google.protobuf.Duration
	(*stat_filter.StatFilter)(nil),                 // 41: stat_filter.StatFilter
	(*stat_filter.DimensionFilter)(nil),            // 42: stat_filter.DimensionFilter
	(*stat_filter.GenericFilter)(nil),              // 43: stat_filter.GenericFilter
}
var file_proto_invocation_proto_depIdxs = []int32{
	5,  // 0: invocation.Invocation.event:type_name -> invocation.InvocationEvent
	28, // 1: invocation.Invocation.invocation_status:type_name -> invocation_status.InvocationStatus
	29, // 2: invocation.Invocation.structured_command_line:type_name -> command_line.CommandLine
	1,  // 3: invocation.Invocation.read_permission:type_name -> invocation.InvocationPermission
	30, // 4: invocation.Invocation.cache_stats:type_name -> cache.CacheStats
	31, // 5: invocation.Invocation.score_card:type_name -> cache.ScoreCard
	32, // 6: invocation.Invocation.acl:type_name -> acl.ACL
	33, // 7: invocation.Invocation.created_with_capabilities:type_name -> capability.Capability
	0,  // 8: invocation.Invocation.download_outputs_option:type_name -> invocation.DownloadOutputsOption
	27, // 9: invocation.Invocation.tags:type_name -> invocation.Invocation.Tag
	34, // 10: invocation.Invocation.target_groups:type_name -> target.TargetGroup
	4,  // 11: invocation.Invocation.child_invocations:type_name -> invocation.Invocation
	35, // 12: invocation.Invocation.run_status:type_name -> invocation_status.OverallStatus
	36, // 13: invocation.InvocationEvent.event_time:type_name -> google.protobuf.Timestamp
	37, // 14: invocation.InvocationEvent.build_event:type_name -> build_event_stream.BuildEvent
	38, // 15: invocation.GetInvocationRequest.request_context:type_name -> context.RequestContext
	6,  // 16: invocation.GetInvocationRequest.lookup:type_name -> invocation.InvocationLookup
	39, // 17: invocation.GetInvocationResponse.response_context:type_name -> context.ResponseContext
	4,  // 18: invocation.GetInvocationResponse.invocation:type_name -> invocation.Invocation
	38, // 19: invocation.GetInvocationOwnerRequest.request_context:type_name -> context.RequestContext
	39, // 20: invocation.GetInvocationOwnerResponse.response_context:type_name -> context.ResponseContext
	38, // 21: invocation.UpdateInvocationRequest.request_context:type_name -> context.RequestContext
	32, // 22: invocation.UpdateInvocationRequest.acl:type_name -> acl.ACL
	39, // 23: invocation.UpdateInvocationResponse.response_context:type_name -> context.ResponseContext
	38, // 24: invocation.DeleteInvocationRequest.request_context:type_name -> context.RequestContext
	39, // 25: invocation.DeleteInvocationResponse.response_context:type_name -> context.ResponseContext
	38, // 26: invocation.CancelExecutionsRequest.request_context:type_name -> context.RequestContext
	39, // 27: invocation.CancelExecutionsResponse.response_context:type_name -> context.ResponseContext
	36, // 28: invocation.InvocationQuery.updated_after:type_name -> google.protobuf.Timestamp
	36, // 29: invocation.InvocationQuery.updated_before:type_name -> google.protobuf.Timestamp
	35, // 30: invocation.InvocationQuery.status:type_name -> invocation_status.OverallStatus
	40, // 31: invocation.InvocationQuery.minimum_duration:type_name -> google.protobuf.Duration
	40, // 32: invocation.InvocationQuery.maximum_duration:type_name -> google.protobuf.Duration
	41, // 33: invocation.InvocationQuery.filter:type_name -> stat_filter.StatFilter
	42, // 34: invocation.InvocationQuery.dimension_filter:type_name -> stat_filter.DimensionFilter
	43, // 35: invocation.InvocationQuery.generic_filters:type_name -> stat_filter.GenericFilter
	3,  // 36: invocation.InvocationSort.sort_field:type_name -> invocation.InvocationSort.SortField
	38, // 37: invocation.SearchInvocationRequest.request_context:type_name -> context.RequestContext
	17, // 38: invocation.SearchInvocationRequest.query:type_name -> invocation.InvocationQuery
	18, // 39: invocation.SearchInvocationRequest.sort:type_name -> invocation.InvocationSort
	39, // 40: invocation.SearchInvocationResponse.response_context:type_name -> context.ResponseContext
	4,  // 41: invocation.SearchInvocationResponse.invocation:type_name -> invocation.Invocation
	36, // 42: invocation.InvocationStatQuery.updated_after:type_name -> google.protobuf.Timestamp
	36, // 43: invocation.InvocationStatQuery.updated_before:type_name -> google.protobuf.Timestamp
	35, // 44: invocation.InvocationStatQuery.status:type_name -> invocation_status.OverallStatus
	41, // 45: invocation.InvocationStatQuery.filter:type_name -> stat_filter.StatFilter
	40, // 46: invocation.InvocationStatQuery.minimum_duration:type_name -> google.protobuf.Duration
	40, // 47: invocation.InvocationStatQuery.maximum_duration:type_name -> google.protobuf.Duration
	42, // 48: invocation.InvocationStatQuery.dimension_filter:type_name -> stat_filter.DimensionFilter
	43, // 49: invocation.InvocationStatQuery.generic_filters:type_name -> stat_filter.GenericFilter
	38, // 50: invocation.GetInvocationStatRequest.request_context:type_name -> context.RequestContext
	2,  // 51: invocation.GetInvocationStatRequest.aggregation_type:type_name -> invocation.AggType
	22, // 52: invocation.GetInvocationStatRequest.query:type_name -> invocation.InvocationStatQuery
	39, // 53: invocation.GetInvocationStatResponse.response_context:type_name -> context.ResponseContext
	21, // 54: invocation.GetInvocationStatResponse.invocation_stat:type_name -> invocation.InvocationStat
	38, // 55: invocation.GetInvocationFilterSuggestionsRequest.request_context:type_name -> context.RequestContext
	43, // 56: invocation.GetInvocationFilterSuggestionsRequest.filters:type_name -> stat_filter.GenericFilter
	39, // 57: invocation.GetInvocationFilterSuggestionsResponse.response_context:type_name -> context.ResponseContext
	43, // 58: invocation.GetInvocationFilterSuggestionsResponse.suggestions:type_name -> stat_filter.GenericFilter
	59, // [59:59] is the sub-list for method output_type
	59, // [59:59] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_proto_invocation_proto_init() }
func file_proto_invocation_proto_init() {
	if File_proto_invocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_invocation_proto_rawDesc), len(file_proto_invocation_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_invocation_proto_goTypes,
		DependencyIndexes: file_proto_invocation_proto_depIdxs,
		EnumInfos:         file_proto_invocation_proto_enumTypes,
		MessageInfos:      file_proto_invocation_proto_msgTypes,
	}.Build()
	File_proto_invocation_proto = out.File
	file_proto_invocation_proto_goTypes = nil
	file_proto_invocation_proto_depIdxs = nil
}
