// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/trace.proto

package trace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_trace_proto protoreflect.FileDescriptor

const file_proto_trace_proto_rawDesc = "" +
	"\n" +
	"\x11proto/trace.proto\x12\x05trace\"~\n" +
	"\bMetadata\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.trace.Metadata.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01b\x06proto3"

var (
	file_proto_trace_proto_rawDescOnce sync.Once
	file_proto_trace_proto_rawDescData []byte
)

func file_proto_trace_proto_rawDescGZIP() []byte {
	file_proto_trace_proto_rawDescOnce.Do(func() {
		file_proto_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trace_proto_rawDesc), len(file_proto_trace_proto_rawDesc)))
	})
	return file_proto_trace_proto_rawDescData
}

var file_proto_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trace_proto_goTypes = []any{
	(*Metadata)(nil), // 0: trace.Metadata
	nil,              // 1: trace.Metadata.EntriesEntry
}
var file_proto_trace_proto_depIdxs = []int32{
	1, // 0: trace.Metadata.entries:type_name -> trace.Metadata.EntriesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trace_proto_init() }
func file_proto_trace_proto_init() {
	if File_proto_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trace_proto_rawDesc), len(file_proto_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trace_proto_goTypes,
		DependencyIndexes: file_proto_trace_proto_depIdxs,
		MessageInfos:      file_proto_trace_proto_msgTypes,
	}.Build()
	File_proto_trace_proto = out.File
	file_proto_trace_proto_goTypes = nil
	file_proto_trace_proto_depIdxs = nil
}
